// generated by newgenasym  Tue Jun 29 10:47:56 2004


module hcnr201_300 (a, b, c, y1, y2, y3);
    input a;
    input b;
    input c;
    output y1;
    output y2;
    output y3;


    initial
        begin
        end

endmodule
