-- generated by newgenasym Tue Jun 29 10:47:56 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hcnr201_300 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	C:         IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC;    
	Y3:        OUT    STD_LOGIC);
end hcnr201_300;
