// generated by newgenasym  Mon Jan 05 16:45:45 2004


module mpv3b (in, \in+ , \in- , \out+ , \out- );
    input in;
    input \in+ ;
    input \in- ;
    output \out+ ;
    output \out- ;


    initial
        begin
        end

endmodule
