-- generated by newgenasym Mon Jan 05 16:45:45 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mpv3b is
    port (    
	\in\:      IN     STD_LOGIC;    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\out+\:    OUT    STD_LOGIC;    
	\out-\:    OUT    STD_LOGIC);
end mpv3b;
