// generated by newgenasym  Thu Aug 16 11:40:26 2018


module tql9093 (rfin, rfout, sdwn, vbias);
    inout rfin;
    inout rfout;
    inout sdwn;
    inout vbias;


    initial
        begin
        end

endmodule
