-- generated by newgenasym Thu Aug 16 11:40:26 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tql9093 is
    port (    
	RFIN:      INOUT  STD_LOGIC;    
	RFOUT:     INOUT  STD_LOGIC;    
	SDWN:      INOUT  STD_LOGIC;    
	VBIAS:     INOUT  STD_LOGIC);
end tql9093;
