-- generated by newgenasym Thu Feb 21 18:12:50 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity salf is
    port (    
	INPUT:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC);
end salf;
