-- generated by newgenasym Mon Aug 30 19:01:22 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \mms-125-02-l-dh\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (25 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (25 DOWNTO 1));
end \mms-125-02-l-dh\;
