// generated by newgenasym  Wed Oct 22 14:46:57 2003


module xc18v512so20i (\ce* , \ceo* , \cf/d4* , clk, d1, d2, d3, d5, d6, d7, data, \oe/reset* ,
        tck, tdi, tdo, tms);
    input \ce* ;
    output \ceo* ;
    output \cf/d4* ;
    input clk;
    output d1;
    output d2;
    output d3;
    output d5;
    output d6;
    output d7;
    output data;
    input \oe/reset* ;
    input tck;
    input tdi;
    output tdo;
    input tms;


    initial
        begin
        end

endmodule
