-- generated by newgenasym Wed Oct 22 14:46:57 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xc18v512so20i is
    port (    
	\ce*\:     IN     STD_LOGIC;    
	\ceo*\:    OUT    STD_LOGIC;    
	\cf/d4*\:  OUT    STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	D1:        OUT    STD_LOGIC;    
	D2:        OUT    STD_LOGIC;    
	D3:        OUT    STD_LOGIC;    
	D5:        OUT    STD_LOGIC;    
	D6:        OUT    STD_LOGIC;    
	D7:        OUT    STD_LOGIC;    
	DATA:      OUT    STD_LOGIC;    
	\oe/reset*\: IN     STD_LOGIC;    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       IN     STD_LOGIC);
end xc18v512so20i;
