-- generated by newgenasym Mon Jun 17 15:39:48 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dvi_74320 is
    port (    
	C1:        INOUT  STD_LOGIC;    
	C10:       INOUT  STD_LOGIC;    
	C11:       INOUT  STD_LOGIC;    
	C12:       INOUT  STD_LOGIC;    
	C13:       INOUT  STD_LOGIC;    
	C14:       INOUT  STD_LOGIC;    
	C15:       INOUT  STD_LOGIC;    
	C16:       INOUT  STD_LOGIC;    
	C17:       INOUT  STD_LOGIC;    
	C18:       INOUT  STD_LOGIC;    
	C19:       INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	C20:       INOUT  STD_LOGIC;    
	C21:       INOUT  STD_LOGIC;    
	C22:       INOUT  STD_LOGIC;    
	C23:       INOUT  STD_LOGIC;    
	C24:       INOUT  STD_LOGIC;    
	C3:        INOUT  STD_LOGIC;    
	C4:        INOUT  STD_LOGIC;    
	C5:        INOUT  STD_LOGIC;    
	C6:        INOUT  STD_LOGIC;    
	C7:        INOUT  STD_LOGIC;    
	C8:        INOUT  STD_LOGIC;    
	C9:        INOUT  STD_LOGIC;    
	PW1:       INOUT  STD_LOGIC;    
	PW2:       INOUT  STD_LOGIC;    
	PW3:       INOUT  STD_LOGIC;    
	PW4:       INOUT  STD_LOGIC;    
	PW5:       INOUT  STD_LOGIC;    
	PW6:       INOUT  STD_LOGIC);
end dvi_74320;
