// generated by newgenasym  Tue Aug 05 18:55:52 2014


module mt41j128m8v2 (a0, a1, a10, a11, \a12/bc# , a13, a2, a3, a4, a5, a6, a7, a8, a9,
        ba0, ba1, ba2, \cas# , ck, \ck# , cke, \cs# , \dm/tdqs , dq0, dq1, dq2,
        dq3, dq4, dq5, dq6, dq7, dqs, \dqs# , odt, \ras# , \reset# , \tdqs# ,
        \we# , zq);
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout \a12/bc# ;
    inout a13;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout ba2;
    inout \cas# ;
    inout ck;
    inout \ck# ;
    inout cke;
    inout \cs# ;
    inout \dm/tdqs ;
    inout dq0;
    inout dq1;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dqs;
    inout \dqs# ;
    inout odt;
    inout \ras# ;
    inout \reset# ;
    inout \tdqs# ;
    inout \we# ;
    inout zq;


    initial
        begin
        end

endmodule
