-- generated by newgenasym Tue Aug 22 18:15:14 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \dbtc-12-4\ is
    port (    
	COUP:      INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \dbtc-12-4\;
