// generated by newgenasym  Wed Dec 14 12:55:25 2011


module ds25br150 (\in+ , \in- , \out+ , \out- );
    inout \in+ ;
    inout \in- ;
    inout \out+ ;
    inout \out- ;


    initial
        begin
        end

endmodule
