-- generated by newgenasym Wed Dec 14 12:55:25 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds25br150 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out+\:    INOUT  STD_LOGIC;    
	\out-\:    INOUT  STD_LOGIC);
end ds25br150;
