-- generated by newgenasym Mon Jun 21 16:50:38 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BLM18A is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end BLM18A;
