-- generated by newgenasym Wed Aug 29 15:31:50 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tbu-ca\ is
    port (    
	L1:        INOUT  STD_LOGIC;    
	L2:        INOUT  STD_LOGIC);
end \tbu-ca\;
