-- generated by newgenasym Fri Apr 22 13:39:09 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hg8002 is
    port (    
	OE:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end hg8002;
