// generated by newgenasym  Fri Apr 19 18:51:31 2013


module tlp117 (gnd, vcc, \vd+ , \vd- , vout);
    input gnd;
    input vcc;
    inout \vd+ ;
    inout \vd- ;
    inout vout;


    initial
        begin
        end

endmodule
