-- generated by newgenasym Fri Apr 19 18:51:31 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlp117 is
    port (    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\vd+\:     INOUT  STD_LOGIC;    
	\vd-\:     INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end tlp117;
