// generated by newgenasym  Wed Dec 28 17:58:22 2011


module lm6181 (\+in , \-in , out, \v+ , \v- );
    inout \+in ;
    inout \-in ;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
