-- generated by newgenasym Wed Dec 28 17:58:22 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm6181 is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end lm6181;
