// generated by newgenasym  Fri Mar 12 14:00:26 2010


module tsm0505s (\+v0 , \+vin , \-v0 , \-vin );
    inout \+v0 ;
    inout \+vin ;
    inout \-v0 ;
    inout \-vin ;


    initial
        begin
        end

endmodule
