-- generated by newgenasym Fri Mar 12 14:00:26 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tsm0505s is
    port (    
	\+v0\:     INOUT  STD_LOGIC;    
	\+vin\:    INOUT  STD_LOGIC;    
	\-v0\:     INOUT  STD_LOGIC;    
	\-vin\:    INOUT  STD_LOGIC);
end tsm0505s;
