-- generated by newgenasym Wed Jul 09 16:57:41 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nl27wz17 is
    port (    
	A:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end nl27wz17;
