-- generated by newgenasym Mon Jan 12 12:07:49 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pvdz172n is
    port (    
	\1a\:      IN     STD_LOGIC;    
	\2a\:      IN     STD_LOGIC;    
	\3a\:      IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end pvdz172n;
