// generated by newgenasym  Mon Sep 10 11:46:02 2012


module adrf6806 (clk, cpout, data, decl1, decl2, decl3, ibbn, ibbp, le, lon,
        lop, losel, muxout, qbbn, qbbp, refin, rfin, rfip, rset, vccbb,
        vocm, vtune);
    inout clk;
    inout cpout;
    inout data;
    inout decl1;
    inout decl2;
    inout decl3;
    inout ibbn;
    inout ibbp;
    inout le;
    inout lon;
    inout lop;
    inout losel;
    inout muxout;
    inout qbbn;
    inout qbbp;
    inout refin;
    inout rfin;
    inout rfip;
    inout rset;
    inout vccbb;
    inout vocm;
    inout vtune;


    initial
        begin
        end

endmodule
