-- generated by newgenasym Mon Sep 10 11:46:02 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adrf6806 is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	CPOUT:     INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	DECL1:     INOUT  STD_LOGIC;    
	DECL2:     INOUT  STD_LOGIC;    
	DECL3:     INOUT  STD_LOGIC;    
	IBBN:      INOUT  STD_LOGIC;    
	IBBP:      INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	LON:       INOUT  STD_LOGIC;    
	LOP:       INOUT  STD_LOGIC;    
	LOSEL:     INOUT  STD_LOGIC;    
	MUXOUT:    INOUT  STD_LOGIC;    
	QBBN:      INOUT  STD_LOGIC;    
	QBBP:      INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	RFIP:      INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	VCCBB:     INOUT  STD_LOGIC;    
	VOCM:      INOUT  STD_LOGIC;    
	VTUNE:     INOUT  STD_LOGIC);
end adrf6806;
