// generated by newgenasym  Wed May 03 15:51:33 2017


module ds90lv804 (en, \in0+ , \in0- , \in1+ , \in1- , \in2+ , \in2- , \in3+ , \in3- , \out0+ ,
        \out0- , \out1+ , \out1- , \out2+ , \out2- , \out3+ , \out3- );
    inout en;
    inout \in0+ ;
    inout \in0- ;
    inout \in1+ ;
    inout \in1- ;
    inout \in2+ ;
    inout \in2- ;
    inout \in3+ ;
    inout \in3- ;
    inout \out0+ ;
    inout \out0- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out2+ ;
    inout \out2- ;
    inout \out3+ ;
    inout \out3- ;


    initial
        begin
        end

endmodule
