-- generated by newgenasym Wed May 03 15:51:33 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90lv804 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	\in0+\:    INOUT  STD_LOGIC;    
	\in0-\:    INOUT  STD_LOGIC;    
	\in1+\:    INOUT  STD_LOGIC;    
	\in1-\:    INOUT  STD_LOGIC;    
	\in2+\:    INOUT  STD_LOGIC;    
	\in2-\:    INOUT  STD_LOGIC;    
	\in3+\:    INOUT  STD_LOGIC;    
	\in3-\:    INOUT  STD_LOGIC;    
	\out0+\:   INOUT  STD_LOGIC;    
	\out0-\:   INOUT  STD_LOGIC;    
	\out1+\:   INOUT  STD_LOGIC;    
	\out1-\:   INOUT  STD_LOGIC;    
	\out2+\:   INOUT  STD_LOGIC;    
	\out2-\:   INOUT  STD_LOGIC;    
	\out3+\:   INOUT  STD_LOGIC;    
	\out3-\:   INOUT  STD_LOGIC);
end ds90lv804;
