// generated by newgenasym  Thu Aug 31 16:28:59 2017


module adp2384 (bst, comp, en, fb, pgood, pvin1, pvin2, pvin3, pvin4, rt, ss,
        sw1, sw2, sw3, sw4, sw_p, sync, vreg);
    inout bst;
    inout comp;
    inout en;
    inout fb;
    inout pgood;
    inout pvin1;
    inout pvin2;
    inout pvin3;
    inout pvin4;
    inout rt;
    inout ss;
    inout sw1;
    inout sw2;
    inout sw3;
    inout sw4;
    inout sw_p;
    inout sync;
    inout vreg;


    initial
        begin
        end

endmodule
