// generated by newgenasym  Wed Aug 26 13:10:01 2020


module pc817 (anode, cathode, collector, emitter);
    inout anode;
    inout cathode;
    inout collector;
    inout emitter;


    initial
        begin
        end

endmodule
