-- generated by newgenasym Wed Aug 26 13:10:01 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pc817 is
    port (    
	ANODE:     INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC;    
	COLLECTOR: INOUT  STD_LOGIC;    
	EMITTER:   INOUT  STD_LOGIC);
end pc817;
