-- generated by newgenasym Wed Mar 23 11:32:52 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity JUMP5 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end JUMP5;
