// generated by newgenasym  Mon Sep 13 12:21:58 2004


module xcv18vxxx (\ce* , \ceo* , \cf* , clk, d, d0, \oe_rst* , tck, tdi, tdo, tms);
    input \ce* ;
    output \ceo* ;
    output \cf* ;
    input clk;
    output [7:1] d;
    output d0;
    input \oe_rst* ;
    input tck;
    input tdi;
    output tdo;
    input tms;


    initial
        begin
        end

endmodule
