-- generated by newgenasym Mon Sep 13 12:21:58 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xcv18vxxx is
    port (    
	\ce*\:     IN     STD_LOGIC;    
	\ceo*\:    OUT    STD_LOGIC;    
	\cf*\:     OUT    STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	D:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 1);    
	D0:        OUT    STD_LOGIC;    
	\oe_rst*\: IN     STD_LOGIC;    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       IN     STD_LOGIC);
end xcv18vxxx;
