-- generated by newgenasym Wed Apr 26 15:56:18 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sda03 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end sda03;
