// generated by newgenasym  Wed Jun 14 16:23:00 2006


module max3485eesa (a, \b* , de, di, \re* , ro);
    input a;
    input \b* ;
    input de;
    input di;
    input \re* ;
    input ro;


    initial
        begin
        end

endmodule
