-- generated by newgenasym Fri Nov 28 17:13:19 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \fs-138b23\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \fs-138b23\;
