-- generated by newgenasym Tue Aug 31 15:24:56 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ssm-107-s-dv-lc\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (7 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (7 DOWNTO 1));
end \ssm-107-s-dv-lc\;
