// generated by newgenasym  Wed Oct 15 13:11:36 2003


module c_jtag (a1, a2, a3, a4, a5, y1, y2, y3, y4, y5);
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    output y1;
    output y2;
    output y3;
    output y4;
    output y5;


    initial
        begin
        end

endmodule
