-- generated by newgenasym Wed Oct 15 13:11:36 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity C_JTAG is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC;    
	Y3:        OUT    STD_LOGIC;    
	Y4:        OUT    STD_LOGIC;    
	Y5:        OUT    STD_LOGIC);
end C_JTAG;
