// generated by newgenasym  Mon Mar 14 10:58:34 2005


module \25lc040  (\cs* , \hold* , miso, mosi, sck, \wp* );
    input \cs* ;
    input \hold* ;
    output miso;
    input mosi;
    input sck;
    input \wp* ;


    initial
        begin
        end

endmodule
