// generated by newgenasym  Wed Dec 14 17:51:45 2011


module adm2486v2 (a, b, de, pv, re_n, rts, rxd, txd);
    inout a;
    inout b;
    inout de;
    inout pv;
    inout re_n;
    inout rts;
    inout rxd;
    inout txd;


    initial
        begin
        end

endmodule
