-- generated by newgenasym Wed Dec 14 17:51:45 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm2486v2 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DE:        INOUT  STD_LOGIC;    
	PV:        INOUT  STD_LOGIC;    
	RE_N:      INOUT  STD_LOGIC;    
	RTS:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC);
end adm2486v2;
