// generated by newgenasym  Mon Dec 20 15:22:48 2004


module hcpl_0930 (gnd1, gnd2, in1, in2, out1, out2, vdd1, vdd2);
    input gnd1;
    input gnd2;
    input in1;
    input in2;
    output out1;
    output out2;
    input vdd1;
    input vdd2;


    initial
        begin
        end

endmodule
