-- generated by newgenasym Mon Dec 20 15:22:48 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HCPL_0930 is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	IN1:       IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC);
end HCPL_0930;
