-- generated by newgenasym Thu Oct 26 17:32:57 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \gk153-un\ is
    port (    
	FOUT:      INOUT  STD_LOGIC;    
	VUPR:      INOUT  STD_LOGIC);
end \gk153-un\;
