// generated by newgenasym  Wed Aug 06 12:05:25 2014


module k5101hb015 (biasmode, biassel1, biassel2, \calrun/splin , clk, clko,
        cmin, csb, inn, inp, lvdsen, nclk, nclko, \oen/sclk ,
        \ovfl/spi_out , pd, q0, q1, q10, q11, q12, q12sel, q13, q2, q3, q4,
        q5, q6, q7, q8, q9, refen, scanen, vref1, vref2);
    inout biasmode;
    inout biassel1;
    inout biassel2;
    inout \calrun/splin ;
    inout clk;
    inout clko;
    inout cmin;
    inout csb;
    inout inn;
    inout inp;
    inout lvdsen;
    inout nclk;
    inout nclko;
    inout \oen/sclk ;
    inout \ovfl/spi_out ;
    inout pd;
    inout q0;
    inout q1;
    inout q10;
    inout q11;
    inout q12;
    inout q12sel;
    inout q13;
    inout q2;
    inout q3;
    inout q4;
    inout q5;
    inout q6;
    inout q7;
    inout q8;
    inout q9;
    inout refen;
    inout scanen;
    inout vref1;
    inout vref2;


    initial
        begin
        end

endmodule
