// generated by newgenasym  Tue Jul 01 15:12:45 2003


module hcpl0930 (\1in , \1out , \2in , \2out , gnd1, gnd2, vdd1, vdd2);
    input \1in ;
    output \1out ;
    input \2in ;
    output \2out ;
    input gnd1;
    input gnd2;
    input vdd1;
    input vdd2;


    initial
        begin
        end

endmodule
