-- generated by newgenasym Thu Jul 15 16:20:59 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \fis-10_7\ is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	GND5:      IN     STD_LOGIC;    
	GND6:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end \fis-10_7\;
