-- generated by newgenasym Thu Jul 29 18:15:57 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pvm4a_1 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC);
end pvm4a_1;
