-- generated by newgenasym Thu Dec 22 12:05:27 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tx1-1\ is
    port (    
	PRI:       INOUT  STD_LOGIC;    
	PRI_DOT:   INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_DOT:   INOUT  STD_LOGIC);
end \tx1-1\;
