// generated by newgenasym  Thu Jul 19 16:37:27 2007


module \at-106  (\+vcc , \-vcc , c1, c16, c2, c32, c4, c8, gnd1, gnd10, gnd11, gnd12,
        gnd13, gnd14, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9,
        rf1, rf2);
    inout \+vcc ;
    inout \-vcc ;
    inout c1;
    inout c16;
    inout c2;
    inout c32;
    inout c4;
    inout c8;
    input gnd1;
    input gnd10;
    input gnd11;
    input gnd12;
    input gnd13;
    input gnd14;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    inout rf1;
    inout rf2;


    initial
        begin
        end

endmodule
