-- generated by newgenasym Tue Dec 06 17:06:24 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fin1002 is
    port (    
	\rin+\:    INOUT  STD_LOGIC;    
	\rin-\:    INOUT  STD_LOGIC;    
	ROUT:      INOUT  STD_LOGIC);
end fin1002;
