// generated by newgenasym  Mon Aug 30 19:07:23 2004


module sn74lv164a (a, b, clk, \clr* , q);
    input a;
    input b;
    input clk;
    input \clr* ;
    output [7:0] q;


    initial
        begin
        end

endmodule
