-- generated by newgenasym Mon Aug 30 19:07:23 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lv164a is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	\clr*\:    IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0));
end sn74lv164a;
