// generated by newgenasym  Fri Jul 13 15:00:47 2007


module max253 (d1, d2, fs, gnd1, gnd2, sd, vcc);
    inout d1;
    inout d2;
    inout fs;
    inout gnd1;
    inout gnd2;
    inout sd;
    inout vcc;


    initial
        begin
        end

endmodule
