-- generated by newgenasym Fri Jul 13 15:00:47 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max253 is
    port (    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	FS:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	SD:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end max253;
