// generated by newgenasym  Fri Jun 04 13:10:42 2004


module \dc/dc_4_6w  (\v1in+ , \v1in- , \v1o+ , \v1o- , \v2in+ , \v2in- , \v2o+ , \v2o- , \v3in+ ,
        \v3in- , \v3o+ , \v3o- );
    input \v1in+ ;
    input \v1in- ;
    output \v1o+ ;
    output \v1o- ;
    input \v2in+ ;
    input \v2in- ;
    output \v2o+ ;
    output \v2o- ;
    input \v3in+ ;
    input \v3in- ;
    output \v3o+ ;
    output \v3o- ;


    initial
        begin
        end

endmodule
