// generated by newgenasym  Mon Jun 07 17:02:10 2004


module max7424 (clk, com, gndd, in, os, out, p3v3, \shdn* );
    input clk;
    input com;
    input gndd;
    input in;
    input os;
    output out;
    input p3v3;
    input \shdn* ;


    initial
        begin
        end

endmodule
