-- generated by newgenasym Mon Jun 07 17:02:10 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max7424 is
    port (    
	CLK:       IN     STD_LOGIC;    
	COM:       IN     STD_LOGIC;    
	GNDD:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	OS:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P3V3:      IN     STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC);
end max7424;
