// generated by newgenasym  Wed Dec 09 14:29:16 2009


module adg1206 (a0, a1, a2, a3, d, en, s1, s10, s11, s12, s13, s14, s15, s16, s2,
        s3, s4, s5, s6, s7, s8, s9);
    inout a0;
    inout a1;
    inout a2;
    inout a3;
    inout d;
    inout en;
    inout s1;
    inout s10;
    inout s11;
    inout s12;
    inout s13;
    inout s14;
    inout s15;
    inout s16;
    inout s2;
    inout s3;
    inout s4;
    inout s5;
    inout s6;
    inout s7;
    inout s8;
    inout s9;


    initial
        begin
        end

endmodule
