-- generated by newgenasym Wed Dec 09 14:29:16 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adg1206 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S10:       INOUT  STD_LOGIC;    
	S11:       INOUT  STD_LOGIC;    
	S12:       INOUT  STD_LOGIC;    
	S13:       INOUT  STD_LOGIC;    
	S14:       INOUT  STD_LOGIC;    
	S15:       INOUT  STD_LOGIC;    
	S16:       INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC;    
	S3:        INOUT  STD_LOGIC;    
	S4:        INOUT  STD_LOGIC;    
	S5:        INOUT  STD_LOGIC;    
	S6:        INOUT  STD_LOGIC;    
	S7:        INOUT  STD_LOGIC;    
	S8:        INOUT  STD_LOGIC;    
	S9:        INOUT  STD_LOGIC);
end adg1206;
