// generated by newgenasym  Tue Jul 01 14:35:41 2003


module pkf2610asi (\in+ , \in- , \nor , out1, rc, rtn, sync, toa, vadj);
    input \in+ ;
    input \in- ;
    input \nor ;
    output out1;
    input rc;
    output rtn;
    input sync;
    input toa;
    input vadj;


    initial
        begin
        end

endmodule
