-- generated by newgenasym Wed Aug 15 16:01:13 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adclk944 is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	CLKN:      INOUT  STD_LOGIC;    
	Q0N:       IN     STD_LOGIC;    
	Q0P:       IN     STD_LOGIC;    
	Q1N:       IN     STD_LOGIC;    
	Q1P:       IN     STD_LOGIC;    
	Q2N:       IN     STD_LOGIC;    
	Q2P:       IN     STD_LOGIC;    
	Q3N:       INOUT  STD_LOGIC;    
	Q3P:       INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VT:        INOUT  STD_LOGIC);
end adclk944;
