// generated by newgenasym  Wed Nov 08 16:18:08 2006


module \93lc46  (cs, di, do, org, sk);
    input cs;
    input di;
    output do;
    inout org;
    inout sk;


    initial
        begin
        end

endmodule
