-- generated by newgenasym Wed Nov 08 16:18:08 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \93lc46\ is
    port (    
	CS:        IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	DO:        OUT    STD_LOGIC;    
	ORG:       INOUT  STD_LOGIC;    
	SK:        INOUT  STD_LOGIC);
end \93lc46\;
