// generated by newgenasym  Thu Mar 18 10:40:29 2004


module sn74lvc2g00_1 (a1, a2, b1, b2, gndd, p5v0, \y1* , \y2* );
    input a1;
    input a2;
    input b1;
    input b2;
    input gndd;
    input p5v0;
    output \y1* ;
    output \y2* ;


    initial
        begin
        end

endmodule
