// generated by newgenasym  Wed Mar 23 17:40:02 2005


module max6736 (gnd, \mr* , \rst* , vcc1, vcc2);
    input gnd;
    input \mr* ;
    output \rst* ;
    inout vcc1;
    inout vcc2;


    initial
        begin
        end

endmodule
