// generated by newgenasym  Thu Apr 28 14:55:34 2005


module erni114809 (a, b, c, d, e, f);
    inout [22:1] a;
    inout [22:1] b;
    inout [22:1] c;
    inout [22:1] d;
    inout [22:1] e;
    inout [22:1] f;


    initial
        begin
        end

endmodule
