-- generated by newgenasym Thu Apr 28 14:55:34 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ERNI114809 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	C:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	D:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	E:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	F:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1));
end ERNI114809;
