// generated by newgenasym  Thu Jun 14 16:57:25 2007


module hmc586lc4b (gnd, gnd2, rfout, vcc, vtune);
    inout gnd;
    inout gnd2;
    inout rfout;
    inout vcc;
    inout vtune;


    initial
        begin
        end

endmodule
