-- generated by newgenasym Wed Dec 13 15:18:49 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpd4e02b04 is
    port (    
	IO1:       INOUT  STD_LOGIC;    
	IO1P:      INOUT  STD_LOGIC;    
	IO2:       INOUT  STD_LOGIC;    
	IO2P:      INOUT  STD_LOGIC;    
	IO3:       INOUT  STD_LOGIC;    
	IO3P:      INOUT  STD_LOGIC;    
	IO4:       INOUT  STD_LOGIC;    
	IO4P:      INOUT  STD_LOGIC);
end tpd4e02b04;
