// generated by newgenasym  Wed Jul 02 16:58:34 2003


module tcn75mua (a0, a1, a2, \int/cmptr , scl, sda);
    input a0;
    input a1;
    input a2;
    output \int/cmptr ;
    input scl;
    inout sda;


    initial
        begin
        end

endmodule
