-- generated by newgenasym Wed Jul 02 16:58:34 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tcn75mua is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	\int/cmptr\: OUT    STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end tcn75mua;
