// generated by newgenasym  Mon Nov 17 14:10:01 2014


module lmk03806 (clkout0, \clkout0* , clkout1, \clkout1* , clkout10, \clkout10* ,
        clkout11, \clkout11* , clkout2, \clkout2* , clkout3, \clkout3* ,
        clkout4, \clkout4* , clkout5, \clkout5* , clkout6, \clkout6* ,
        clkout7, \clkout7* , clkout8, \clkout8* , clkout9, \clkout9* ,
        clkuwire, cpout, datauwire, \ftest/ld , gpout0, gpout1,
        ldobyp1, ldobyp2, leuwire, oscin, \oscin* , oscout0, \oscout0* ,
        oscout1, \oscout1* , readback, sync);
    inout clkout0;
    inout \clkout0* ;
    inout clkout1;
    inout \clkout1* ;
    inout clkout10;
    inout \clkout10* ;
    inout clkout11;
    inout \clkout11* ;
    inout clkout2;
    inout \clkout2* ;
    inout clkout3;
    inout \clkout3* ;
    inout clkout4;
    inout \clkout4* ;
    inout clkout5;
    inout \clkout5* ;
    inout clkout6;
    inout \clkout6* ;
    inout clkout7;
    inout \clkout7* ;
    inout clkout8;
    inout \clkout8* ;
    inout clkout9;
    inout \clkout9* ;
    inout clkuwire;
    inout cpout;
    inout datauwire;
    inout \ftest/ld ;
    inout gpout0;
    inout gpout1;
    inout ldobyp1;
    inout ldobyp2;
    inout leuwire;
    inout oscin;
    inout \oscin* ;
    inout oscout0;
    inout \oscout0* ;
    inout oscout1;
    inout \oscout1* ;
    inout readback;
    inout sync;


    initial
        begin
        end

endmodule
