-- generated by newgenasym Thu Feb 02 10:35:09 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity quarz is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end quarz;
