// generated by newgenasym  Tue Jul 19 16:58:14 2005


module max1615 (\5/3 , gnd, in, out, shdn);
    inout \5/3 ;
    input gnd;
    inout in;
    inout out;
    inout shdn;


    initial
        begin
        end

endmodule
