// generated by newgenasym  Mon Oct 13 16:54:49 2003


module itdqs3vh257q (\10b , \e* , i0a, i0c, i0d, i1a, i1b, i1c, i1d, s, ya, yb, yc, yd);
    input \10b ;
    input \e* ;
    input i0a;
    input i0c;
    input i0d;
    input i1a;
    input i1b;
    input i1c;
    input i1d;
    input s;
    output ya;
    output yb;
    output yc;
    output yd;


    initial
        begin
        end

endmodule
