-- generated by newgenasym Mon Oct 13 16:54:49 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity itdqs3vh257q is
    port (    
	\10b\:     IN     STD_LOGIC;    
	\e*\:      IN     STD_LOGIC;    
	I0A:       IN     STD_LOGIC;    
	I0C:       IN     STD_LOGIC;    
	I0D:       IN     STD_LOGIC;    
	I1A:       IN     STD_LOGIC;    
	I1B:       IN     STD_LOGIC;    
	I1C:       IN     STD_LOGIC;    
	I1D:       IN     STD_LOGIC;    
	S:         IN     STD_LOGIC;    
	YA:        OUT    STD_LOGIC;    
	YB:        OUT    STD_LOGIC;    
	YC:        OUT    STD_LOGIC;    
	YD:        OUT    STD_LOGIC);
end itdqs3vh257q;
