-- generated by newgenasym Tue Dec 15 16:54:40 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xcf04svo20 is
    port (    
	\ce#\:     INOUT  STD_LOGIC;    
	\ceo#\:    INOUT  STD_LOGIC;    
	\cf#\:     INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	DO:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\oe/reset#\: INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC;    
	TDO:       INOUT  STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC;    
	VCCINT:    INOUT  STD_LOGIC;    
	VCCJ:      INOUT  STD_LOGIC;    
	VCCO:      INOUT  STD_LOGIC);
end xcf04svo20;
