-- generated by newgenasym Tue Aug 31 15:07:08 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tsm-1-05-01-l-dv\ is
    generic (
        size:positive:= 1
            );
    port (    
	X:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end \tsm-1-05-01-l-dv\;
