-- generated by newgenasym Tue Aug 10 15:42:45 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlp281_4 is
    port (    
	AN1:       INOUT  STD_LOGIC;    
	AN2:       INOUT  STD_LOGIC;    
	AN3:       INOUT  STD_LOGIC;    
	AN4:       INOUT  STD_LOGIC;    
	CAT1:      INOUT  STD_LOGIC;    
	CAT2:      INOUT  STD_LOGIC;    
	CAT3:      INOUT  STD_LOGIC;    
	CAT4:      INOUT  STD_LOGIC;    
	EM1:       INOUT  STD_LOGIC;    
	EM2:       INOUT  STD_LOGIC;    
	EM3:       INOUT  STD_LOGIC;    
	EM4:       INOUT  STD_LOGIC;    
	VOUT1:     INOUT  STD_LOGIC;    
	VOUT2:     INOUT  STD_LOGIC;    
	VOUT3:     INOUT  STD_LOGIC;    
	VOUT4:     INOUT  STD_LOGIC);
end tlp281_4;
