-- generated by newgenasym Wed Apr 02 14:06:38 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8001 is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end ad8001;
