-- generated by newgenasym Mon Aug 30 19:29:49 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res;
