-- generated by newgenasym Fri Jun 04 16:01:54 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ent-125_01_s_d\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (50 DOWNTO 1));
end \ent-125_01_s_d\;
