// generated by newgenasym  Tue Aug 22 13:01:29 2017


module ads42jb69 (clkinm, clkinp, ctrl1, ctrl2, da0m, da0p, da1m, da1p, db0m,
        db0p, db1m, db1p, inam, inap, inbm, inbp, mode, ovra, ovrb,
        pdn_gbl, reset, sclk, sdata, sdout, sen, stby, sync_m, sync_p,
        sysrefm, sysrefp, vcm);
    inout clkinm;
    inout clkinp;
    inout ctrl1;
    inout ctrl2;
    inout da0m;
    inout da0p;
    inout da1m;
    inout da1p;
    inout db0m;
    inout db0p;
    inout db1m;
    inout db1p;
    inout inam;
    inout inap;
    inout inbm;
    inout inbp;
    inout mode;
    inout ovra;
    inout ovrb;
    inout pdn_gbl;
    inout reset;
    inout sclk;
    inout sdata;
    inout sdout;
    inout sen;
    inout stby;
    inout sync_m;
    inout sync_p;
    inout sysrefm;
    inout sysrefp;
    inout vcm;


    initial
        begin
        end

endmodule
