-- generated by newgenasym Tue Aug 22 13:01:29 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ads42jb69 is
    port (    
	CLKINM:    INOUT  STD_LOGIC;    
	CLKINP:    INOUT  STD_LOGIC;    
	CTRL1:     INOUT  STD_LOGIC;    
	CTRL2:     INOUT  STD_LOGIC;    
	DA0M:      INOUT  STD_LOGIC;    
	DA0P:      INOUT  STD_LOGIC;    
	DA1M:      INOUT  STD_LOGIC;    
	DA1P:      INOUT  STD_LOGIC;    
	DB0M:      INOUT  STD_LOGIC;    
	DB0P:      INOUT  STD_LOGIC;    
	DB1M:      INOUT  STD_LOGIC;    
	DB1P:      INOUT  STD_LOGIC;    
	INAM:      INOUT  STD_LOGIC;    
	INAP:      INOUT  STD_LOGIC;    
	INBM:      INOUT  STD_LOGIC;    
	INBP:      INOUT  STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	OVRA:      INOUT  STD_LOGIC;    
	OVRB:      INOUT  STD_LOGIC;    
	PDN_GBL:   INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	SDATA:     INOUT  STD_LOGIC;    
	SDOUT:     INOUT  STD_LOGIC;    
	SEN:       INOUT  STD_LOGIC;    
	STBY:      INOUT  STD_LOGIC;    
	SYNC_M:    INOUT  STD_LOGIC;    
	SYNC_P:    INOUT  STD_LOGIC;    
	SYSREFM:   INOUT  STD_LOGIC;    
	SYSREFP:   INOUT  STD_LOGIC;    
	VCM:       INOUT  STD_LOGIC);
end ads42jb69;
