-- generated by newgenasym Tue Jun 01 16:57:38 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fu is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end fu;
