-- generated by newgenasym Thu Nov 01 14:51:03 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r1lv0816asb is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A10:       INOUT  STD_LOGIC;    
	A11:       INOUT  STD_LOGIC;    
	A12:       INOUT  STD_LOGIC;    
	A13:       INOUT  STD_LOGIC;    
	A14:       INOUT  STD_LOGIC;    
	A15:       INOUT  STD_LOGIC;    
	A16:       INOUT  STD_LOGIC;    
	A17:       INOUT  STD_LOGIC;    
	A18:       INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	A9:        INOUT  STD_LOGIC;    
	CE:        INOUT  STD_LOGIC;    
	IO0:       INOUT  STD_LOGIC;    
	IO1:       INOUT  STD_LOGIC;    
	IO10:      INOUT  STD_LOGIC;    
	IO11:      INOUT  STD_LOGIC;    
	IO12:      INOUT  STD_LOGIC;    
	IO13:      INOUT  STD_LOGIC;    
	IO14:      INOUT  STD_LOGIC;    
	IO15:      INOUT  STD_LOGIC;    
	IO2:       INOUT  STD_LOGIC;    
	IO3:       INOUT  STD_LOGIC;    
	IO4:       INOUT  STD_LOGIC;    
	IO5:       INOUT  STD_LOGIC;    
	IO6:       INOUT  STD_LOGIC;    
	IO7:       INOUT  STD_LOGIC;    
	IO8:       INOUT  STD_LOGIC;    
	IO9:       INOUT  STD_LOGIC;    
	LB:        INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	UB:        INOUT  STD_LOGIC;    
	WE:        INOUT  STD_LOGIC);
end r1lv0816asb;
