// generated by newgenasym  Tue Feb 07 09:52:44 2006


module op213 (\+ina , \+inb , \-ina , \-inb , outa, outb, \v+ , \v- );
    input \+ina ;
    input \+inb ;
    input \-ina ;
    input \-inb ;
    output outa;
    output outb;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
