-- generated by newgenasym Tue May 14 16:37:39 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3207e is
    port (    
	I01:       INOUT  STD_LOGIC;    
	I02:       INOUT  STD_LOGIC);
end max3207e;
