-- generated by newgenasym Fri Jun 28 17:05:11 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cdce62005 is
    port (    
	AUX_IN:    INOUT  STD_LOGIC;    
	AUX_OUT:   OUT    STD_LOGIC;    
	EXT_LFN:   INOUT  STD_LOGIC;    
	EXT_LFP:   INOUT  STD_LOGIC;    
	PLL_LOCK:  INOUT  STD_LOGIC;    
	\pri_ref+\: INOUT  STD_LOGIC;    
	\pri_ref-\: INOUT  STD_LOGIC;    
	PWDWN:     IN     STD_LOGIC;    
	REF_SEL:   IN     STD_LOGIC;    
	REG_CAP1:  INOUT  STD_LOGIC;    
	REG_CAP2:  INOUT  STD_LOGIC;    
	\sec_ref+\: INOUT  STD_LOGIC;    
	\sec_ref-\: INOUT  STD_LOGIC;    
	SPI_CLK:   IN     STD_LOGIC;    
	SPI_LE:    IN     STD_LOGIC;    
	SPI_MISO:  OUT    STD_LOGIC;    
	SPI_MOSI:  IN     STD_LOGIC;    
	SYNC:      INOUT  STD_LOGIC;    
	TEST_MODE: IN     STD_LOGIC;    
	TESTOUTA:  OUT    STD_LOGIC;    
	U0N:       OUT    STD_LOGIC;    
	U0P:       OUT    STD_LOGIC;    
	U1N:       OUT    STD_LOGIC;    
	U1P:       OUT    STD_LOGIC;    
	U2N:       OUT    STD_LOGIC;    
	U2P:       OUT    STD_LOGIC;    
	U3N:       OUT    STD_LOGIC;    
	U3P:       OUT    STD_LOGIC;    
	U4N:       OUT    STD_LOGIC;    
	U4P:       OUT    STD_LOGIC);
end cdce62005;
