// generated by newgenasym  Wed Aug 01 10:24:25 2018


module m54 (a1_100n, a1_100p, a2_100n, a2_100p, clk10, clk125, contr,
        dsp100, get1n, get1p, get2n, get2p, in1, in2, ipwoff, nrst,
        pf1, pwr1v8, pwr1v8adc, pwr1v8d1, pwr2v5, pwr3v3d, pwr3v3d1,
        rtc, rx0, rx1, strb, sw0din, sw0dip, sw0don, sw0dop, sw0sin,
        sw0sip, sw0son, sw0sop, sw1d1n, sw1d1p, sw1don, sw1dop,
        sw1sin, sw1sip, sw1son, sw1sop, syncclr, syncgain, syncnco,
        syncstart, tck, tck_f, tdi, tdi_f, tdo, tms, trst, tst1, tst2,
        tx0, tx1, wdt);
    inout a1_100n;
    inout a1_100p;
    inout a2_100n;
    inout a2_100p;
    inout clk10;
    inout clk125;
    inout contr;
    inout dsp100;
    inout get1n;
    inout get1p;
    inout get2n;
    inout get2p;
    inout in1;
    inout in2;
    inout ipwoff;
    inout nrst;
    inout pf1;
    inout pwr1v8;
    inout pwr1v8adc;
    inout pwr1v8d1;
    inout pwr2v5;
    inout pwr3v3d;
    inout pwr3v3d1;
    inout rtc;
    inout rx0;
    inout rx1;
    inout strb;
    inout sw0din;
    inout sw0dip;
    inout sw0don;
    inout sw0dop;
    inout sw0sin;
    inout sw0sip;
    inout sw0son;
    inout sw0sop;
    inout sw1d1n;
    inout sw1d1p;
    inout sw1don;
    inout sw1dop;
    inout sw1sin;
    inout sw1sip;
    inout sw1son;
    inout sw1sop;
    inout syncclr;
    inout syncgain;
    inout syncnco;
    inout syncstart;
    inout tck;
    inout tck_f;
    inout tdi;
    inout tdi_f;
    inout tdo;
    inout tms;
    inout trst;
    inout tst1;
    inout tst2;
    inout tx0;
    inout tx1;
    inout wdt;


    initial
        begin
        end

endmodule
