// generated by newgenasym  Fri Jun 04 16:36:34 2004


module lp3852 (\error* , gndd, \sd* , v_in, v_out);
    input \error* ;
    inout gndd;
    input \sd* ;
    input v_in;
    output v_out;


    initial
        begin
        end

endmodule
