// generated by newgenasym  Mon Jun 18 11:13:33 2007


module \adf4360-7  (avdd, cc, ce, clk, cn, cp, cpgnd, data, dvdd, l1, l2, le,
        mux_out, ref_in, rf_outa, rf_outb, rset, vtune, vvco);
    inout avdd;
    inout cc;
    inout ce;
    inout clk;
    inout cn;
    inout cp;
    inout cpgnd;
    inout data;
    inout dvdd;
    inout l1;
    inout l2;
    inout le;
    inout mux_out;
    inout ref_in;
    inout rf_outa;
    inout rf_outb;
    inout rset;
    inout vtune;
    inout vvco;


    initial
        begin
        end

endmodule
