-- generated by newgenasym Mon Jun 18 11:13:33 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \adf4360-7\ is
    port (    
	AVDD:      INOUT  STD_LOGIC;    
	CC:        INOUT  STD_LOGIC;    
	CE:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CN:        INOUT  STD_LOGIC;    
	CP:        INOUT  STD_LOGIC;    
	CPGND:     INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	DVDD:      INOUT  STD_LOGIC;    
	L1:        INOUT  STD_LOGIC;    
	L2:        INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	MUX_OUT:   INOUT  STD_LOGIC;    
	REF_IN:    INOUT  STD_LOGIC;    
	RF_OUTA:   INOUT  STD_LOGIC;    
	RF_OUTB:   INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	VTUNE:     INOUT  STD_LOGIC;    
	VVCO:      INOUT  STD_LOGIC);
end \adf4360-7\;
