-- generated by newgenasym Fri Dec 15 13:41:19 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \usblc6-2\ is
    port (    
	I1:        INOUT  STD_LOGIC;    
	I2:        INOUT  STD_LOGIC;    
	O1:        INOUT  STD_LOGIC;    
	O2:        INOUT  STD_LOGIC);
end \usblc6-2\;
