-- generated by newgenasym Thu Dec 23 17:20:00 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max6825suk_t is
    port (    
	GND:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	RESET:     OUT    STD_LOGIC;    
	\reset*\:  OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end max6825suk_t;
