// generated by newgenasym  Tue Aug 31 18:04:01 2004


module microgigacn12x (chassis, g, s1, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19,
        s2, s20, s21, s22, s23, s24, s25, s26, s27, s28, s29, s3, s30, s31,
        s32, s33, s34, s35, s36, s37, s38, s39, s4, s40, s41, s42, s43,
        s44, s45, s46, s47, s48, s5, s6, s7, s8, s9);
    inout [2:1] chassis;
    inout [25:1] g;
    inout s1;
    inout s10;
    inout s11;
    inout s12;
    inout s13;
    inout s14;
    inout s15;
    inout s16;
    inout s17;
    inout s18;
    inout s19;
    inout s2;
    inout s20;
    inout s21;
    inout s22;
    inout s23;
    inout s24;
    inout s25;
    inout s26;
    inout s27;
    inout s28;
    inout s29;
    inout s3;
    inout s30;
    inout s31;
    inout s32;
    inout s33;
    inout s34;
    inout s35;
    inout s36;
    inout s37;
    inout s38;
    inout s39;
    inout s4;
    inout s40;
    inout s41;
    inout s42;
    inout s43;
    inout s44;
    inout s45;
    inout s46;
    inout s47;
    inout s48;
    inout s5;
    inout s6;
    inout s7;
    inout s8;
    inout s9;


    initial
        begin
        end

endmodule
