// generated by newgenasym  Wed Aug 23 18:37:05 2017


module si7236 (d1a, d1b, d2a, d2b, g1, g2, s1, s2);
    inout d1a;
    inout d1b;
    inout d2a;
    inout d2b;
    inout g1;
    inout g2;
    inout s1;
    inout s2;


    initial
        begin
        end

endmodule
