-- generated by newgenasym Wed Oct 27 17:00:19 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity QTE_020_50_NEW is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	GND:       INOUT  STD_LOGIC_VECTOR (82 DOWNTO 41));
end QTE_020_50_NEW;
