// generated by newgenasym  Thu Aug 16 13:56:15 2018


module hmc759 (acg0, acg1, acg2, acg3, clk, le, pup1, pup2, rf1, rf2, serin,
        serout);
    inout acg0;
    inout acg1;
    inout acg2;
    inout acg3;
    inout clk;
    inout le;
    inout pup1;
    inout pup2;
    inout rf1;
    inout rf2;
    inout serin;
    inout serout;


    initial
        begin
        end

endmodule
