-- generated by newgenasym Thu Aug 16 13:56:15 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc759 is
    port (    
	ACG0:      INOUT  STD_LOGIC;    
	ACG1:      INOUT  STD_LOGIC;    
	ACG2:      INOUT  STD_LOGIC;    
	ACG3:      INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	PUP1:      INOUT  STD_LOGIC;    
	PUP2:      INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	SERIN:     INOUT  STD_LOGIC;    
	SEROUT:    INOUT  STD_LOGIC);
end hmc759;
