-- generated by newgenasym Fri Aug 06 10:34:57 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity smm_125_02 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (25 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (25 DOWNTO 1));
end smm_125_02;
