-- generated by newgenasym Thu Nov 13 10:50:02 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       OUT    STD_LOGIC);
end c;
