// generated by newgenasym  Mon Jan 12 11:24:35 2004


module sn74lvc2g00 (\1a , \1b , \1y* , \2a , \2b , \2y* );
    input \1a ;
    input \1b ;
    output \1y* ;
    input \2a ;
    input \2b ;
    output \2y* ;


    initial
        begin
        end

endmodule
