-- generated by newgenasym Tue Mar 27 13:31:13 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1324uv2h4\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \1324uv2h4\;
