// generated by newgenasym  Tue Nov 18 11:13:33 2014


module mic39101 (en, flg, in, out);
    inout en;
    inout flg;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
