// generated by newgenasym  Mon Dec 08 16:31:17 2003


module cd74ac20m (a1, a2, a3, a4, a5, a6, a7, a8, \b1* , \b2* );
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    output \b1* ;
    output \b2* ;


    initial
        begin
        end

endmodule
