// generated by newgenasym  Tue Aug 31 16:45:20 2004


module cpci_peripheral_j1 (\ack64* , ad, \bd_sel* , brsvp1a5, brsvp1b5, \c_be0* , \c_be1* ,
        \c_be2* , \c_be3* , clk, \devsel* , \enum* , \frame* , gnd, gndl, \gnt* ,
        \healthy* , idsel, \inta* , \intb* , \intc* , \intd* , intp, ints,
        ipmb_pwr, ipmb_scl, ipmb_sda, \irdy* , \lock* , m66en, n12v0,
        p12v0, p3v3, p3v3l, p5v0, p5v0l, par, \perr* , \req* , \req64* ,
        \rst* , \serr* , \stop* , tck, tdi, tdo, tms, \trdy* , \trst* , vio, viol);
    inout \ack64* ;
    inout [31:0] ad;
    output \bd_sel* ;
    output brsvp1a5;
    output brsvp1b5;
    inout \c_be0* ;
    inout \c_be1* ;
    inout \c_be2* ;
    inout \c_be3* ;
    output clk;
    input \devsel* ;
    input \enum* ;
    inout \frame* ;
    input [31:0] gnd;
    input [5:0] gndl;
    output \gnt* ;
    input \healthy* ;
    output idsel;
    input \inta* ;
    input \intb* ;
    input \intc* ;
    input \intd* ;
    output intp;
    output ints;
    output ipmb_pwr;
    output ipmb_scl;
    output ipmb_sda;
    inout \irdy* ;
    inout \lock* ;
    output m66en;
    input n12v0;
    input p12v0;
    input [7:0] p3v3;
    input [1:0] p3v3l;
    input [5:0] p5v0;
    input [1:0] p5v0l;
    inout par;
    inout \perr* ;
    input \req* ;
    inout \req64* ;
    output \rst* ;
    inout \serr* ;
    inout \stop* ;
    output tck;
    input tdi;
    output tdo;
    output tms;
    inout \trdy* ;
    output \trst* ;
    input [2:0] vio;
    input [1:0] viol;


    initial
        begin
        end

endmodule
