-- generated by newgenasym Fri Dec 09 16:39:49 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adcmp600 is
    port (    
	Q:         INOUT  STD_LOGIC;    
	VN:        INOUT  STD_LOGIC;    
	VP:        INOUT  STD_LOGIC);
end adcmp600;
