// generated by newgenasym  Thu Mar 11 16:07:00 2004


module mpb3 (in, \in1+ , \in1- , \in2+ , \in2- , \out+ , \out- );
    input in;
    input \in1+ ;
    input \in1- ;
    input \in2+ ;
    input \in2- ;
    output \out+ ;
    output \out- ;


    initial
        begin
        end

endmodule
