-- generated by newgenasym Thu Mar 11 16:07:00 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MPB3 is
    port (    
	\in\:      IN     STD_LOGIC;    
	\in1+\:    IN     STD_LOGIC;    
	\in1-\:    IN     STD_LOGIC;    
	\in2+\:    IN     STD_LOGIC;    
	\in2-\:    IN     STD_LOGIC;    
	\out+\:    OUT    STD_LOGIC;    
	\out-\:    OUT    STD_LOGIC);
end MPB3;
