// generated by newgenasym  Fri Apr 19 14:32:45 2013


module \tes#202n_2421  (\+vin , \+vout , \-vin , \-vout , common);
    inout \+vin ;
    inout \+vout ;
    inout \-vin ;
    inout \-vout ;
    inout common;


    initial
        begin
        end

endmodule
