-- generated by newgenasym Mon Dec 05 12:06:46 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g08 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GNDDM:     INOUT  STD_LOGIC;    
	P3V3M:     INOUT  STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc1g08;
