-- generated by newgenasym Thu Jul 06 15:45:22 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ipl1_02 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ipl1_02;
