// generated by newgenasym  Mon Dec 26 14:55:03 2011


module \hswa2-30dr  (contr1, contr2, rf1, rf2, rf_com);
    inout contr1;
    inout contr2;
    inout rf1;
    inout rf2;
    inout rf_com;


    initial
        begin
        end

endmodule
