-- generated by newgenasym Mon Dec 26 14:55:03 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \hswa2-30dr\ is
    port (    
	CONTR1:    INOUT  STD_LOGIC;    
	CONTR2:    INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RF_COM:    INOUT  STD_LOGIC);
end \hswa2-30dr\;
