// generated by newgenasym  Wed Jun 06 10:28:39 2018


module \din-96_vme  (\+5v_stanby , \a01* , \a02* , \a03* , \a04* , \a05* , \a06* , \a07* , a08,
        a09, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21,
        a22, a23, \acfail* , am0, am0am1, am0am1am2, am0am1am2am3,
        \am4* , am5, \as* , \bbsy* , \bclr* , \berr* , \bg0in* , \bg0out* , \bg1in* ,
        \bg1out* , \bg2in* , \bg2out* , \bg3in* , \bg3out* , \br0* , \br1* , \br2* ,
        \br3* , d00, d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11,
        d12, d13, d14, d15, \ds0* , \ds1* , \dtack* , \iack* , \iackin* ,
        \iackout* , \irq1* , \irq2* , \irq3* , \irq4* , \irq5* , \irq6* , \irq7* ,
        \lword* , serclk, \serdat* , sysclk, \sysfail* , \sysreset* ,
        \write* );
    inout \+5v_stanby ;
    inout \a01* ;
    inout \a02* ;
    inout \a03* ;
    inout \a04* ;
    inout \a05* ;
    inout \a06* ;
    inout \a07* ;
    inout a08;
    inout a09;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a20;
    inout a21;
    inout a22;
    inout a23;
    inout \acfail* ;
    inout am0;
    inout am0am1;
    inout am0am1am2;
    inout am0am1am2am3;
    inout \am4* ;
    inout am5;
    inout \as* ;
    inout \bbsy* ;
    inout \bclr* ;
    inout \berr* ;
    inout \bg0in* ;
    inout \bg0out* ;
    inout \bg1in* ;
    inout \bg1out* ;
    inout \bg2in* ;
    inout \bg2out* ;
    inout \bg3in* ;
    inout \bg3out* ;
    inout \br0* ;
    inout \br1* ;
    inout \br2* ;
    inout \br3* ;
    inout d00;
    inout d01;
    inout d02;
    inout d03;
    inout d04;
    inout d05;
    inout d06;
    inout d07;
    inout d08;
    inout d09;
    inout d10;
    inout d11;
    inout d12;
    inout d13;
    inout d14;
    inout d15;
    inout \ds0* ;
    inout \ds1* ;
    inout \dtack* ;
    inout \iack* ;
    inout \iackin* ;
    inout \iackout* ;
    inout \irq1* ;
    inout \irq2* ;
    inout \irq3* ;
    inout \irq4* ;
    inout \irq5* ;
    inout \irq6* ;
    inout \irq7* ;
    inout \lword* ;
    inout serclk;
    inout \serdat* ;
    inout sysclk;
    inout \sysfail* ;
    inout \sysreset* ;
    inout \write* ;


    initial
        begin
        end

endmodule
