-- generated by newgenasym Mon Dec 11 10:16:46 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1338xk8y\ is
    port (    
	INN:       INOUT  STD_LOGIC;    
	INP:       INOUT  STD_LOGIC;    
	OUTN:      INOUT  STD_LOGIC;    
	OUTP:      INOUT  STD_LOGIC;    
	X1:        INOUT  STD_LOGIC;    
	X2:        INOUT  STD_LOGIC;    
	X3:        INOUT  STD_LOGIC;    
	X4:        INOUT  STD_LOGIC;    
	X5:        INOUT  STD_LOGIC;    
	X6:        INOUT  STD_LOGIC);
end \1338xk8y\;
