-- generated by newgenasym Thu Mar 01 18:59:26 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8304 is
    port (    
	ACOM:      INOUT  STD_LOGIC;    
	BFIN:      INOUT  STD_LOGIC;    
	BFNG:      INOUT  STD_LOGIC;    
	INPT:      INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	VLOG:      INOUT  STD_LOGIC;    
	VNEG:      INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VPDB:      INOUT  STD_LOGIC;    
	VPS1:      INOUT  STD_LOGIC;    
	VPS2:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ad8304;
