// generated by newgenasym  Wed Sep 05 11:23:42 2012


module adl5331 (enbl, gain, inhi, inho, ipbs, opbs, ophi, opho);
    inout enbl;
    inout gain;
    inout inhi;
    inout inho;
    inout ipbs;
    inout opbs;
    inout ophi;
    inout opho;


    initial
        begin
        end

endmodule
