-- generated by newgenasym Wed Sep 05 11:23:42 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5331 is
    port (    
	ENBL:      INOUT  STD_LOGIC;    
	GAIN:      INOUT  STD_LOGIC;    
	INHI:      INOUT  STD_LOGIC;    
	INHO:      INOUT  STD_LOGIC;    
	IPBS:      INOUT  STD_LOGIC;    
	OPBS:      INOUT  STD_LOGIC;    
	OPHI:      INOUT  STD_LOGIC;    
	OPHO:      INOUT  STD_LOGIC);
end adl5331;
