-- generated by newgenasym Thu Jun 17 18:21:11 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps5461x is
    port (    
	AGND:      IN     STD_LOGIC;    
	BOOT:      IN     STD_LOGIC;    
	FSEL:      IN     STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC_VECTOR (5 DOWNTO 1);    
	PH:        INOUT  STD_LOGIC_VECTOR (9 DOWNTO 1);    
	PWRGD:     OUT    STD_LOGIC;    
	PWRPAD:    IN     STD_LOGIC;    
	RT:        IN     STD_LOGIC;    
	SS_ENA:    OUT    STD_LOGIC;    
	VBIAS:     INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC_VECTOR (5 DOWNTO 1);    
	VSENSE:    IN     STD_LOGIC);
end tps5461x;
