// generated by newgenasym  Tue Sep 25 10:56:58 2007


module xp3 (\+5vm , \0vm , \0vm1 , \0vm2 , \0vm3 , \0vm4 , \0vm5 , \0vm6 , \0vm7 , \0vm8 ,
        kontr_rx_0, kontr_rx_1, kontr_tx_0, kontr_tx_1,
        kvkl_msh1u, kvkl_mshu2, kvkl_rba, scl, sda, u_ac, udet_uaru,
        vkl_mshu1, vkl_mshu2, vkl_rba);
    inout \+5vm ;
    inout \0vm ;
    inout \0vm1 ;
    inout \0vm2 ;
    inout \0vm3 ;
    inout \0vm4 ;
    inout \0vm5 ;
    inout \0vm6 ;
    inout \0vm7 ;
    inout \0vm8 ;
    inout kontr_rx_0;
    inout kontr_rx_1;
    inout kontr_tx_0;
    inout kontr_tx_1;
    inout kvkl_msh1u;
    inout kvkl_mshu2;
    inout kvkl_rba;
    inout scl;
    inout sda;
    inout u_ac;
    inout udet_uaru;
    inout vkl_mshu1;
    inout vkl_mshu2;
    inout vkl_rba;


    initial
        begin
        end

endmodule
