-- generated by newgenasym Tue Sep 25 10:56:58 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XP3 is
    port (    
	\+5vm\:    INOUT  STD_LOGIC;    
	\0vm\:     INOUT  STD_LOGIC;    
	\0vm1\:    INOUT  STD_LOGIC;    
	\0vm2\:    INOUT  STD_LOGIC;    
	\0vm3\:    INOUT  STD_LOGIC;    
	\0vm4\:    INOUT  STD_LOGIC;    
	\0vm5\:    INOUT  STD_LOGIC;    
	\0vm6\:    INOUT  STD_LOGIC;    
	\0vm7\:    INOUT  STD_LOGIC;    
	\0vm8\:    INOUT  STD_LOGIC;    
	KONTR_RX_0: INOUT  STD_LOGIC;    
	KONTR_RX_1: INOUT  STD_LOGIC;    
	KONTR_TX_0: INOUT  STD_LOGIC;    
	KONTR_TX_1: INOUT  STD_LOGIC;    
	KVKL_MSH1U: INOUT  STD_LOGIC;    
	KVKL_MSHU2: INOUT  STD_LOGIC;    
	KVKL_RBA:  INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	U_AC:      INOUT  STD_LOGIC;    
	UDET_UARU: INOUT  STD_LOGIC;    
	VKL_MSHU1: INOUT  STD_LOGIC;    
	VKL_MSHU2: INOUT  STD_LOGIC;    
	VKL_RBA:   INOUT  STD_LOGIC);
end XP3;
