// generated by newgenasym  Thu May 12 16:56:32 2005


module mc74vhc1gt125 (gndd, in, \oe* , out, p3v3);
    input gndd;
    input in;
    input \oe* ;
    output out;
    input p3v3;


    initial
        begin
        end

endmodule
