-- generated by newgenasym Thu May 12 16:56:32 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MC74VHC1GT125 is
    port (    
	GNDD:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P3V3:      IN     STD_LOGIC);
end MC74VHC1GT125;
