// generated by newgenasym  Wed Sep 26 10:48:02 2007


module salf78 (gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, \input , output1);
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout \input ;
    inout output1;


    initial
        begin
        end

endmodule
