// generated by newgenasym  Wed May 10 10:53:54 2017


module ltc2195 (\ain1+ , \ain1- , \ain2+ , \ain2- , \cs* , \dco+ , \dco- , \enc+ , \enc- , \fr+ ,
        \fr- , \out1a+ , \out1a- , \out1b+ , \out1b- , \out1c+ , \out1c- , \out1d+ ,
        \out1d- , \out2a+ , \out2a- , \out2b+ , \out2b- , \out2c+ , \out2c- ,
        \out2d+ , \out2d- , \par/ser , sck, sdi, sdo, sense, vcm1, vcm2,
        vref);
    inout \ain1+ ;
    inout \ain1- ;
    inout \ain2+ ;
    inout \ain2- ;
    inout \cs* ;
    inout \dco+ ;
    inout \dco- ;
    inout \enc+ ;
    inout \enc- ;
    inout \fr+ ;
    inout \fr- ;
    inout \out1a+ ;
    inout \out1a- ;
    inout \out1b+ ;
    inout \out1b- ;
    inout \out1c+ ;
    inout \out1c- ;
    inout \out1d+ ;
    inout \out1d- ;
    inout \out2a+ ;
    inout \out2a- ;
    inout \out2b+ ;
    inout \out2b- ;
    inout \out2c+ ;
    inout \out2c- ;
    inout \out2d+ ;
    inout \out2d- ;
    inout \par/ser ;
    inout sck;
    inout sdi;
    inout sdo;
    inout sense;
    inout vcm1;
    inout vcm2;
    inout vref;


    initial
        begin
        end

endmodule
