-- generated by newgenasym Wed Sep 26 10:38:21 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad9742 is
    port (    
	ACOM:      INOUT  STD_LOGIC;    
	AVDD:      INOUT  STD_LOGIC;    
	CLOCK:     INOUT  STD_LOGIC;    
	DB0:       INOUT  STD_LOGIC;    
	DB1:       INOUT  STD_LOGIC;    
	DB10:      INOUT  STD_LOGIC;    
	DB11:      INOUT  STD_LOGIC;    
	DB2:       INOUT  STD_LOGIC;    
	DB3:       INOUT  STD_LOGIC;    
	DB4:       INOUT  STD_LOGIC;    
	DB5:       INOUT  STD_LOGIC;    
	DB6:       INOUT  STD_LOGIC;    
	DB7:       INOUT  STD_LOGIC;    
	DB8:       INOUT  STD_LOGIC;    
	DB9:       INOUT  STD_LOGIC;    
	DCOM:      INOUT  STD_LOGIC;    
	DVDD:      INOUT  STD_LOGIC;    
	FSADJ:     INOUT  STD_LOGIC;    
	IOUTA:     INOUT  STD_LOGIC;    
	IOUTB:     INOUT  STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	REFIO:     INOUT  STD_LOGIC;    
	REFLO:     INOUT  STD_LOGIC;    
	RES:       INOUT  STD_LOGIC;    
	SLEEP:     INOUT  STD_LOGIC);
end ad9742;
