-- generated by newgenasym Mon Dec 08 16:31:17 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cd74ac20m is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	A6:        IN     STD_LOGIC;    
	A7:        IN     STD_LOGIC;    
	A8:        IN     STD_LOGIC;    
	\b1*\:     OUT    STD_LOGIC;    
	\b2*\:     OUT    STD_LOGIC);
end cd74ac20m;
