// generated by newgenasym  Thu Apr 27 18:04:33 2017


module n25q256mb (c, dq0, dq1, dq2, dq3, reset, \s# );
    inout c;
    inout dq0;
    inout dq1;
    inout dq2;
    inout dq3;
    inout reset;
    inout \s# ;


    initial
        begin
        end

endmodule
