// generated by newgenasym  Thu Jul 29 17:59:29 2004


module ad8361 (comm, fltr, iref, pwdn, rfin, sref, vpos, vrms);
    input comm;
    output fltr;
    output iref;
    input pwdn;
    input rfin;
    input sref;
    input vpos;
    output vrms;


    initial
        begin
        end

endmodule
