-- generated by newgenasym Thu Jul 29 17:59:29 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8361 is
    port (    
	COMM:      IN     STD_LOGIC;    
	FLTR:      OUT    STD_LOGIC;    
	IREF:      OUT    STD_LOGIC;    
	PWDN:      IN     STD_LOGIC;    
	RFIN:      IN     STD_LOGIC;    
	SREF:      IN     STD_LOGIC;    
	VPOS:      IN     STD_LOGIC;    
	VRMS:      OUT    STD_LOGIC);
end ad8361;
