-- generated by newgenasym Wed Aug 26 14:42:23 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cat4101 is
    port (    
	LED:       INOUT  STD_LOGIC;    
	PWM:       INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end cat4101;
