// generated by newgenasym  Fri Oct 27 12:49:42 2017


module adf4110 (ce, clk, cp, data, le, muxout, refin, rfina, rfinb, rset);
    inout ce;
    inout clk;
    inout cp;
    inout data;
    inout le;
    inout muxout;
    inout refin;
    inout rfina;
    inout rfinb;
    inout rset;


    initial
        begin
        end

endmodule
