-- generated by newgenasym Fri Oct 27 12:49:42 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adf4110 is
    port (    
	CE:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CP:        INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	MUXOUT:    INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	RFINA:     INOUT  STD_LOGIC;    
	RFINB:     INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC);
end adf4110;
