-- generated by newgenasym Mon Jul 10 19:06:05 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \si-70002\ is
    port (    
	CHASSIS:   INOUT  STD_LOGIC;    
	\d1+\:     INOUT  STD_LOGIC;    
	\d1-\:     INOUT  STD_LOGIC;    
	\d2+\:     INOUT  STD_LOGIC;    
	\d2-\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	LED1A:     INOUT  STD_LOGIC;    
	LED1C:     INOUT  STD_LOGIC;    
	LED2A:     INOUT  STD_LOGIC;    
	LED2C:     INOUT  STD_LOGIC;    
	PWR1:      INOUT  STD_LOGIC;    
	PWR2:      INOUT  STD_LOGIC;    
	RCT:       INOUT  STD_LOGIC;    
	\rd+\:     INOUT  STD_LOGIC;    
	\rd-\:     INOUT  STD_LOGIC;    
	TCT:       INOUT  STD_LOGIC;    
	\td+\:     INOUT  STD_LOGIC;    
	\td-\:     INOUT  STD_LOGIC);
end \si-70002\;
