// generated by newgenasym  Thu Dec 23 09:13:32 2004


module cfpt_125 (gnd, out, vc, vcc);
    input gnd;
    output out;
    input vc;
    input vcc;


    initial
        begin
        end

endmodule
