-- generated by newgenasym Thu Dec 23 09:13:32 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cfpt_125 is
    port (    
	GND:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VC:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end cfpt_125;
