// generated by newgenasym  Tue Aug 22 14:56:06 2017


module sn65lvdt390 (\1a , \1b , \1y , \2a , \2b , \2y , \3a , \3b , \3y , \4a , \4b , \4y , en1_2, en3_4);
    inout \1a ;
    inout \1b ;
    inout \1y ;
    inout \2a ;
    inout \2b ;
    inout \2y ;
    inout \3a ;
    inout \3b ;
    inout \3y ;
    inout \4a ;
    inout \4b ;
    inout \4y ;
    inout en1_2;
    inout en3_4;


    initial
        begin
        end

endmodule
