-- generated by newgenasym Fri Jun 03 17:50:28 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad9854 is
    port (    
	\a0/sdio\: INOUT  STD_LOGIC;    
	\a1/sdo\:  INOUT  STD_LOGIC;    
	\a2/io_reset\: IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        IN     STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	D6:        INOUT  STD_LOGIC;    
	D7:        INOUT  STD_LOGIC;    
	DAC_RSET:  INOUT  STD_LOGIC;    
	DACBP:     INOUT  STD_LOGIC;    
	DIFF_CLK_EN: INOUT  STD_LOGIC;    
	\fsk/bpsk/hold\: IN     STD_LOGIC;    
	\i/o_ud_clk\: INOUT  STD_LOGIC;    
	M_RESET:   INOUT  STD_LOGIC;    
	OSK:       IN     STD_LOGIC;    
	OUT_IN:    INOUT  STD_LOGIC;    
	OUT_IP:    INOUT  STD_LOGIC;    
	OUT_QN:    INOUT  STD_LOGIC;    
	OUT_QP:    INOUT  STD_LOGIC;    
	PLL_FILTER: INOUT  STD_LOGIC;    
	\rd/cs\:   IN     STD_LOGIC;    
	\ref_clk*\: INOUT  STD_LOGIC;    
	REF_CLK_P: INOUT  STD_LOGIC;    
	\s/p select\: INOUT  STD_LOGIC;    
	VINN:      IN     STD_LOGIC;    
	VINP:      IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC;    
	\wr/sclk\: IN     STD_LOGIC);
end ad9854;
