// generated by newgenasym  Thu Feb 15 15:53:26 2018


module smd_spst (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
