// generated by newgenasym  Sun Aug 01 18:38:55 2004


module cpci_peripheral_j2 (\64en* , ad, brsvp2a15, brsvp2a16, brsvp2a17, brsvp2a18,
        brsvp2b16, brsvp2b18, brsvp2b4, brsvp2c18, brsvp2e16,
        brsvp2e18, \c_be4* , \c_be5* , \c_be6* , \c_be7* , ga, gnd, par64,
        rsv, \smbalert* , \unc_sysen* , vio);
    output \64en* ;
    inout [63:32] ad;
    output brsvp2a15;
    output brsvp2a16;
    output brsvp2a17;
    output brsvp2a18;
    output brsvp2b16;
    output brsvp2b18;
    output brsvp2b4;
    output brsvp2c18;
    output brsvp2e16;
    output brsvp2e18;
    inout \c_be4* ;
    inout \c_be5* ;
    inout \c_be6* ;
    inout \c_be7* ;
    output [4:0] ga;
    input [38:0] gnd;
    inout par64;
    inout [31:0] rsv;
    input \smbalert* ;
    output \unc_sysen* ;
    input [5:0] vio;


    initial
        begin
        end

endmodule
