// generated by newgenasym  Thu Apr 10 11:03:39 2003


module epm7128 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \23 , \24 , \25 , \26 , \27 ,
        \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \38 , \39 , \4 , \40 , \41 , \42 , \43 , \44 ,
        \46 , \47 , \48 , \49 , \5 , \50 , \51 , \52 , \53 , \54 , \55 , \56 , \59 , \6 , \60 , \61 , \62 , \63 ,
        \64 , \65 , \66 , \7 , \71 , \72 , \78 , \8 , \82 , \83 , \84 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    output \12 ;
    input \13 ;
    output \14 ;
    input \15 ;
    input \16 ;
    input \17 ;
    input \18 ;
    output \19 ;
    output \2 ;
    input \20 ;
    output \23 ;
    output \24 ;
    output \25 ;
    input \26 ;
    output \27 ;
    output \28 ;
    output \29 ;
    input \3 ;
    output \30 ;
    input \31 ;
    output \32 ;
    output \33 ;
    output \34 ;
    input \35 ;
    output \36 ;
    input \38 ;
    output \39 ;
    input \4 ;
    input \40 ;
    output \41 ;
    output \42 ;
    input \43 ;
    output \44 ;
    input \46 ;
    output \47 ;
    output \48 ;
    input \49 ;
    input \5 ;
    output \50 ;
    input \51 ;
    input \52 ;
    input \53 ;
    input \54 ;
    input \55 ;
    input \56 ;
    output \59 ;
    input \6 ;
    input \60 ;
    input \61 ;
    output \62 ;
    input \63 ;
    input \64 ;
    input \65 ;
    input \66 ;
    output \7 ;
    output \71 ;
    output \72 ;
    input \78 ;
    input \8 ;
    output \82 ;
    input \83 ;
    input \84 ;
    input \9 ;


    initial
        begin
        end

endmodule
