// generated by newgenasym  Thu May 12 15:17:20 2005


module iru1207_33cs (enable, flag, gnd1, gnd2, gnd3, gnd4, vin, vout);
    input enable;
    output flag;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input vin;
    output vout;


    initial
        begin
        end

endmodule
