// generated by newgenasym  Mon Oct 13 18:42:20 2014


module ft2232h (acbus0, acbus1, acbus2, acbus3, acbus4, acbus5, acbus6,
        acbus7, adbus0, adbus1, adbus2, adbus3, adbus4, adbus5,
        adbus6, adbus7, bcbus0, bcbus1, bcbus2, bcbus3, bcbus4,
        bcbus5, bcbus6, bcbus7, bdbus0, bdbus1, bdbus2, bdbus3,
        bdbus4, bdbus5, bdbus6, bdbus7, dm, dp, eeclk, eecs, eedata,
        osci, osco, \pwren# , ref, \reset# , \suspend# , test, vregin,
        vregout);
    inout acbus0;
    inout acbus1;
    inout acbus2;
    inout acbus3;
    inout acbus4;
    inout acbus5;
    inout acbus6;
    inout acbus7;
    inout adbus0;
    inout adbus1;
    inout adbus2;
    inout adbus3;
    inout adbus4;
    inout adbus5;
    inout adbus6;
    inout adbus7;
    inout bcbus0;
    inout bcbus1;
    inout bcbus2;
    inout bcbus3;
    inout bcbus4;
    inout bcbus5;
    inout bcbus6;
    inout bcbus7;
    inout bdbus0;
    inout bdbus1;
    inout bdbus2;
    inout bdbus3;
    inout bdbus4;
    inout bdbus5;
    inout bdbus6;
    inout bdbus7;
    inout dm;
    inout dp;
    inout eeclk;
    inout eecs;
    inout eedata;
    inout osci;
    inout osco;
    inout \pwren# ;
    inout ref;
    inout \reset# ;
    inout \suspend# ;
    inout test;
    inout vregin;
    inout vregout;


    initial
        begin
        end

endmodule
