// generated by newgenasym  Mon Nov 16 17:42:09 2009


module \ltc1064-2  (\50/100 , fclk, out_c, rina, \v+ , \v- , vin, vout);
    inout \50/100 ;
    inout fclk;
    inout out_c;
    inout rina;
    inout \v+ ;
    inout \v- ;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
