-- generated by newgenasym Mon Nov 16 17:42:09 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ltc1064-2\ is
    port (    
	\50/100\:  INOUT  STD_LOGIC;    
	FCLK:      INOUT  STD_LOGIC;    
	OUT_C:     INOUT  STD_LOGIC;    
	RINA:      INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end \ltc1064-2\;
