-- generated by newgenasym Wed Sep 26 11:46:06 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5372 is
    port (    
	COM1:      IN     STD_LOGIC;    
	COM2:      IN     STD_LOGIC;    
	COM3:      IN     STD_LOGIC;    
	COM4:      IN     STD_LOGIC;    
	COM5:      IN     STD_LOGIC;    
	COM6:      IN     STD_LOGIC;    
	COM7:      IN     STD_LOGIC;    
	COM8:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IBBN:      INOUT  STD_LOGIC;    
	IBBP:      INOUT  STD_LOGIC;    
	LOIN:      INOUT  STD_LOGIC;    
	LOIP:      INOUT  STD_LOGIC;    
	QBBN:      INOUT  STD_LOGIC;    
	QBBP:      INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VPS1:      IN     STD_LOGIC;    
	VPS2:      IN     STD_LOGIC;    
	VPS3:      IN     STD_LOGIC;    
	VPS4:      IN     STD_LOGIC;    
	VPS5:      IN     STD_LOGIC;    
	VPS6:      IN     STD_LOGIC;    
	VPS7:      IN     STD_LOGIC;    
	VPS8:      IN     STD_LOGIC;    
	VPS9:      IN     STD_LOGIC);
end adl5372;
