-- generated by newgenasym Fri Jul 19 11:59:45 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bl_l519 is
    port (    
	ANOD1:     INOUT  STD_LOGIC;    
	ANOD2:     INOUT  STD_LOGIC;    
	CATOD:     INOUT  STD_LOGIC);
end bl_l519;
