// generated by newgenasym  Fri Jun 08 18:00:39 2007


module \rps-2-30  (gnd1, gnd2, gnd3, port1, port2, sum);
    input gnd1;
    input gnd2;
    input gnd3;
    inout port1;
    inout port2;
    inout sum;


    initial
        begin
        end

endmodule
