-- generated by newgenasym Fri Jun 08 18:00:39 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \rps-2-30\ is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	PORT1:     INOUT  STD_LOGIC;    
	PORT2:     INOUT  STD_LOGIC;    
	SUM:       INOUT  STD_LOGIC);
end \rps-2-30\;
