// generated by newgenasym  Thu Aug 24 14:44:05 2017


module sn65lvds180 (a, b, d, de, r, \re* , y, z);
    inout a;
    inout b;
    inout d;
    inout de;
    inout r;
    inout \re* ;
    inout y;
    inout z;


    initial
        begin
        end

endmodule
