-- generated by newgenasym Wed Oct 06 12:42:48 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mw_2mr is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end mw_2mr;
