-- generated by newgenasym Fri Sep 08 12:06:02 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm1032 is
    port (    
	ALERT:     INOUT  STD_LOGIC;    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	SDATA:     INOUT  STD_LOGIC;    
	THERM:     INOUT  STD_LOGIC);
end adm1032;
