-- generated by newgenasym Thu Jul 12 15:50:24 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX810 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\reset*\:  INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end MAX810;
