// generated by newgenasym  Tue Nov 17 14:32:23 2009


module opa1632 (\+vin , \-vin , enb, \v+ , \v- , vocm, \vout+ , \vout- );
    inout \+vin ;
    inout \-vin ;
    inout enb;
    inout \v+ ;
    inout \v- ;
    inout vocm;
    inout \vout+ ;
    inout \vout- ;


    initial
        begin
        end

endmodule
