-- generated by newgenasym Tue Jul 11 15:50:52 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tc1-1tx\ is
    port (    
	PRI:       INOUT  STD_LOGIC;    
	PRI_D:     INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_CT:    INOUT  STD_LOGIC;    
	SEC_D:     INOUT  STD_LOGIC);
end \tc1-1tx\;
