// generated by newgenasym  Fri Dec 23 15:18:07 2011


module ten5 (\+vin1 , \+vin2 , \+vout , \-vin1 , \-vin2 , \-vout );
    inout \+vin1 ;
    inout \+vin2 ;
    inout \+vout ;
    inout \-vin1 ;
    inout \-vin2 ;
    inout \-vout ;


    initial
        begin
        end

endmodule
