// generated by newgenasym  Mon Feb 06 16:24:37 2006


module ad8309 (com1, com2, enbl, fltr, inhi, inlo, lmdr, lmhi, lmlo, padl,
        padl11, padl14, padl6, vlog, vps1, vps2);
    inout com1;
    inout com2;
    inout enbl;
    inout fltr;
    inout inhi;
    inout inlo;
    inout lmdr;
    inout lmhi;
    inout lmlo;
    input padl;
    input padl11;
    input padl14;
    input padl6;
    inout vlog;
    inout vps1;
    inout vps2;


    initial
        begin
        end

endmodule
