-- generated by newgenasym Mon Feb 06 16:24:37 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8309 is
    port (    
	COM1:      INOUT  STD_LOGIC;    
	COM2:      INOUT  STD_LOGIC;    
	ENBL:      INOUT  STD_LOGIC;    
	FLTR:      INOUT  STD_LOGIC;    
	INHI:      INOUT  STD_LOGIC;    
	INLO:      INOUT  STD_LOGIC;    
	LMDR:      INOUT  STD_LOGIC;    
	LMHI:      INOUT  STD_LOGIC;    
	LMLO:      INOUT  STD_LOGIC;    
	PADL:      IN     STD_LOGIC;    
	PADL11:    IN     STD_LOGIC;    
	PADL14:    IN     STD_LOGIC;    
	PADL6:     IN     STD_LOGIC;    
	VLOG:      INOUT  STD_LOGIC;    
	VPS1:      INOUT  STD_LOGIC;    
	VPS2:      INOUT  STD_LOGIC);
end ad8309;
