// generated by newgenasym  Thu Dec 08 11:21:28 2011


module adl5501 (comm, enbl, fltr, rfin, vpos, vrms);
    inout comm;
    inout enbl;
    inout fltr;
    inout rfin;
    inout vpos;
    inout vrms;


    initial
        begin
        end

endmodule
