-- generated by newgenasym Thu Dec 08 11:21:28 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADL5501 is
    port (    
	COMM:      INOUT  STD_LOGIC;    
	ENBL:      INOUT  STD_LOGIC;    
	FLTR:      INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	VPOS:      INOUT  STD_LOGIC;    
	VRMS:      INOUT  STD_LOGIC);
end ADL5501;
