-- generated by newgenasym Thu Mar 27 14:39:32 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bss138 is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end bss138;
