// generated by newgenasym  Wed Jun 30 16:31:44 2004


module pvdz (anode, cathode, drain, source);
    input anode;
    input cathode;
    output drain;
    output source;


    initial
        begin
        end

endmodule
