-- generated by newgenasym Thu Mar 10 15:39:37 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jtag is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (6 DOWNTO 0);    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC);
end jtag;
