// generated by newgenasym  Fri Aug 01 16:06:21 2003


module cpci_j1 (\ack64* , ad0, ad1, ad10, ad11, ad12, ad13, ad14, ad15, ad16,
        ad17, ad18, ad19, ad2, ad20, ad21, ad22, ad23, ad24, ad25, ad26,
        ad27, ad28, ad29, ad3, ad30, ad31, ad4, ad5, ad6, ad7, ad8, ad9,
        \c/be0* , \c/be1* , \c/be2* , \c/be3* , clk, cndd1, \devsel* , \enum* ,
        ersvp1a5, \frame* , gndd10, gndd11, gndd12, gndd13, gndd14,
        gndd15, gndd16, gndd17, gndd18, gndd19, gndd2, gndd20,
        gndd21, gndd22, gndd23, gndd24, gndd25, gndd26, gndd27,
        gndd28, gndd29, gndd3, gndd4, gndd5, gndd6, gndd7, gndd8,
        gndd9, gndl1, gndl2, gndl3, gndl4, gndl5, gndl6, \gnt* ,
        \healthy* , idsels, \inta* , \intb* , \intc* , \intd* , intp, ints,
        \irdy* , \lock* , m66en, n12v0, p12v0, p3v3_1, p3v3_2, p3v3_3,
        p3v3_4, p3v3_5, p3v3_6, p3v3_7, p3v3_8, p3v3l1, p3v3l2,
        p5v0_1, p5v0_2, p5v0_3, p5v0_4, p5v0_5, p5v0_6, p5v0l1,
        p5v0l2, par, \pci_rst* , \perr* , \reo64* , \req* , \sbo* , \sd_sels* ,
        sdone, \serr* , srsvp1a4, srsvp1b5, \stop* , tck, tdi, tdo, tms,
        \troy* , \trst* , vio1, vio2, vio3, viol1, viol2);
    output \ack64* ;
    input ad0;
    input ad1;
    input ad10;
    input ad11;
    input ad12;
    input ad13;
    input ad14;
    input ad15;
    input ad16;
    input ad17;
    input ad18;
    input ad19;
    input ad2;
    input ad20;
    input ad21;
    input ad22;
    input ad23;
    input ad24;
    input ad25;
    input ad26;
    input ad27;
    input ad28;
    input ad29;
    input ad3;
    input ad30;
    input ad31;
    input ad4;
    input ad5;
    input ad6;
    input ad7;
    input ad8;
    input ad9;
    input \c/be0* ;
    input \c/be1* ;
    input \c/be2* ;
    input \c/be3* ;
    input clk;
    input cndd1;
    input \devsel* ;
    input \enum* ;
    output ersvp1a5;
    input \frame* ;
    input gndd10;
    input gndd11;
    input gndd12;
    input gndd13;
    input gndd14;
    input gndd15;
    input gndd16;
    input gndd17;
    input gndd18;
    input gndd19;
    input gndd2;
    input gndd20;
    input gndd21;
    input gndd22;
    input gndd23;
    input gndd24;
    input gndd25;
    input gndd26;
    input gndd27;
    input gndd28;
    input gndd29;
    input gndd3;
    input gndd4;
    input gndd5;
    input gndd6;
    input gndd7;
    input gndd8;
    input gndd9;
    input gndl1;
    input gndl2;
    input gndl3;
    input gndl4;
    input gndl5;
    input gndl6;
    input \gnt* ;
    input \healthy* ;
    input idsels;
    input \inta* ;
    input \intb* ;
    input \intc* ;
    input \intd* ;
    output intp;
    output ints;
    input \irdy* ;
    input \lock* ;
    output m66en;
    input n12v0;
    input p12v0;
    input p3v3_1;
    input p3v3_2;
    input p3v3_3;
    input p3v3_4;
    input p3v3_5;
    input p3v3_6;
    input p3v3_7;
    input p3v3_8;
    input p3v3l1;
    input p3v3l2;
    input p5v0_1;
    input p5v0_2;
    input p5v0_3;
    input p5v0_4;
    input p5v0_5;
    input p5v0_6;
    input p5v0l1;
    input p5v0l2;
    input par;
    input \pci_rst* ;
    input \perr* ;
    output \reo64* ;
    input \req* ;
    output \sbo* ;
    input \sd_sels* ;
    output sdone;
    input \serr* ;
    output srsvp1a4;
    output srsvp1b5;
    input \stop* ;
    output tck;
    output tdi;
    output tdo;
    output tms;
    input \troy* ;
    output \trst* ;
    input vio1;
    input vio2;
    input vio3;
    input viol1;
    input viol2;


    initial
        begin
        end

endmodule
