-- generated by newgenasym Tue Sep 30 20:36:04 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dip_isp is
    port (    
	OUT_V:     INOUT  STD_LOGIC;    
	PGN:       INOUT  STD_LOGIC;    
	VKL:       INOUT  STD_LOGIC);
end dip_isp;
