-- generated by newgenasym Wed Jul 21 16:14:55 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g04 is
    port (    
	\1a\:      IN     STD_LOGIC;    
	\1y*\:     OUT    STD_LOGIC;    
	\2a\:      IN     STD_LOGIC;    
	\2y*\:     OUT    STD_LOGIC;    
	GNDD:      IN     STD_LOGIC;    
	P5V0:      IN     STD_LOGIC);
end sn74lvc2g04;
