// generated by newgenasym  Thu Aug 16 13:04:44 2018


module tc2_1t (pri, \pri#20dot , sec, \sec#20ct , \sec#20dot );
    inout pri;
    inout \pri#20dot ;
    inout sec;
    inout \sec#20ct ;
    inout \sec#20dot ;


    initial
        begin
        end

endmodule
