// generated by newgenasym  Mon Aug 30 20:13:00 2004


module max9124 (din1, din2, din3, din4, dout1, \dout1* , dout2, \dout2* , dout3,
        \dout3* , dout4, \dout4* , en, \en* );
    input din1;
    input din2;
    input din3;
    input din4;
    output dout1;
    output \dout1* ;
    output dout2;
    output \dout2* ;
    output dout3;
    output \dout3* ;
    output dout4;
    output \dout4* ;
    input en;
    input \en* ;


    initial
        begin
        end

endmodule
