-- generated by newgenasym Mon Aug 30 20:13:00 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9124 is
    port (    
	DIN1:      IN     STD_LOGIC;    
	DIN2:      IN     STD_LOGIC;    
	DIN3:      IN     STD_LOGIC;    
	DIN4:      IN     STD_LOGIC;    
	DOUT1:     OUT    STD_LOGIC;    
	\dout1*\:  OUT    STD_LOGIC;    
	DOUT2:     OUT    STD_LOGIC;    
	\dout2*\:  OUT    STD_LOGIC;    
	DOUT3:     OUT    STD_LOGIC;    
	\dout3*\:  OUT    STD_LOGIC;    
	DOUT4:     OUT    STD_LOGIC;    
	\dout4*\:  OUT    STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC);
end max9124;
