-- generated by newgenasym Tue Nov 16 11:20:56 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max1283beue is
    port (    
	CH0:       IN     STD_LOGIC;    
	CH1:       IN     STD_LOGIC;    
	CH2:       IN     STD_LOGIC;    
	CH3:       IN     STD_LOGIC;    
	COM:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	REF:       IN     STD_LOGIC;    
	REFADJ:    IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC;    
	SSTRB:     OUT    STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC);
end max1283beue;
