-- generated by newgenasym Thu Mar 02 17:40:21 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ssq_fuse is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end ssq_fuse;
