-- generated by newgenasym Wed Oct 31 17:49:21 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4599 is
    port (    
	COM:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	O1:        INOUT  STD_LOGIC;    
	O2:        INOUT  STD_LOGIC);
end max4599;
