-- generated by newgenasym Fri Nov 10 17:28:44 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc744lc3 is
    port (    
	D1N:       OUT    STD_LOGIC;    
	D1P:       OUT    STD_LOGIC;    
	D2N:       OUT    STD_LOGIC;    
	D2P:       OUT    STD_LOGIC;    
	DINN:      IN     STD_LOGIC;    
	DINP:      IN     STD_LOGIC;    
	VR:        INOUT  STD_LOGIC);
end hmc744lc3;
