-- generated by newgenasym Wed Jan 11 15:21:54 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \drb-25\ is
    port (    
	IN1:       INOUT  STD_LOGIC;    
	IN10:      INOUT  STD_LOGIC;    
	IN11:      INOUT  STD_LOGIC;    
	IN12:      INOUT  STD_LOGIC;    
	IN13:      INOUT  STD_LOGIC;    
	IN14:      INOUT  STD_LOGIC;    
	IN15:      INOUT  STD_LOGIC;    
	IN16:      INOUT  STD_LOGIC;    
	IN17:      INOUT  STD_LOGIC;    
	IN18:      INOUT  STD_LOGIC;    
	IN19:      INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN20:      INOUT  STD_LOGIC;    
	IN21:      INOUT  STD_LOGIC;    
	IN22:      INOUT  STD_LOGIC;    
	IN23:      INOUT  STD_LOGIC;    
	IN24:      INOUT  STD_LOGIC;    
	IN25:      INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	IN4:       INOUT  STD_LOGIC;    
	IN5:       INOUT  STD_LOGIC;    
	IN6:       INOUT  STD_LOGIC;    
	IN7:       INOUT  STD_LOGIC;    
	IN8:       INOUT  STD_LOGIC;    
	IN9:       INOUT  STD_LOGIC);
end \drb-25\;
