// generated by newgenasym  Fri Dec 24 15:52:17 2004


module bga2771 (gnd, gnd1, gnd2, rfin, rfout, vs);
    input gnd;
    input gnd1;
    input gnd2;
    input rfin;
    output rfout;
    input vs;


    initial
        begin
        end

endmodule
