// generated by newgenasym  Thu May 25 11:39:15 2017


module usb_a (gnd, usb_dn, usb_dp, vcc);
    inout gnd;
    inout usb_dn;
    inout usb_dp;
    inout vcc;


    initial
        begin
        end

endmodule
