-- generated by newgenasym Thu May 25 11:39:15 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity usb_a is
    port (    
	GND:       INOUT  STD_LOGIC;    
	USB_DN:    INOUT  STD_LOGIC;    
	USB_DP:    INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end usb_a;
