// generated by newgenasym  Tue Aug 22 17:17:26 2017


module lmk04828 (clkin0, \clkin0* , clkin1, \clkin1* , clkin_sel0, clkin_sel1,
        cpout1, cpout2, \cs* , dclkout0, \dclkout0* , dclkout10,
        \dclkout10* , dclkout12, \dclkout12* , dclkout2, \dclkout2* ,
        dclkout4, \dclkout4* , dclkout6, \dclkout6* , dclkout8,
        \dclkout8* , ldobyp1, ldobyp2, oscin, \oscin* , oscout, \oscout* ,
        reset, sck, sdclkout1, \sdclkout1* , sdclkout11, \sdclkout11* ,
        sdclkout13, \sdclkout13* , sdclkout3, \sdclkout3* , sdclkout5,
        \sdclkout5* , sdclkout7, \sdclkout7* , sdclkout9, \sdclkout9* ,
        sdio, status_ld1, status_ld2, \sync/sysref_req );
    inout clkin0;
    inout \clkin0* ;
    inout clkin1;
    inout \clkin1* ;
    inout clkin_sel0;
    inout clkin_sel1;
    inout cpout1;
    inout cpout2;
    inout \cs* ;
    inout dclkout0;
    inout \dclkout0* ;
    inout dclkout10;
    inout \dclkout10* ;
    inout dclkout12;
    inout \dclkout12* ;
    inout dclkout2;
    inout \dclkout2* ;
    inout dclkout4;
    inout \dclkout4* ;
    inout dclkout6;
    inout \dclkout6* ;
    inout dclkout8;
    inout \dclkout8* ;
    inout ldobyp1;
    inout ldobyp2;
    inout oscin;
    inout \oscin* ;
    inout oscout;
    inout \oscout* ;
    inout reset;
    inout sck;
    inout sdclkout1;
    inout \sdclkout1* ;
    inout sdclkout11;
    inout \sdclkout11* ;
    inout sdclkout13;
    inout \sdclkout13* ;
    inout sdclkout3;
    inout \sdclkout3* ;
    inout sdclkout5;
    inout \sdclkout5* ;
    inout sdclkout7;
    inout \sdclkout7* ;
    inout sdclkout9;
    inout \sdclkout9* ;
    inout sdio;
    inout status_ld1;
    inout status_ld2;
    inout \sync/sysref_req ;


    initial
        begin
        end

endmodule
