-- generated by newgenasym Tue Jun 29 10:33:00 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max5382l is
    port (    
	\out\:     OUT    STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end max5382l;
