-- generated by newgenasym Wed Oct 31 12:11:58 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pmeg2010aeb is
    port (    
	A:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end pmeg2010aeb;
