// generated by newgenasym  Mon Nov 08 13:35:07 2010


module \pbd-28  (in1, in10, in11, in12, in13, in14, in15, in16, in17, in18,
        in19, in2, in20, in21, in22, in23, in24, in25, in26, in27, in28,
        in3, in4, in5, in6, in7, in8, in9);
    inout in1;
    inout in10;
    inout in11;
    inout in12;
    inout in13;
    inout in14;
    inout in15;
    inout in16;
    inout in17;
    inout in18;
    inout in19;
    inout in2;
    inout in20;
    inout in21;
    inout in22;
    inout in23;
    inout in24;
    inout in25;
    inout in26;
    inout in27;
    inout in28;
    inout in3;
    inout in4;
    inout in5;
    inout in6;
    inout in7;
    inout in8;
    inout in9;


    initial
        begin
        end

endmodule
