// generated by newgenasym  Tue Dec 15 11:40:36 2009


module at25256a (\cs# , gnd, \hold# , sck, si, so, vcc, \wp# );
    inout \cs# ;
    inout gnd;
    inout \hold# ;
    inout sck;
    inout si;
    inout so;
    inout vcc;
    inout \wp# ;


    initial
        begin
        end

endmodule
