// generated by newgenasym  Tue Feb 07 17:32:10 2006


module \ltc1563-2  (agnd, \en- , inva, invb, \lp- , lpa, lpb, nc1, nc2, nc3, nc4, nc6,
        \sa- , sb, \v+ , \v- );
    inout agnd;
    inout \en- ;
    inout inva;
    inout invb;
    inout \lp- ;
    inout lpa;
    inout lpb;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc6;
    inout \sa- ;
    inout sb;
    inout \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
