// generated by newgenasym  Fri Jul 04 11:37:48 2003


module lm2904dp (a, \a* , a_out, b, \b* , b_out, n3v3_a, p3v3_a);
    input a;
    input \a* ;
    output a_out;
    input b;
    input \b* ;
    output b_out;
    input n3v3_a;
    input p3v3_a;


    initial
        begin
        end

endmodule
