-- generated by newgenasym Tue Mar 09 17:45:38 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds2402 is
    port (    
	DATA:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC);
end ds2402;
