-- generated by newgenasym Mon Jun 04 15:08:45 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mv103 is
    port (    
	GND:       IN     STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end mv103;
