-- generated by newgenasym Wed Aug 13 15:25:13 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \6405ps1\ is
    port (    
	\+if\:     INOUT  STD_LOGIC;    
	\-if\:     INOUT  STD_LOGIC;    
	LO:        INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC);
end \6405ps1\;
