// generated by newgenasym  Fri Dec 24 15:49:56 2004


module op184es (in_a, \in_a* , \n.c. , null1, null2, out_a, \v+ , \v- );
    input in_a;
    input \in_a* ;
    inout \n.c. ;
    input null1;
    input null2;
    output out_a;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
