-- generated by newgenasym Fri Dec 24 15:49:56 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity op184es is
    port (    
	IN_A:      IN     STD_LOGIC;    
	\in_a*\:   IN     STD_LOGIC;    
	\n.c.\:    INOUT  STD_LOGIC;    
	NULL1:     IN     STD_LOGIC;    
	NULL2:     IN     STD_LOGIC;    
	OUT_A:     OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end op184es;
