// generated by newgenasym  Fri Jul 16 12:51:19 2004


module ad8361arm (comm, fltr, iref, pwdn, rfin, sref, vpos, vrms);
    input comm;
    output fltr;
    output iref;
    input pwdn;
    input rfin;
    input sref;
    input vpos;
    output vrms;


    initial
        begin
        end

endmodule
