-- generated by newgenasym Tue Jan 06 13:13:24 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity L is
    port (    
	A:         IN     STD_LOGIC;    
	B:         OUT    STD_LOGIC);
end L;
