-- generated by newgenasym Thu Sep 10 18:06:17 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity b130 is
    port (    
	A:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end b130;
