-- generated by newgenasym Tue Jul 25 15:35:36 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tcp_2_10 is
    port (    
	PORT1:     INOUT  STD_LOGIC;    
	PORT2:     INOUT  STD_LOGIC;    
	SHORT1:    INOUT  STD_LOGIC;    
	SHORT2:    INOUT  STD_LOGIC;    
	\sum port\: INOUT  STD_LOGIC);
end tcp_2_10;
