// generated by newgenasym  Wed May 16 17:45:07 2007


module adp3300 (err, gnd, in, nr, out, sd);
    inout err;
    input gnd;
    inout in;
    inout nr;
    inout out;
    inout sd;


    initial
        begin
        end

endmodule
