-- generated by newgenasym Wed Jul 25 10:16:47 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm2486 is
    port (    
	\-b\:      INOUT  STD_LOGIC;    
	\-re\:     INOUT  STD_LOGIC;    
	A:         INOUT  STD_LOGIC;    
	DE:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND11:     INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND21:     INOUT  STD_LOGIC;    
	PV:        INOUT  STD_LOGIC;    
	RTS:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VDD1:      INOUT  STD_LOGIC;    
	VDD2:      INOUT  STD_LOGIC);
end adm2486;
