// generated by newgenasym  Mon Dec 12 17:53:38 2011


module adcmp572 (hys, le_n, le_p, q_n, q_p, vn, vp, vtn, vtp);
    inout hys;
    inout le_n;
    inout le_p;
    inout q_n;
    inout q_p;
    inout vn;
    inout vp;
    inout vtn;
    inout vtp;


    initial
        begin
        end

endmodule
