-- generated by newgenasym Mon Dec 12 17:53:38 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adcmp572 is
    port (    
	HYS:       INOUT  STD_LOGIC;    
	LE_N:      INOUT  STD_LOGIC;    
	LE_P:      INOUT  STD_LOGIC;    
	Q_N:       INOUT  STD_LOGIC;    
	Q_P:       INOUT  STD_LOGIC;    
	VN:        INOUT  STD_LOGIC;    
	VP:        INOUT  STD_LOGIC;    
	VTN:       INOUT  STD_LOGIC;    
	VTP:       INOUT  STD_LOGIC);
end adcmp572;
