// generated by newgenasym  Mon Mar 24 17:46:55 2008


module at113 (rfin, rfout, vc, vcc);
    inout rfin;
    inout rfout;
    inout vc;
    inout vcc;


    initial
        begin
        end

endmodule
