-- generated by newgenasym Mon Mar 24 17:46:55 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity at113 is
    port (    
	RFIN:      INOUT  STD_LOGIC;    
	RFOUT:     INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end at113;
