// generated by newgenasym  Wed May 03 11:47:19 2017


module onet4251pa (coc1, coc2, \din+ , \din- , \disable , \dout+ , \dout- , los, outpol,
        rssi, th);
    inout coc1;
    inout coc2;
    inout \din+ ;
    inout \din- ;
    inout \disable ;
    inout \dout+ ;
    inout \dout- ;
    inout los;
    inout outpol;
    inout rssi;
    inout th;


    initial
        begin
        end

endmodule
