-- generated by newgenasym Wed May 03 11:47:19 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity onet4251pa is
    port (    
	COC1:      INOUT  STD_LOGIC;    
	COC2:      INOUT  STD_LOGIC;    
	\din+\:    INOUT  STD_LOGIC;    
	\din-\:    INOUT  STD_LOGIC;    
	DISABLE:   INOUT  STD_LOGIC;    
	\dout+\:   INOUT  STD_LOGIC;    
	\dout-\:   INOUT  STD_LOGIC;    
	LOS:       INOUT  STD_LOGIC;    
	OUTPOL:    INOUT  STD_LOGIC;    
	RSSI:      INOUT  STD_LOGIC;    
	TH:        INOUT  STD_LOGIC);
end onet4251pa;
