// generated by newgenasym  Tue Jul 06 12:31:50 2004


module gk54_tc (in1, in2, in3, in4, out);
    input in1;
    input in2;
    input in3;
    input in4;
    output out;


    initial
        begin
        end

endmodule
