-- generated by newgenasym Tue Jul 06 12:31:50 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gk54_tc is
    port (    
	IN1:       IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	IN3:       IN     STD_LOGIC;    
	IN4:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end gk54_tc;
