// generated by newgenasym  Mon Dec 18 17:24:12 2017


module \1310pn1u  (comp, fb, fbsel, gnd, in1, in2, in3, in4, in5, lx1, lx2, lx3,
        lx4, lx5, pgnd1, pgnd2, pgnd3, pgnd4, pgnd5, ref, shdn, ss,
        toff, ucc);
    inout comp;
    inout fb;
    inout fbsel;
    inout gnd;
    inout in1;
    inout in2;
    inout in3;
    inout in4;
    inout in5;
    inout lx1;
    inout lx2;
    inout lx3;
    inout lx4;
    inout lx5;
    inout pgnd1;
    inout pgnd2;
    inout pgnd3;
    inout pgnd4;
    inout pgnd5;
    inout ref;
    inout shdn;
    inout ss;
    inout toff;
    inout ucc;


    initial
        begin
        end

endmodule
