// generated by newgenasym  Thu Jun 09 16:43:22 2011


module \74hct74  (\1cp , \1d , \1nq , \1q , \1rd , \1sd , \2cp , \2d , \2nq , \2q , \2rd , \2sd , gnd, vcc);
    inout \1cp ;
    inout \1d ;
    inout \1nq ;
    inout \1q ;
    inout \1rd ;
    inout \1sd ;
    inout \2cp ;
    inout \2d ;
    inout \2nq ;
    inout \2q ;
    inout \2rd ;
    inout \2sd ;
    input gnd;
    input vcc;


    initial
        begin
        end

endmodule
