-- generated by newgenasym Thu Jun 09 16:43:22 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hct74\ is
    port (    
	\1cp\:     INOUT  STD_LOGIC;    
	\1d\:      INOUT  STD_LOGIC;    
	\1nq\:     INOUT  STD_LOGIC;    
	\1q\:      INOUT  STD_LOGIC;    
	\1rd\:     INOUT  STD_LOGIC;    
	\1sd\:     INOUT  STD_LOGIC;    
	\2cp\:     INOUT  STD_LOGIC;    
	\2d\:      INOUT  STD_LOGIC;    
	\2nq\:     INOUT  STD_LOGIC;    
	\2q\:      INOUT  STD_LOGIC;    
	\2rd\:     INOUT  STD_LOGIC;    
	\2sd\:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end \74hct74\;
