// generated by newgenasym  Mon Dec 11 10:31:14 2017


module \1324ps3  (fget, ifn, ifp, inn, inp);
    inout fget;
    inout ifn;
    inout ifp;
    inout inn;
    inout inp;


    initial
        begin
        end

endmodule
