// generated by newgenasym  Fri Feb 11 15:17:04 2005


module ad9958 (agnd, agnd1, agnd10, agnd2, agnd3, agnd4, agnd5, agnd6,
        agnd7, agnd8, agnd9, avdd, avdd1, avdd10, avdd2, avdd3, avdd4,
        avdd5, avdd6, avdd7, avdd8, avdd9, ch0_iout, \ch0_iout* ,
        ch1_iout, \ch1_iout* , clkmod, \cs* , dac_rs, dgnd, dgnd1, dvdd,
        dvdd1, \dvdd_i/o , \i/o_upd , lpf, \n.c. , \n.c.1 , \n.c.2 , \n.c.3 , ps0,
        ps1, ps2, ps3, pwrdn, refclk, \refclk* , reset, sclk, sdio_0,
        sdio_1, sdio_2, sdio_3, sync_clk, sync_in, sync_out);
    input agnd;
    input agnd1;
    input agnd10;
    input agnd2;
    input agnd3;
    input agnd4;
    input agnd5;
    input agnd6;
    input agnd7;
    input agnd8;
    input agnd9;
    input avdd;
    input avdd1;
    input avdd10;
    input avdd2;
    input avdd3;
    input avdd4;
    input avdd5;
    input avdd6;
    input avdd7;
    input avdd8;
    input avdd9;
    output ch0_iout;
    output \ch0_iout* ;
    output ch1_iout;
    output \ch1_iout* ;
    input clkmod;
    input \cs* ;
    input dac_rs;
    input dgnd;
    input dgnd1;
    input dvdd;
    input dvdd1;
    input \dvdd_i/o ;
    input \i/o_upd ;
    input lpf;
    inout \n.c. ;
    inout \n.c.1 ;
    inout \n.c.2 ;
    inout \n.c.3 ;
    input ps0;
    input ps1;
    input ps2;
    input ps3;
    input pwrdn;
    input refclk;
    input \refclk* ;
    input reset;
    input sclk;
    inout sdio_0;
    inout sdio_1;
    inout sdio_2;
    inout sdio_3;
    output sync_clk;
    input sync_in;
    output sync_out;


    initial
        begin
        end

endmodule
