// generated by newgenasym  Wed Aug 15 18:05:36 2012


module mt41j64m16la_187e (a0, a1, \a10/ap , a11, \a12/bcn , a2, a3, a4, a5, a6, a7, a8, a9, ba0,
        ba1, ba2, cas_b, \ck* , ck_p, cke, cs_b, dq0, dq1, dq10, dq11,
        dq12, dq13, dq14, dq15, dq2, dq3, dq4, dq5, dq6, dq7, dq8, dq9,
        ldm, \ldqs* , ldqs_p, \nc/a13 , \nc/a14 , nc1, nc2, nc3, nc4, nc5,
        odt, ras_b, reset_b, udm, \udqs* , udqs_p, vdd1, vdd2, vdd3,
        vdd4, vdd5, vdd6, vdd7, vdd8, vdd9, vddq1, vddq2, vddq3, vddq4,
        vddq5, vddq6, vddq7, vddq8, vddq9, vrefca, vrefdq, vss1,
        vss10, vss11, vss12, vss2, vss3, vss4, vss5, vss6, vss7, vss8,
        vss9, vssq1, vssq2, vssq3, vssq4, vssq5, vssq6, vssq7, vssq8,
        vssq9, we_b, zq);
    inout a0;
    inout a1;
    inout \a10/ap ;
    inout a11;
    inout \a12/bcn ;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout ba2;
    inout cas_b;
    inout \ck* ;
    inout ck_p;
    inout cke;
    inout cs_b;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout ldm;
    inout \ldqs* ;
    inout ldqs_p;
    inout \nc/a13 ;
    inout \nc/a14 ;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout odt;
    inout ras_b;
    inout reset_b;
    inout udm;
    inout \udqs* ;
    inout udqs_p;
    input vdd1;
    input vdd2;
    input vdd3;
    input vdd4;
    input vdd5;
    input vdd6;
    input vdd7;
    input vdd8;
    input vdd9;
    input vddq1;
    input vddq2;
    input vddq3;
    input vddq4;
    input vddq5;
    input vddq6;
    input vddq7;
    input vddq8;
    input vddq9;
    inout vrefca;
    inout vrefdq;
    input vss1;
    input vss10;
    input vss11;
    input vss12;
    input vss2;
    input vss3;
    input vss4;
    input vss5;
    input vss6;
    input vss7;
    input vss8;
    input vss9;
    input vssq1;
    input vssq2;
    input vssq3;
    input vssq4;
    input vssq5;
    input vssq6;
    input vssq7;
    input vssq8;
    input vssq9;
    inout we_b;
    inout zq;


    initial
        begin
        end

endmodule
