// generated by newgenasym  Wed Apr 20 16:05:29 2016


module hmc539lp3 (acg1, acg2, acg3, acg4, acg5, rf1, rf2, v1, v2, v3, v4, v5);
    inout acg1;
    inout acg2;
    inout acg3;
    inout acg4;
    inout acg5;
    inout rf1;
    inout rf2;
    inout v1;
    inout v2;
    inout v3;
    inout v4;
    inout v5;


    initial
        begin
        end

endmodule
