-- generated by newgenasym Thu Aug 23 15:12:01 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc435 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RFC:       INOUT  STD_LOGIC);
end hmc435;
