-- generated by newgenasym Tue Sep 25 14:54:47 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds18s20par is
    port (    
	DQ:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end ds18s20par;
