// generated by newgenasym  Tue Aug 13 13:04:23 2013


module vpb30w8m400aa (\-48v_a , \-48v_b , \-48v_early_a , \-48v_early_b , analog_test,
        emi_chassis_gnd, enable_a, enable_b, hard_m, hard_manager,
        logic_gnd, vrtn_a, vrtn_b);
    inout \-48v_a ;
    inout \-48v_b ;
    inout \-48v_early_a ;
    inout \-48v_early_b ;
    inout [24:17] analog_test;
    inout emi_chassis_gnd;
    inout enable_a;
    inout enable_b;
    inout [16:13] hard_m;
    inout [16:5] hard_manager;
    inout logic_gnd;
    inout vrtn_a;
    inout vrtn_b;


    initial
        begin
        end

endmodule
