-- generated by newgenasym Wed Jul 28 17:30:11 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity VD is
    port (    
	A:         IN     STD_LOGIC;    
	B:         OUT    STD_LOGIC);
end VD;
