// generated by newgenasym  Wed Sep 26 11:13:31 2007


module \ada4937-1  (\+fb , \+in , \+out , \+vs , \+vs2 , \+vs3 , \+vs4 , \-fb , \-in , \-out , \-vs ,
        \-vs2 , \-vs3 , \-vs4 , gnd, pd, vocm);
    inout \+fb ;
    inout \+in ;
    inout \+out ;
    inout \+vs ;
    inout \+vs2 ;
    inout \+vs3 ;
    inout \+vs4 ;
    inout \-fb ;
    inout \-in ;
    inout \-out ;
    inout \-vs ;
    inout \-vs2 ;
    inout \-vs3 ;
    inout \-vs4 ;
    inout gnd;
    inout pd;
    inout vocm;


    initial
        begin
        end

endmodule
