-- generated by newgenasym Wed Sep 26 11:13:31 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ada4937-1\ is
    port (    
	\+fb\:     INOUT  STD_LOGIC;    
	\+in\:     INOUT  STD_LOGIC;    
	\+out\:    INOUT  STD_LOGIC;    
	\+vs\:     INOUT  STD_LOGIC;    
	\+vs2\:    INOUT  STD_LOGIC;    
	\+vs3\:    INOUT  STD_LOGIC;    
	\+vs4\:    INOUT  STD_LOGIC;    
	\-fb\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\-out\:    INOUT  STD_LOGIC;    
	\-vs\:     INOUT  STD_LOGIC;    
	\-vs2\:    INOUT  STD_LOGIC;    
	\-vs3\:    INOUT  STD_LOGIC;    
	\-vs4\:    INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PD:        INOUT  STD_LOGIC;    
	VOCM:      INOUT  STD_LOGIC);
end \ada4937-1\;
