-- generated by newgenasym Wed Nov 08 10:08:51 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g126 is
    port (    
	A:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc1g126;
