// generated by newgenasym  Wed Dec 09 14:42:27 2009


module ad8620 (\+ina , \+inb , \-ina , \-inb , outa, outb, \v+ , \v- );
    inout \+ina ;
    inout \+inb ;
    inout \-ina ;
    inout \-inb ;
    inout outa;
    inout outb;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
