-- generated by newgenasym Wed Dec 09 14:42:27 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8620 is
    port (    
	\+ina\:    INOUT  STD_LOGIC;    
	\+inb\:    INOUT  STD_LOGIC;    
	\-ina\:    INOUT  STD_LOGIC;    
	\-inb\:    INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end ad8620;
