// generated by newgenasym  Sat Dec 26 13:05:53 2009


module adsp_bf533 (abe0, abe1, addr1, addr10, addr11, addr12, addr13, addr14,
        addr15, addr16, addr17, addr18, addr19, addr2, addr3, addr4,
        addr5, addr6, addr7, addr8, addr9, ams0, ams1, ams2, ams3, aoe,
        ardy, are, awe, bg, bgh, bmode0, bmode1, br, clkin, clkout,
        data0, data1, data10, data11, data12, data13, data14, data15,
        data2, data3, data4, data5, data6, data7, data8, data9,
        dr0pri, dr0sec, dr1pri, dr1sec, dt0pri, dt0sec, dt1pri,
        dt1sec, emu, miso, mosi, nmi, pf0, pf1, pf10, pf11, pf12, pf13,
        pf14, pf15, pf2, pf3, pf4, pf5, pf6, pf7, pf8, pf9, ppi_0, ppi_1,
        ppi_2, ppi_3, ppi_clk, reset, rfs0, rfs1, rsclk0, rsclk1,
        rtxi, rtxo, rx, sa10, scas, sck, scke, sms, sras, swe, tck, tdi,
        tdo, tfs0, tfs1, tmr0, tmr1, tmr2, tms, trst, tsclk0, tsclk1,
        tx, vrout0, vrout1, xtal);
    inout abe0;
    inout abe1;
    inout addr1;
    inout addr10;
    inout addr11;
    inout addr12;
    inout addr13;
    inout addr14;
    inout addr15;
    inout addr16;
    inout addr17;
    inout addr18;
    inout addr19;
    inout addr2;
    inout addr3;
    inout addr4;
    inout addr5;
    inout addr6;
    inout addr7;
    inout addr8;
    inout addr9;
    inout ams0;
    inout ams1;
    inout ams2;
    inout ams3;
    inout aoe;
    inout ardy;
    inout are;
    inout awe;
    inout bg;
    inout bgh;
    inout bmode0;
    inout bmode1;
    inout br;
    inout clkin;
    inout clkout;
    inout data0;
    inout data1;
    inout data10;
    inout data11;
    inout data12;
    inout data13;
    inout data14;
    inout data15;
    inout data2;
    inout data3;
    inout data4;
    inout data5;
    inout data6;
    inout data7;
    inout data8;
    inout data9;
    inout dr0pri;
    inout dr0sec;
    inout dr1pri;
    inout dr1sec;
    inout dt0pri;
    inout dt0sec;
    inout dt1pri;
    inout dt1sec;
    inout emu;
    inout miso;
    inout mosi;
    inout nmi;
    inout pf0;
    inout pf1;
    inout pf10;
    inout pf11;
    inout pf12;
    inout pf13;
    inout pf14;
    inout pf15;
    inout pf2;
    inout pf3;
    inout pf4;
    inout pf5;
    inout pf6;
    inout pf7;
    inout pf8;
    inout pf9;
    inout ppi_0;
    inout ppi_1;
    inout ppi_2;
    inout ppi_3;
    inout ppi_clk;
    inout reset;
    inout rfs0;
    inout rfs1;
    inout rsclk0;
    inout rsclk1;
    inout rtxi;
    inout rtxo;
    inout rx;
    inout sa10;
    inout scas;
    inout sck;
    inout scke;
    inout sms;
    inout sras;
    inout swe;
    inout tck;
    inout tdi;
    inout tdo;
    inout tfs0;
    inout tfs1;
    inout tmr0;
    inout tmr1;
    inout tmr2;
    inout tms;
    inout trst;
    inout tsclk0;
    inout tsclk1;
    inout tx;
    output vrout0;
    output vrout1;
    inout xtal;


    initial
        begin
        end

endmodule
