// generated by newgenasym  Thu Jun 27 15:40:07 2013


module ltc2208 (\ain+ , \ain- , \clkout+/clkoutb , \clkout-/ofb , \d0+/db1 ,
        \d0-/db0 , \d1+/db3 , \d1-/db2 , \d10+/da4 , \d10-/da3 , \d11+/da6 ,
        \d11-/da5 , \d12+/da8 , \d12-/da7 , \d13+/da10 , \d13-/da9 ,
        \d14+/da12 , \d14-/da11 , \d15+/da14 , \d15-/da13 , \d2+/db5 ,
        \d2-/db4 , \d3+/db7 , \d3-/db6 , \d4+/db9 , \d4-/db8 , \d5+/db11 ,
        \d5-/db10 , \d6+/db13 , \d6-/db12 , \d7+/db15 , \d7-/db14 , \d8+/da0 ,
        \d8-/clkouta , \d9+/da2 , \d9-/da1 , dith, \enc+ , \enc- , lvds, mode,
        \of+/ofa , \of-/da15 , pga, rand, sense, shdn, vcm);
    inout \ain+ ;
    inout \ain- ;
    output \clkout+/clkoutb ;
    output \clkout-/ofb ;
    output \d0+/db1 ;
    output \d0-/db0 ;
    output \d1+/db3 ;
    output \d1-/db2 ;
    output \d10+/da4 ;
    output \d10-/da3 ;
    output \d11+/da6 ;
    output \d11-/da5 ;
    output \d12+/da8 ;
    output \d12-/da7 ;
    output \d13+/da10 ;
    output \d13-/da9 ;
    output \d14+/da12 ;
    output \d14-/da11 ;
    output \d15+/da14 ;
    output \d15-/da13 ;
    output \d2+/db5 ;
    output \d2-/db4 ;
    output \d3+/db7 ;
    output \d3-/db6 ;
    output \d4+/db9 ;
    output \d4-/db8 ;
    output \d5+/db11 ;
    output \d5-/db10 ;
    output \d6+/db13 ;
    output \d6-/db12 ;
    output \d7+/db15 ;
    output \d7-/db14 ;
    output \d8+/da0 ;
    output \d8-/clkouta ;
    output \d9+/da2 ;
    output \d9-/da1 ;
    inout dith;
    inout \enc+ ;
    inout \enc- ;
    inout lvds;
    inout mode;
    inout \of+/ofa ;
    output \of-/da15 ;
    inout pga;
    inout rand;
    input sense;
    inout shdn;
    inout vcm;


    initial
        begin
        end

endmodule
