// generated by newgenasym  Mon Oct 16 16:36:54 2006


module \ipl1-105  (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
