// generated by newgenasym  Thu Apr 10 11:52:26 2003


module cnp135 (a12, a3, a45, a7, a9, b11, b3, b38, b39, b40, b41, b42, b43, b44,
        b45, b8, b9, c1, c2, c28, c3, c30, c32, c34, c36, c37, c38, c39,
        c40, c41, c42, c43, c44, c45);
    input a12;
    input a3;
    input a45;
    input a7;
    input a9;
    input b11;
    input b3;
    input b38;
    input b39;
    input b40;
    input b41;
    input b42;
    input b43;
    input b44;
    input b45;
    input b8;
    input b9;
    input c1;
    input c2;
    input c28;
    input c3;
    input c30;
    input c32;
    input c34;
    input c36;
    input c37;
    input c38;
    input c39;
    input c40;
    input c41;
    input c42;
    input c43;
    input c44;
    input c45;


    initial
        begin
        end

endmodule
