-- generated by newgenasym Thu Apr 10 11:52:26 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cnp135 is
    port (    
	A12:       IN     STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A45:       IN     STD_LOGIC;    
	A7:        IN     STD_LOGIC;    
	A9:        IN     STD_LOGIC;    
	B11:       IN     STD_LOGIC;    
	B3:        IN     STD_LOGIC;    
	B38:       IN     STD_LOGIC;    
	B39:       IN     STD_LOGIC;    
	B40:       IN     STD_LOGIC;    
	B41:       IN     STD_LOGIC;    
	B42:       IN     STD_LOGIC;    
	B43:       IN     STD_LOGIC;    
	B44:       IN     STD_LOGIC;    
	B45:       IN     STD_LOGIC;    
	B8:        IN     STD_LOGIC;    
	B9:        IN     STD_LOGIC;    
	C1:        IN     STD_LOGIC;    
	C2:        IN     STD_LOGIC;    
	C28:       IN     STD_LOGIC;    
	C3:        IN     STD_LOGIC;    
	C30:       IN     STD_LOGIC;    
	C32:       IN     STD_LOGIC;    
	C34:       IN     STD_LOGIC;    
	C36:       IN     STD_LOGIC;    
	C37:       IN     STD_LOGIC;    
	C38:       IN     STD_LOGIC;    
	C39:       IN     STD_LOGIC;    
	C40:       IN     STD_LOGIC;    
	C41:       IN     STD_LOGIC;    
	C42:       IN     STD_LOGIC;    
	C43:       IN     STD_LOGIC;    
	C44:       IN     STD_LOGIC;    
	C45:       IN     STD_LOGIC);
end cnp135;
