// generated by newgenasym  Tue Aug 31 18:33:42 2004


module \molex43650-0426  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
