// generated by newgenasym  Wed Aug 15 11:30:57 2018


module adl5375 (dsop, ibbn, ibbp, loin, loip, qbbn, qbbp, rfout);
    inout dsop;
    inout ibbn;
    inout ibbp;
    inout loin;
    inout loip;
    inout qbbn;
    inout qbbp;
    inout rfout;


    initial
        begin
        end

endmodule
