// generated by newgenasym  Wed Jun 02 15:46:15 2004


module rg_leds (\1 , \2 , \3 , \4 );
    output \1 ;
    input \2 ;
    output \3 ;
    input \4 ;


    initial
        begin
        end

endmodule
