-- generated by newgenasym Wed Jun 02 15:46:15 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rg_leds is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC);
end rg_leds;
