// generated by newgenasym  Thu Dec 07 13:49:01 2017


module \1288hk1t  (addr, clk, csn, data, encode, idat1, idat2, idat3, idat4, irq,
        lack, lclk, num, p32, pclk, pf_rrn, pmode0, pmode1, psync,
        rdn_rw, rdy_ackn, rstn, sclk, scsn, sdi, sdo, sync_clr,
        sync_gain, sync_nco, sync_start, tck, tdi, tdo, tms, trstn,
        wrn_dsn);
    inout [5:0] addr;
    inout clk;
    inout csn;
    inout [31:0] data;
    inout encode;
    input [15:0] idat1;
    input [15:0] idat2;
    input [15:0] idat3;
    input [15:0] idat4;
    inout irq;
    inout lack;
    inout lclk;
    inout [2:0] num;
    inout p32;
    inout pclk;
    output pf_rrn;
    inout pmode0;
    inout pmode1;
    inout psync;
    inout rdn_rw;
    output rdy_ackn;
    inout rstn;
    inout sclk;
    inout scsn;
    inout sdi;
    inout sdo;
    inout sync_clr;
    inout sync_gain;
    inout sync_nco;
    inout sync_start;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout trstn;
    inout wrn_dsn;


    initial
        begin
        end

endmodule
