// generated by newgenasym  Thu Jul 01 15:43:30 2004


module pcf8575 (a, gndd, \int* , p, p5v0, scl, sda);
    input [2:0] a;
    input gndd;
    output \int* ;
    inout [15:0] p;
    input p5v0;
    input scl;
    inout sda;


    initial
        begin
        end

endmodule
