-- generated by newgenasym Wed Oct 27 17:23:04 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity qse_020_50_new is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	GND:       INOUT  STD_LOGIC_VECTOR (41 DOWNTO 41));
end qse_020_50_new;
