// generated by newgenasym  Mon May 15 17:30:19 2017


module tca9543a (a0, a1, int, int0, int1, reset, sc0, sc1, scl, sd0, sd1, sda);
    inout a0;
    inout a1;
    inout int;
    inout int0;
    inout int1;
    inout reset;
    inout sc0;
    inout sc1;
    inout scl;
    inout sd0;
    inout sd1;
    inout sda;


    initial
        begin
        end

endmodule
