-- generated by newgenasym Mon May 15 17:30:19 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tca9543a is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	INT:       INOUT  STD_LOGIC;    
	INT0:      INOUT  STD_LOGIC;    
	INT1:      INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	SC0:       INOUT  STD_LOGIC;    
	SC1:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SD0:       INOUT  STD_LOGIC;    
	SD1:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end tca9543a;
