// generated by newgenasym  Fri Aug 17 09:45:33 2018


module tcm1_43x (\pri#20dot , pri1, pri2, sec, \sec#20dot );
    inout \pri#20dot ;
    inout pri1;
    inout pri2;
    inout sec;
    inout \sec#20dot ;


    initial
        begin
        end

endmodule
