-- generated by newgenasym Fri Aug 17 09:45:33 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tcm1_43x is
    port (    
	\pri dot\: INOUT  STD_LOGIC;    
	PRI1:      INOUT  STD_LOGIC;    
	PRI2:      INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	\sec dot\: INOUT  STD_LOGIC);
end tcm1_43x;
