// generated by newgenasym  Tue Jul 04 17:06:57 2006


module ks8721bl (col, crs, fxsd, gnd0, gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7,
        int, led0, led1, led2, led3, mdc, mdio, pd, rext, rst, \rx+ , \rx- ,
        rxc, rxd0, rxd1, rxd2, rxd3, rxdv, rxer, \tx+ , \tx- , txc, txd0,
        txd1, txd2, txd3, txen, txer, vddc, vddio0, vddio1, vddpll,
        vddrcv, vddrx, vddtx, xi, xo);
    input col;
    input crs;
    inout fxsd;
    input gnd0;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    output int;
    output led0;
    output led1;
    output led2;
    output led3;
    input mdc;
    input mdio;
    output pd;
    output rext;
    input rst;
    output \rx+ ;
    output \rx- ;
    input rxc;
    input rxd0;
    input rxd1;
    input rxd2;
    input rxd3;
    input rxdv;
    input rxer;
    output \tx+ ;
    output \tx- ;
    input txc;
    input txd0;
    input txd1;
    input txd2;
    input txd3;
    input txen;
    input txer;
    input vddc;
    input vddio0;
    input vddio1;
    input vddpll;
    input vddrcv;
    input vddrx;
    input vddtx;
    input xi;
    input xo;


    initial
        begin
        end

endmodule
