// generated by newgenasym  Fri Oct 29 15:50:09 2004


module ad8324jrq (byp, clk, \daten* , gnd, gnd1, gnd2, gnd3, gnd4, gnd5, \n.c. ,
        ramp, sdata, \sleep* , txen, vcc1, vcc2, \vin+ , \vin- , \vout+ ,
        \vout- );
    output byp;
    input clk;
    input \daten* ;
    input gnd;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    inout \n.c. ;
    output ramp;
    input sdata;
    input \sleep* ;
    input txen;
    input vcc1;
    input vcc2;
    input \vin+ ;
    input \vin- ;
    output \vout+ ;
    output \vout- ;


    initial
        begin
        end

endmodule
