-- generated by newgenasym Fri Oct 29 15:50:09 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD8324JRQ is
    port (    
	BYP:       OUT    STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	\daten*\:  IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	GND5:      IN     STD_LOGIC;    
	\n.c.\:    INOUT  STD_LOGIC;    
	RAMP:      OUT    STD_LOGIC;    
	SDATA:     IN     STD_LOGIC;    
	\sleep*\:  IN     STD_LOGIC;    
	TXEN:      IN     STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	\vin+\:    IN     STD_LOGIC;    
	\vin-\:    IN     STD_LOGIC;    
	\vout+\:   OUT    STD_LOGIC;    
	\vout-\:   OUT    STD_LOGIC);
end AD8324JRQ;
