-- generated by newgenasym Fri Jun 04 14:34:50 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity qte_20 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	GNDD:      INOUT  STD_LOGIC);
end qte_20;
