-- generated by newgenasym Tue Dec 27 13:10:45 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sga6589ds is
    port (    
	RF_IN:     INOUT  STD_LOGIC;    
	RF_OUT:    INOUT  STD_LOGIC);
end sga6589ds;
