-- generated by newgenasym Tue May 16 16:03:14 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fp3p7_516_1a is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end fp3p7_516_1a;
