// generated by newgenasym  Tue Dec 15 17:39:28 2009


module max3053 (canh, canl, gnd, rs, rxd, \shdn# , txd, vcc);
    inout canh;
    inout canl;
    inout gnd;
    inout rs;
    inout rxd;
    inout \shdn# ;
    inout txd;
    inout vcc;


    initial
        begin
        end

endmodule
