// generated by newgenasym  Tue Nov 13 10:30:09 2012


module tdr3 (\+vin , \+vout , \-vin , \-vout , \on/off );
    inout \+vin ;
    inout \+vout ;
    inout \-vin ;
    inout \-vout ;
    inout \on/off ;


    initial
        begin
        end

endmodule
