-- generated by newgenasym Tue Nov 13 10:30:09 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tdr3 is
    port (    
	\+vin\:    INOUT  STD_LOGIC;    
	\+vout\:   INOUT  STD_LOGIC;    
	\-vin\:    INOUT  STD_LOGIC;    
	\-vout\:   INOUT  STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC);
end tdr3;
