// generated by newgenasym  Thu May 18 14:27:09 2017


module tps74401 (bias, en, fb, in0, in1, in2, in3, out0, out1, out2, out3, pg, ss);
    inout bias;
    inout en;
    inout fb;
    inout in0;
    inout in1;
    inout in2;
    inout in3;
    inout out0;
    inout out1;
    inout out2;
    inout out3;
    inout pg;
    inout ss;


    initial
        begin
        end

endmodule
