-- generated by newgenasym Thu May 18 14:27:09 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps74401 is
    port (    
	BIAS:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	IN0:       INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	OUT0:      INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC);
end tps74401;
