// generated by newgenasym  Mon May 10 14:53:13 2004


module pci9656ba (\2p5_vaux , \64en* , \ack64* , ad, \ads* , \bd_sel* , \bigend* , \blast* ,
        breqi, breqo, \bterm* , \c_be* , card_vaux, \ccs* , cpcisw, \dack0* ,
        \dack1* , \devsel* , \dmpaf_eot* , dp, \dreq0* , \dreq1* , eecs,
        eedi_eedo, eesk, \enum* , \frame* , gndd, \gnt* , \gnt0_req* ,
        \hosten* , \iddqen* , idsel, \inta* , \irdy* , la, \lbe* , lclk, ld,
        \led_on* , lhold, lholda, \linti* , \linto* , \lock* , \lreset* ,
        \lserr* , \lw_rn* , mode0, mode1, p2v5, par, par_64, pclk,
        \pemereq* , \perr* , \pme* , present_det, \ready* , \req* , \req0_gnt* ,
        \req_64* , \rst* , \serr* , \stop* , tck, tdi, tdo, tms, \trdy* , \trst* ,
        \useri* , \usero* , vio, vring, \wait* );
    input \2p5_vaux ;
    input \64en* ;
    inout \ack64* ;
    inout [63:0] ad;
    inout \ads* ;
    input \bd_sel* ;
    input \bigend* ;
    inout \blast* ;
    input breqi;
    output breqo;
    inout \bterm* ;
    inout [7:0] \c_be* ;
    input card_vaux;
    input \ccs* ;
    input cpcisw;
    output \dack0* ;
    output \dack1* ;
    inout \devsel* ;
    inout \dmpaf_eot* ;
    inout [3:0] dp;
    input \dreq0* ;
    input \dreq1* ;
    output eecs;
    inout eedi_eedo;
    output eesk;
    output \enum* ;
    inout \frame* ;
    input [17:0] gndd;
    output [6:1] \gnt* ;
    output \gnt0_req* ;
    input \hosten* ;
    input \iddqen* ;
    input idsel;
    inout \inta* ;
    inout \irdy* ;
    inout [31:2] la;
    inout [3:0] \lbe* ;
    input lclk;
    inout [31:0] ld;
    output \led_on* ;
    output lhold;
    input lholda;
    input \linti* ;
    output \linto* ;
    inout \lock* ;
    inout \lreset* ;
    output \lserr* ;
    inout \lw_rn* ;
    input mode0;
    input mode1;
    input [5:0] p2v5;
    inout par;
    inout par_64;
    input pclk;
    input \pemereq* ;
    inout \perr* ;
    output \pme* ;
    input present_det;
    inout \ready* ;
    input [6:1] \req* ;
    input \req0_gnt* ;
    inout \req_64* ;
    inout \rst* ;
    inout \serr* ;
    inout \stop* ;
    input tck;
    input tdi;
    output tdo;
    input tms;
    inout \trdy* ;
    input \trst* ;
    input \useri* ;
    output \usero* ;
    input [3:0] vio;
    input [25:0] vring;
    inout \wait* ;


    initial
        begin
        end

endmodule
