// generated by newgenasym  Tue Jun 01 12:00:21 2004


module sn74lvc1g86 (a, b, gndd, p5v0, y);
    input a;
    input b;
    input gndd;
    input p5v0;
    output y;


    initial
        begin
        end

endmodule
