// generated by newgenasym  Tue May 25 15:39:13 2004


module b82720 (a, b, c, d, y1, y2, y3, y4);
    input a;
    input b;
    input c;
    input d;
    output y1;
    output y2;
    output y3;
    output y4;


    initial
        begin
        end

endmodule
