// generated by newgenasym  Wed Apr 11 17:40:29 2018


module lm25056 (adr0, adr1, adr2, diod, enable, scl, sda, smba, vaux, vdd,
        vref, \vs+ , \vs- );
    inout adr0;
    inout adr1;
    inout adr2;
    inout diod;
    inout enable;
    inout scl;
    inout sda;
    inout smba;
    inout vaux;
    inout vdd;
    inout vref;
    inout \vs+ ;
    inout \vs- ;


    initial
        begin
        end

endmodule
