-- generated by newgenasym Wed Apr 11 17:40:29 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm25056 is
    port (    
	ADR0:      INOUT  STD_LOGIC;    
	ADR1:      INOUT  STD_LOGIC;    
	ADR2:      INOUT  STD_LOGIC;    
	DIOD:      INOUT  STD_LOGIC;    
	ENABLE:    INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SMBA:      INOUT  STD_LOGIC;    
	VAUX:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	\vs+\:     INOUT  STD_LOGIC;    
	\vs-\:     INOUT  STD_LOGIC);
end lm25056;
