-- generated by newgenasym Tue Dec 13 16:30:56 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \sxbp-425\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \sxbp-425\;
