// generated by newgenasym  Thu Jul 01 12:32:04 2004


module sn74lvc2g126 (\1a , \1oe , \1y , \2a , \2oe , \2y , gnd, vcc);
    input \1a ;
    input \1oe ;
    output \1y ;
    input \2a ;
    input \2oe ;
    output \2y ;
    input gnd;
    input vcc;


    initial
        begin
        end

endmodule
