-- generated by newgenasym Thu Jul 01 12:32:04 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g126 is
    port (    
	\1a\:      IN     STD_LOGIC;    
	\1oe\:     IN     STD_LOGIC;    
	\1y\:      OUT    STD_LOGIC;    
	\2a\:      IN     STD_LOGIC;    
	\2oe\:     IN     STD_LOGIC;    
	\2y\:      OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end sn74lvc2g126;
