-- generated by newgenasym Thu Apr 27 15:23:05 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \afct-5715pz\ is
    port (    
	LOS:       INOUT  STD_LOGIC;    
	\mod-def0\: INOUT  STD_LOGIC;    
	\mod-def1\: INOUT  STD_LOGIC;    
	\mod-def2\: INOUT  STD_LOGIC;    
	\rate selection\: INOUT  STD_LOGIC;    
	\rd+\:     INOUT  STD_LOGIC;    
	\rd-\:     INOUT  STD_LOGIC;    
	\td+\:     INOUT  STD_LOGIC;    
	\td-\:     INOUT  STD_LOGIC;    
	\tx disable\: INOUT  STD_LOGIC;    
	\tx fault\: INOUT  STD_LOGIC;    
	VCCR:      IN     STD_LOGIC;    
	VCCT:      IN     STD_LOGIC);
end \afct-5715pz\;
