// generated by newgenasym  Mon Oct 13 16:48:59 2003


module max3485esa (a, b, de, di, \re* , ro);
    output a;
    output b;
    input de;
    input di;
    input \re* ;
    output ro;


    initial
        begin
        end

endmodule
