// generated by newgenasym  Mon Oct 20 17:03:40 2003


module sa532d (a, \a* , a_out, b, \b* , b_out, n3v3a, p3v3a);
    input a;
    input \a* ;
    output a_out;
    input b;
    input \b* ;
    output b_out;
    input n3v3a;
    input p3v3a;


    initial
        begin
        end

endmodule
