-- generated by newgenasym Mon Oct 20 17:03:40 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sa532d is
    port (    
	A:         IN     STD_LOGIC;    
	\a*\:      IN     STD_LOGIC;    
	A_OUT:     OUT    STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	\b*\:      IN     STD_LOGIC;    
	B_OUT:     OUT    STD_LOGIC;    
	N3V3A:     IN     STD_LOGIC;    
	P3V3A:     IN     STD_LOGIC);
end sa532d;
