-- generated by newgenasym Sat Feb 05 14:54:26 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g07 is
    port (    
	A:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc2g07;
