// generated by newgenasym  Wed Nov 23 11:22:55 2005


module kt18 (gnd, out, vcc, vcon);
    input gnd;
    inout out;
    input vcc;
    inout vcon;


    initial
        begin
        end

endmodule
