-- generated by newgenasym Wed Nov 23 11:22:55 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity kt18 is
    port (    
	GND:       IN     STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VCON:      INOUT  STD_LOGIC);
end kt18;
