-- generated by newgenasym Tue Jul 01 15:15:48 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hcpl0931 is
    port (    
	\1in\:     IN     STD_LOGIC;    
	\1out\:    OUT    STD_LOGIC;    
	\2in\:     IN     STD_LOGIC;    
	\2out\:    OUT    STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC);
end hcpl0931;
