// generated by newgenasym  Fri Apr 19 12:40:59 2013


module \tel#2030-2412  (\+vin , \+vout , \-vin , \-vout , \on/off , trim);
    inout \+vin ;
    inout \+vout ;
    inout \-vin ;
    inout \-vout ;
    inout \on/off ;
    inout trim;


    initial
        begin
        end

endmodule
