// generated by newgenasym  Tue Sep 11 17:20:49 2012


module ad9643 (\clk+ , \clk- , csb, \d0+ , \d0- , \d1+ , \d1- , \d10+ , \d10- , \d11+ , \d11- ,
        \d12+ , \d12- , \d13+ , \d13- , \d2+ , \d2- , \d3+ , \d3- , \d4+ , \d4- , \d5+ , \d5- ,
        \d6+ , \d6- , \d7+ , \d7- , \d8+ , \d8- , \d9+ , \d9- , \dco+ , \dco- , oeb, \or+ , \or- ,
        pdwn, sclk, sdio, sync, vcm, \vin+a , \vin+b , \vin-a , \vin-b );
    inout \clk+ ;
    inout \clk- ;
    inout csb;
    inout \d0+ ;
    inout \d0- ;
    inout \d1+ ;
    inout \d1- ;
    inout \d10+ ;
    inout \d10- ;
    inout \d11+ ;
    inout \d11- ;
    inout \d12+ ;
    inout \d12- ;
    inout \d13+ ;
    inout \d13- ;
    inout \d2+ ;
    inout \d2- ;
    inout \d3+ ;
    inout \d3- ;
    inout \d4+ ;
    inout \d4- ;
    inout \d5+ ;
    inout \d5- ;
    inout \d6+ ;
    inout \d6- ;
    inout \d7+ ;
    inout \d7- ;
    inout \d8+ ;
    inout \d8- ;
    inout \d9+ ;
    inout \d9- ;
    inout \dco+ ;
    inout \dco- ;
    inout oeb;
    inout \or+ ;
    inout \or- ;
    inout pdwn;
    inout sclk;
    inout sdio;
    inout sync;
    inout vcm;
    inout \vin+a ;
    inout \vin+b ;
    inout \vin-a ;
    inout \vin-b ;


    initial
        begin
        end

endmodule
