// generated by newgenasym  Mon Nov 16 11:37:45 2009


module ltc1264 (agnd, bpa, bpb, bpc, bpd, clk, \hpa/na , \hpb/nb , \hpc/nc , \hpd/nd ,
        inv_a, inv_b, inv_c, inv_d, lpa, lpb, lpc, lpd, sa, sb, sc, sd,
        \v+ , \v- );
    inout agnd;
    inout bpa;
    inout bpb;
    inout bpc;
    inout bpd;
    inout clk;
    inout \hpa/na ;
    inout \hpb/nb ;
    inout \hpc/nc ;
    inout \hpd/nd ;
    inout inv_a;
    inout inv_b;
    inout inv_c;
    inout inv_d;
    inout lpa;
    inout lpb;
    inout lpc;
    inout lpd;
    inout sa;
    inout sb;
    inout sc;
    inout sd;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
