-- generated by newgenasym Mon Nov 16 11:37:45 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ltc1264 is
    port (    
	AGND:      INOUT  STD_LOGIC;    
	BPA:       INOUT  STD_LOGIC;    
	BPB:       INOUT  STD_LOGIC;    
	BPC:       INOUT  STD_LOGIC;    
	BPD:       INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	\hpa/na\:  INOUT  STD_LOGIC;    
	\hpb/nb\:  INOUT  STD_LOGIC;    
	\hpc/nc\:  INOUT  STD_LOGIC;    
	\hpd/nd\:  INOUT  STD_LOGIC;    
	INV_A:     INOUT  STD_LOGIC;    
	INV_B:     INOUT  STD_LOGIC;    
	INV_C:     INOUT  STD_LOGIC;    
	INV_D:     INOUT  STD_LOGIC;    
	LPA:       INOUT  STD_LOGIC;    
	LPB:       INOUT  STD_LOGIC;    
	LPC:       INOUT  STD_LOGIC;    
	LPD:       INOUT  STD_LOGIC;    
	SA:        INOUT  STD_LOGIC;    
	SB:        INOUT  STD_LOGIC;    
	SC:        INOUT  STD_LOGIC;    
	SD:        INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end ltc1264;
