-- generated by newgenasym Mon Dec 28 14:36:30 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD9225 is
    port (    
	BIT1:      INOUT  STD_LOGIC;    
	BIT10:     INOUT  STD_LOGIC;    
	BIT11:     INOUT  STD_LOGIC;    
	BIT12:     INOUT  STD_LOGIC;    
	BIT2:      INOUT  STD_LOGIC;    
	BIT3:      INOUT  STD_LOGIC;    
	BIT4:      INOUT  STD_LOGIC;    
	BIT5:      INOUT  STD_LOGIC;    
	BIT6:      INOUT  STD_LOGIC;    
	BIT7:      INOUT  STD_LOGIC;    
	BIT8:      INOUT  STD_LOGIC;    
	BIT9:      INOUT  STD_LOGIC;    
	CAPB:      INOUT  STD_LOGIC;    
	CAPT:      INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CML:       INOUT  STD_LOGIC;    
	DRVDD:     INOUT  STD_LOGIC;    
	DRVSS:     INOUT  STD_LOGIC;    
	OTR:       INOUT  STD_LOGIC;    
	REFCOM:    INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	VINA:      INOUT  STD_LOGIC;    
	VINB:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end AD9225;
