// generated by newgenasym  Thu Dec 17 18:02:57 2009


module ina152 (n3v3, p3v3, ref, sense, v0, \v_in+ , \v_in- );
    inout n3v3;
    inout p3v3;
    output ref;
    output sense;
    output v0;
    input \v_in+ ;
    input \v_in- ;


    initial
        begin
        end

endmodule
