// generated by newgenasym  Wed Jul 26 10:26:33 2017


module pha_11 (\rf#20in1 , \rf#20in2 , \rf#20out1 , \rf#20out2 );
    inout \rf#20in1 ;
    inout \rf#20in2 ;
    inout \rf#20out1 ;
    inout \rf#20out2 ;


    initial
        begin
        end

endmodule
