-- generated by newgenasym Wed Jul 26 10:26:33 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pha_11 is
    port (    
	\rf in1\:  INOUT  STD_LOGIC;    
	\rf in2\:  INOUT  STD_LOGIC;    
	\rf out1\: INOUT  STD_LOGIC;    
	\rf out2\: INOUT  STD_LOGIC);
end pha_11;
