// generated by newgenasym  Mon Oct 20 17:01:12 2003


module max3384eeap (\c1+ , \c1- , \c2+ , \c2- , r1in, r1out, r2in, r2out, \shdn* , t1in,
        t1out, t2in, t2out, \v+ , \v- );
    input \c1+ ;
    input \c1- ;
    input \c2+ ;
    input \c2- ;
    input r1in;
    output r1out;
    input r2in;
    output r2out;
    input \shdn* ;
    input t1in;
    output t1out;
    input t2in;
    output t2out;
    output \v+ ;
    output \v- ;


    initial
        begin
        end

endmodule
