-- generated by newgenasym Thu Sep 25 16:14:18 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       OUT    STD_LOGIC);
end r;
