// generated by newgenasym  Thu Dec 30 12:12:48 2004


module max9000esa (\ain+ , \ain- , aout, \cin+ , cout, ref, vdd, vss);
    input \ain+ ;
    input \ain- ;
    output aout;
    input \cin+ ;
    output cout;
    output ref;
    input vdd;
    input vss;


    initial
        begin
        end

endmodule
