-- generated by newgenasym Thu Dec 30 12:12:48 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX9000ESA is
    port (    
	\ain+\:    IN     STD_LOGIC;    
	\ain-\:    IN     STD_LOGIC;    
	AOUT:      OUT    STD_LOGIC;    
	\cin+\:    IN     STD_LOGIC;    
	COUT:      OUT    STD_LOGIC;    
	REF:       OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC);
end MAX9000ESA;
