-- generated by newgenasym Wed Mar 14 18:38:14 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity vt is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       OUT    STD_LOGIC;    
	\3\:       OUT    STD_LOGIC);
end vt;
