// generated by newgenasym  Mon Nov 16 09:57:30 2009


module ina128 (\+in , \+v , \-in , \-v , ref, rg1, rg2, vo);
    inout \+in ;
    inout \+v ;
    inout \-in ;
    inout \-v ;
    inout ref;
    inout rg1;
    inout rg2;
    inout vo;


    initial
        begin
        end

endmodule
