-- generated by newgenasym Thu Jul 26 11:30:03 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PBTC3G is
    port (    
	DC:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND10:     INOUT  STD_LOGIC;    
	GND11:     INOUT  STD_LOGIC;    
	GND12:     INOUT  STD_LOGIC;    
	GND13:     INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GND5:      INOUT  STD_LOGIC;    
	GND6:      INOUT  STD_LOGIC;    
	GND7:      INOUT  STD_LOGIC;    
	GND8:      INOUT  STD_LOGIC;    
	GND9:      INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	RF_DC:     INOUT  STD_LOGIC);
end PBTC3G;
