-- generated by newgenasym Fri Jul 20 17:08:58 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max5402 is
    port (    
	CS:        INOUT  STD_LOGIC;    
	DIN:       INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	H:         INOUT  STD_LOGIC;    
	L:         INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	W:         INOUT  STD_LOGIC);
end max5402;
