// generated by newgenasym  Wed Sep 13 13:27:26 2017


module tc4_1w_17ln (pri, \pri#20dot , sec, \sec#20ct , \sec#20dot );
    inout pri;
    inout \pri#20dot ;
    inout sec;
    inout \sec#20ct ;
    inout \sec#20dot ;


    initial
        begin
        end

endmodule
