-- generated by newgenasym Wed Sep 13 13:27:26 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tc4_1w_17ln is
    port (    
	PRI:       INOUT  STD_LOGIC;    
	\pri dot\: INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	\sec ct\:  INOUT  STD_LOGIC;    
	\sec dot\: INOUT  STD_LOGIC);
end tc4_1w_17ln;
