// generated by newgenasym  Thu Dec 08 16:50:29 2011


module adclk846 (clk_n, clk_p, ctrl_a, ctrl_b, out0_n, out0_p, out1_n,
        out1_p, out2_n, out2_p, out3_n, out3_p, out4_n, out4_p,
        out5_n, out5_p, sleep, vref);
    inout clk_n;
    inout clk_p;
    inout ctrl_a;
    inout ctrl_b;
    inout out0_n;
    inout out0_p;
    inout out1_n;
    inout out1_p;
    inout out2_n;
    inout out2_p;
    inout out3_n;
    inout out3_p;
    inout out4_n;
    inout out4_p;
    inout out5_n;
    inout out5_p;
    inout sleep;
    inout vref;


    initial
        begin
        end

endmodule
