-- generated by newgenasym Thu Dec 08 16:50:29 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adclk846 is
    port (    
	CLK_N:     INOUT  STD_LOGIC;    
	CLK_P:     INOUT  STD_LOGIC;    
	CTRL_A:    INOUT  STD_LOGIC;    
	CTRL_B:    INOUT  STD_LOGIC;    
	OUT0_N:    INOUT  STD_LOGIC;    
	OUT0_P:    INOUT  STD_LOGIC;    
	OUT1_N:    INOUT  STD_LOGIC;    
	OUT1_P:    INOUT  STD_LOGIC;    
	OUT2_N:    INOUT  STD_LOGIC;    
	OUT2_P:    INOUT  STD_LOGIC;    
	OUT3_N:    INOUT  STD_LOGIC;    
	OUT3_P:    INOUT  STD_LOGIC;    
	OUT4_N:    INOUT  STD_LOGIC;    
	OUT4_P:    INOUT  STD_LOGIC;    
	OUT5_N:    INOUT  STD_LOGIC;    
	OUT5_P:    INOUT  STD_LOGIC;    
	SLEEP:     INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end adclk846;
