-- generated by newgenasym Tue Jun 08 15:14:33 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity idc30 is
    port (    
	I1:        INOUT  STD_LOGIC;    
	I10:       INOUT  STD_LOGIC;    
	I11:       INOUT  STD_LOGIC;    
	I12:       INOUT  STD_LOGIC;    
	I13:       INOUT  STD_LOGIC;    
	I14:       INOUT  STD_LOGIC;    
	I15:       INOUT  STD_LOGIC;    
	I16:       INOUT  STD_LOGIC;    
	I17:       INOUT  STD_LOGIC;    
	I18:       INOUT  STD_LOGIC;    
	I19:       INOUT  STD_LOGIC;    
	I2:        INOUT  STD_LOGIC;    
	I20:       INOUT  STD_LOGIC;    
	I21:       INOUT  STD_LOGIC;    
	I22:       INOUT  STD_LOGIC;    
	I23:       INOUT  STD_LOGIC;    
	I24:       INOUT  STD_LOGIC;    
	I25:       INOUT  STD_LOGIC;    
	I26:       INOUT  STD_LOGIC;    
	I27:       INOUT  STD_LOGIC;    
	I28:       INOUT  STD_LOGIC;    
	I29:       INOUT  STD_LOGIC;    
	I3:        INOUT  STD_LOGIC;    
	I30:       INOUT  STD_LOGIC;    
	I4:        INOUT  STD_LOGIC;    
	I5:        INOUT  STD_LOGIC;    
	I6:        INOUT  STD_LOGIC;    
	I7:        INOUT  STD_LOGIC;    
	I8:        INOUT  STD_LOGIC;    
	I9:        INOUT  STD_LOGIC);
end idc30;
