// generated by newgenasym  Thu Aug 21 12:39:51 2014


module adp3309 (\err* , gnd, in, out, \sd* );
    inout \err* ;
    input gnd;
    inout in;
    inout out;
    inout \sd* ;


    initial
        begin
        end

endmodule
