-- generated by newgenasym Tue Aug 31 15:23:32 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \hw-07-15-s-d-453-sm-lc\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (7 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (7 DOWNTO 1));
end \hw-07-15-s-d-453-sm-lc\;
