// generated by newgenasym  Thu Dec 22 12:09:51 2011


module \tt4-1a  (pri, \pri#20ct , pri_dot, sec, \sec#20ct , sec_dot);
    inout pri;
    inout \pri#20ct ;
    inout pri_dot;
    inout sec;
    inout \sec#20ct ;
    inout sec_dot;


    initial
        begin
        end

endmodule
