// generated by newgenasym  Tue Dec 15 17:48:42 2009


module max3535 (a, b, de, di, gnd1, gnd2, \re# , ro1, ro2, \slo# , st1, st2, vcc1,
        vcc2, y, z);
    inout a;
    inout b;
    inout de;
    inout di;
    inout gnd1;
    inout gnd2;
    inout \re# ;
    inout ro1;
    inout ro2;
    inout \slo# ;
    inout st1;
    inout st2;
    inout vcc1;
    inout vcc2;
    inout y;
    inout z;


    initial
        begin
        end

endmodule
