-- generated by newgenasym Tue Aug 01 16:38:06 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lqw2ua is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end lqw2ua;
