-- generated by newgenasym Thu May 25 15:50:58 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nup4114hmr6t1g is
    port (    
	GND:       INOUT  STD_LOGIC;    
	IO1:       INOUT  STD_LOGIC;    
	IO2:       INOUT  STD_LOGIC;    
	IO3:       INOUT  STD_LOGIC;    
	IO4:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end nup4114hmr6t1g;
