// generated by newgenasym  Wed Aug 23 13:27:44 2017


module dac37j82 (alarm, amux0, amux1, atest, dacclkn, dacclkp, extio, iforce,
        ioutan, ioutap, ioutbn, ioutbp, ioutcn, ioutcp, ioutdn,
        ioutdp, lpf, rbias, resetb, rx0n, rx0p, rx1n, rx1p, rx2n, rx2p,
        rx3n, rx3p, rx4n, rx4p, rx5n, rx5p, rx6n, rx6p, rx7n, rx7p,
        sclk, sdenb, sdio, sdo, sleep, sync_n_ab, sync_n_cd, syncbn,
        syncbp, sysrefn, sysrefp, tclk, tdi, tdo, testmode, tms,
        trstb, txenable, vsense);
    inout alarm;
    inout amux0;
    inout amux1;
    inout atest;
    inout dacclkn;
    inout dacclkp;
    inout extio;
    inout iforce;
    inout ioutan;
    inout ioutap;
    inout ioutbn;
    inout ioutbp;
    inout ioutcn;
    inout ioutcp;
    inout ioutdn;
    inout ioutdp;
    inout lpf;
    inout rbias;
    inout resetb;
    inout rx0n;
    inout rx0p;
    inout rx1n;
    inout rx1p;
    inout rx2n;
    inout rx2p;
    inout rx3n;
    inout rx3p;
    inout rx4n;
    inout rx4p;
    inout rx5n;
    inout rx5p;
    inout rx6n;
    inout rx6p;
    inout rx7n;
    inout rx7p;
    inout sclk;
    inout sdenb;
    inout sdio;
    inout sdo;
    inout sleep;
    inout sync_n_ab;
    inout sync_n_cd;
    inout syncbn;
    inout syncbp;
    inout sysrefn;
    inout sysrefp;
    inout tclk;
    inout tdi;
    inout tdo;
    inout testmode;
    inout tms;
    inout trstb;
    inout txenable;
    inout vsense;


    initial
        begin
        end

endmodule
