-- generated by newgenasym Wed Jul 02 17:06:45 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74vcg17 is
    port (    
	A:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74vcg17;
