// generated by newgenasym  Mon Oct 13 16:46:24 2003


module \dc/dc_5_10w  (\nor , rc, s_ync, t_rim, toa, \v_in+ , \v_in- , \v_out+ , \v_out- );
    output \nor ;
    input rc;
    input s_ync;
    output t_rim;
    input toa;
    input \v_in+ ;
    input \v_in- ;
    output \v_out+ ;
    output \v_out- ;


    initial
        begin
        end

endmodule
