-- generated by newgenasym Mon Oct 13 16:46:24 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \dc/dc_5_10w\ is
    port (    
	\nor\:     OUT    STD_LOGIC;    
	RC:        IN     STD_LOGIC;    
	S_YNC:     IN     STD_LOGIC;    
	T_RIM:     OUT    STD_LOGIC;    
	TOA:       IN     STD_LOGIC;    
	\v_in+\:   IN     STD_LOGIC;    
	\v_in-\:   IN     STD_LOGIC;    
	\v_out+\:  OUT    STD_LOGIC;    
	\v_out-\:  OUT    STD_LOGIC);
end \dc/dc_5_10w\;
