-- generated by newgenasym Thu Mar 11 14:51:27 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm1117 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     IN     STD_LOGIC);
end lm1117;
