// generated by newgenasym  Thu Jan 10 16:18:33 2008


module pth05010w (r, track, v0, vin);
    inout r;
    inout track;
    inout v0;
    inout vin;


    initial
        begin
        end

endmodule
