-- generated by newgenasym Thu Jan 10 16:18:33 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pth05010w is
    port (    
	R:         INOUT  STD_LOGIC;    
	TRACK:     INOUT  STD_LOGIC;    
	V0:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end pth05010w;
