-- generated by newgenasym Wed Apr 21 13:59:12 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \597_77010202\ is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC);
end \597_77010202\;
