-- generated by newgenasym Wed Nov 25 13:26:14 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity idc24 is
    port (    
	IN1:       INOUT  STD_LOGIC;    
	IN10:      INOUT  STD_LOGIC;    
	IN11:      INOUT  STD_LOGIC;    
	IN12:      INOUT  STD_LOGIC;    
	IN13:      INOUT  STD_LOGIC;    
	IN14:      INOUT  STD_LOGIC;    
	IN15:      INOUT  STD_LOGIC;    
	IN16:      INOUT  STD_LOGIC;    
	IN17:      INOUT  STD_LOGIC;    
	IN18:      INOUT  STD_LOGIC;    
	IN19:      INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN20:      INOUT  STD_LOGIC;    
	IN21:      INOUT  STD_LOGIC;    
	IN22:      INOUT  STD_LOGIC;    
	IN23:      INOUT  STD_LOGIC;    
	IN24:      INOUT  STD_LOGIC;    
	IN25:      INOUT  STD_LOGIC;    
	IN26:      INOUT  STD_LOGIC;    
	IN27:      INOUT  STD_LOGIC;    
	IN28:      INOUT  STD_LOGIC;    
	IN29:      INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	IN30:      INOUT  STD_LOGIC;    
	IN31:      INOUT  STD_LOGIC;    
	IN32:      INOUT  STD_LOGIC;    
	IN4:       INOUT  STD_LOGIC;    
	IN5:       INOUT  STD_LOGIC;    
	IN6:       INOUT  STD_LOGIC;    
	IN7:       INOUT  STD_LOGIC;    
	IN8:       INOUT  STD_LOGIC;    
	IN9:       INOUT  STD_LOGIC);
end idc24;
