// generated by newgenasym  Tue Mar 20 10:31:29 2007


module xcf0xs (\ce* , \ceo* , \cf* , clk, d0, \oe/rst* , tck, tdi, tdo, tms);
    inout \ce* ;
    inout \ceo* ;
    inout \cf* ;
    inout clk;
    inout d0;
    inout \oe/rst* ;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;


    initial
        begin
        end

endmodule
