-- generated by newgenasym Tue Mar 20 10:31:29 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xcf0xs is
    port (    
	\ce*\:     INOUT  STD_LOGIC;    
	\ceo*\:    INOUT  STD_LOGIC;    
	\cf*\:     INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	\oe/rst*\: INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC;    
	TDO:       INOUT  STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC);
end xcf0xs;
