-- generated by newgenasym Wed Jun 02 15:38:03 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g14 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	\y*\:      OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end sn74lvc2g14;
