-- generated by newgenasym Wed Dec 17 10:41:47 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity inductor is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end inductor;
