// generated by newgenasym  Thu Dec 15 10:12:43 2011


module \hm-tr  (config, drx, dtx, enable, gnd, vdd);
    inout config;
    inout drx;
    inout dtx;
    inout enable;
    inout gnd;
    inout vdd;


    initial
        begin
        end

endmodule
