// generated by newgenasym  Mon Jun 26 19:00:52 2006


module at25f1024n (\cs* , gnd, \hold* , sck, si, so, vcc, \wp* );
    input \cs* ;
    input gnd;
    input \hold* ;
    input sck;
    input si;
    output so;
    input vcc;
    input \wp* ;


    initial
        begin
        end

endmodule
