-- generated by newgenasym Wed May 01 19:49:59 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bnx_02 is
    port (    
	B:         INOUT  STD_LOGIC;    
	CB:        INOUT  STD_LOGIC;    
	CG:        INOUT  STD_LOGIC;    
	PSG:       INOUT  STD_LOGIC);
end bnx_02;
