-- generated by newgenasym Wed Aug 15 16:25:44 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tc1_1t is
    port (    
	PRI:       INOUT  STD_LOGIC;    
	\pri dot\: INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	\sec ct\:  INOUT  STD_LOGIC;    
	\sec dot\: INOUT  STD_LOGIC);
end tc1_1t;
