// generated by newgenasym  Fri May 26 13:02:10 2017


module adn4650 (din1n, din1p, din2n, din2p, dout1n, dout1p, dout2n, dout2p,
        vin1, vin2);
    inout din1n;
    inout din1p;
    inout din2n;
    inout din2p;
    inout dout1n;
    inout dout1p;
    inout dout2n;
    inout dout2p;
    inout vin1;
    inout vin2;


    initial
        begin
        end

endmodule
