-- generated by newgenasym Fri May 26 13:02:10 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adn4650 is
    port (    
	DIN1N:     INOUT  STD_LOGIC;    
	DIN1P:     INOUT  STD_LOGIC;    
	DIN2N:     INOUT  STD_LOGIC;    
	DIN2P:     INOUT  STD_LOGIC;    
	DOUT1N:    INOUT  STD_LOGIC;    
	DOUT1P:    INOUT  STD_LOGIC;    
	DOUT2N:    INOUT  STD_LOGIC;    
	DOUT2P:    INOUT  STD_LOGIC;    
	VIN1:      INOUT  STD_LOGIC;    
	VIN2:      INOUT  STD_LOGIC);
end adn4650;
