// generated by newgenasym  Fri Dec 01 14:18:59 2006


module jtag_atmega (\+3.3v , \11 , \15 , \17 , \19 , \e* , ft_s, gnd, s, \spi_1/2 , tck, tdi, tdo,
        tms, trst);
    inout [1:0] \+3.3v ;
    inout \11 ;
    inout \15 ;
    inout \17 ;
    inout \19 ;
    inout \e* ;
    inout ft_s;
    inout [5:1] gnd;
    inout s;
    inout \spi_1/2 ;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout trst;


    initial
        begin
        end

endmodule
