-- generated by newgenasym Fri Dec 01 14:18:59 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jtag_atmega is
    port (    
	\+3.3v\:   INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\11\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\17\:      INOUT  STD_LOGIC;    
	\19\:      INOUT  STD_LOGIC;    
	\e*\:      INOUT  STD_LOGIC;    
	FT_S:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (5 DOWNTO 1);    
	S:         INOUT  STD_LOGIC;    
	\spi_1/2\: INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC;    
	TDO:       INOUT  STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC;    
	TRST:      INOUT  STD_LOGIC);
end jtag_atmega;
