// generated by newgenasym  Tue Mar 16 18:01:05 2010


module idc26 (i1, i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i2, i20,
        i21, i22, i23, i24, i25, i26, i3, i4, i5, i6, i7, i8, i9);
    inout i1;
    inout i10;
    inout i11;
    inout i12;
    inout i13;
    inout i14;
    inout i15;
    inout i16;
    inout i17;
    inout i18;
    inout i19;
    inout i2;
    inout i20;
    inout i21;
    inout i22;
    inout i23;
    inout i24;
    inout i25;
    inout i26;
    inout i3;
    inout i4;
    inout i5;
    inout i6;
    inout i7;
    inout i8;
    inout i9;


    initial
        begin
        end

endmodule
