// generated by newgenasym  Wed Jul 11 17:38:08 2007


module kv (\+ , \- , \2 , \3 , \4 , \5 , \6 , \7 );
    inout \+ ;
    inout \- ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;


    initial
        begin
        end

endmodule
