-- generated by newgenasym Wed Jul 11 17:38:08 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity KV is
    port (    
	\+\:       INOUT  STD_LOGIC;    
	\-\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC);
end KV;
