// generated by newgenasym  Wed Jul 30 14:12:41 2003


module gs8161z36t_133i (a, adv, \ba* , \bb* , \bc* , \bd* , ck, \cke* , dqa, dqb, dqc, dqd, \e1* , e2,
        \e3* , \ft* , \g* , \lbo* , tck, tdi, tdo, tms, \w* , zz);
    input [18:0] a;
    input adv;
    input \ba* ;
    input \bb* ;
    input \bc* ;
    input \bd* ;
    input ck;
    input \cke* ;
    inout [9:1] dqa;
    inout [9:1] dqb;
    inout [9:1] dqc;
    inout [9:1] dqd;
    input \e1* ;
    input e2;
    input \e3* ;
    input \ft* ;
    input \g* ;
    input \lbo* ;
    input tck;
    input tdi;
    input tdo;
    input tms;
    input \w* ;
    input zz;


    initial
        begin
        end

endmodule
