-- generated by newgenasym Tue Dec 15 17:48:42 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3535 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DE:        INOUT  STD_LOGIC;    
	DI:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\re#\:     INOUT  STD_LOGIC;    
	RO1:       INOUT  STD_LOGIC;    
	RO2:       INOUT  STD_LOGIC;    
	\slo#\:    INOUT  STD_LOGIC;    
	ST1:       INOUT  STD_LOGIC;    
	ST2:       INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC;    
	Z:         INOUT  STD_LOGIC);
end max3535;
