// generated by newgenasym  Wed Nov 08 16:18:40 2006


module max3485 (a, b, de, di, \re* , ro);
    inout a;
    inout b;
    inout de;
    inout di;
    inout \re* ;
    inout ro;


    initial
        begin
        end

endmodule
