-- generated by newgenasym Wed Nov 08 16:18:40 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX3485 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DE:        INOUT  STD_LOGIC;    
	DI:        INOUT  STD_LOGIC;    
	\re*\:     INOUT  STD_LOGIC;    
	RO:        INOUT  STD_LOGIC);
end MAX3485;
