// generated by newgenasym  Fri Dec 01 14:55:19 2006


module xp2 (\data1+ , \data1- , \data2+ , \data2- , shield1, shield2);
    inout \data1+ ;
    inout \data1- ;
    inout \data2+ ;
    inout \data2- ;
    inout shield1;
    inout shield2;


    initial
        begin
        end

endmodule
