-- generated by newgenasym Fri Dec 01 14:55:19 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xp2 is
    port (    
	\data1+\:  INOUT  STD_LOGIC;    
	\data1-\:  INOUT  STD_LOGIC;    
	\data2+\:  INOUT  STD_LOGIC;    
	\data2-\:  INOUT  STD_LOGIC;    
	SHIELD1:   INOUT  STD_LOGIC;    
	SHIELD2:   INOUT  STD_LOGIC);
end xp2;
