// generated by newgenasym  Thu Aug 16 10:28:26 2018


module tps2592a (bfet, dvdt, en, ilim);
    inout bfet;
    inout dvdt;
    inout en;
    inout ilim;


    initial
        begin
        end

endmodule
