-- generated by newgenasym Thu Aug 16 12:45:30 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \lcfn-3000\ is
    port (    
	RFIN:      INOUT  STD_LOGIC;    
	RFOUT:     INOUT  STD_LOGIC);
end \lcfn-3000\;
