-- generated by newgenasym Mon Aug 30 20:08:55 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sg8002ca is
    port (    
	CLK:       OUT    STD_LOGIC;    
	OE:        IN     STD_LOGIC);
end sg8002ca;
