-- generated by newgenasym Fri Jul 13 10:25:41 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xp01 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	MISO:      INOUT  STD_LOGIC;    
	MOSI:      INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end xp01;
