-- generated by newgenasym Mon Nov 13 14:07:35 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XP7 is
    port (    
	DQ:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC);
end XP7;
