// generated by newgenasym  Wed Jul 21 15:46:45 2004


module hcpl_063 (ah1, an2, cat1, cat2, gnddm, p3v3m, \v01* , \v02* );
    input ah1;
    input an2;
    input cat1;
    input cat2;
    input gnddm;
    input p3v3m;
    output \v01* ;
    output \v02* ;


    initial
        begin
        end

endmodule
