// generated by newgenasym  Mon Jul 24 18:04:55 2017


module pdi_8p50 (anode, \case , cathode);
    inout anode;
    inout \case ;
    inout cathode;


    initial
        begin
        end

endmodule
