-- generated by newgenasym Tue Jul 01 14:32:02 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3490eesa is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	\ro*\:     IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC;    
	\z*\:      OUT    STD_LOGIC);
end max3490eesa;
