// generated by newgenasym  Sat May 29 16:27:15 2004


module si4465 (d1, d2, d3, d4, g, s1, s2, s3);
    input d1;
    input d2;
    input d3;
    input d4;
    input g;
    output s1;
    output s2;
    output s3;


    initial
        begin
        end

endmodule
