-- generated by newgenasym Sat May 29 16:27:15 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SI4465 is
    port (    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	G:         IN     STD_LOGIC;    
	S1:        OUT    STD_LOGIC;    
	S2:        OUT    STD_LOGIC;    
	S3:        OUT    STD_LOGIC);
end SI4465;
