// generated by newgenasym  Wed Nov 08 10:10:33 2006


module sn74lvc1g126 (a, gnd, \oe* , vcc, y);
    input a;
    input gnd;
    input \oe* ;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
