// generated by newgenasym  Fri Jun 04 16:42:31 2004


module c8051f041tqfp64 (\/rst* , \1xtal , \2xtal , \ain0. , canrx, cantx, dac, \hvain+ ,
        \hvain- , hvcap, hvref, monen, \p0. , \p1. , \p2. , \p3. , tck, tdi, tdo,
        tms, vref, vrefa);
    inout \/rst* ;
    input \1xtal ;
    output \2xtal ;
    input [3:0] \ain0. ;
    input canrx;
    output cantx;
    output [1:0] dac;
    input \hvain+ ;
    input \hvain- ;
    inout hvcap;
    input hvref;
    input monen;
    inout [7:0] \p0. ;
    inout [7:0] \p1. ;
    inout [7:0] \p2. ;
    inout [7:0] \p3. ;
    input tck;
    input tdi;
    output tdo;
    input tms;
    inout vref;
    input vrefa;


    initial
        begin
        end

endmodule
