-- generated by newgenasym Fri Jun 04 16:42:31 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c8051f041tqfp64 is
    port (    
	\/rst*\:   INOUT  STD_LOGIC;    
	\1xtal\:   IN     STD_LOGIC;    
	\2xtal\:   OUT    STD_LOGIC;    
	\ain0.\:   IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	CANRX:     IN     STD_LOGIC;    
	CANTX:     OUT    STD_LOGIC;    
	DAC:       OUT    STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\hvain+\:  IN     STD_LOGIC;    
	\hvain-\:  IN     STD_LOGIC;    
	HVCAP:     INOUT  STD_LOGIC;    
	HVREF:     IN     STD_LOGIC;    
	MONEN:     IN     STD_LOGIC;    
	\p0.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p1.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p2.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p3.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       IN     STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VREFA:     IN     STD_LOGIC);
end c8051f041tqfp64;
