// generated by newgenasym  Fri Dec 11 12:52:45 2009


module mt48lc32m16a2p (a0, a1, a10, a11, \a12/nc , a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1,
        \cas# , cke, clk, \cs# , dq0, dq1, dq10, dq11, dq12, dq13, dq14,
        dq15, dq2, dq3, dq4, dq5, dq6, dq7, dq8, dq9, dqmh, dqml, \ras# ,
        \we# );
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout \a12/nc ;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout \cas# ;
    inout cke;
    inout clk;
    inout \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout dqmh;
    inout dqml;
    inout \ras# ;
    inout \we# ;


    initial
        begin
        end

endmodule
