// generated by newgenasym  Mon Nov 16 10:13:11 2009


module ad8610 (\+in , \-in , nc, null, null2, out, \v+ , \v- );
    inout \+in ;
    inout \-in ;
    inout nc;
    inout null;
    inout null2;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
