-- generated by newgenasym Wed Dec 13 16:03:00 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity b560 is
    port (    
	ANOD:      INOUT  STD_LOGIC;    
	KATOD:     INOUT  STD_LOGIC);
end b560;
