// generated by newgenasym  Tue Dec 19 16:23:39 2017


module \etc1-1-13v5  (\1 , \3 , \4 , \5 );
    inout \1 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
