// generated by newgenasym  Thu Mar 17 16:21:56 2005


module rg_leds (\1 , \2 , \3 , \4 );
    output \1 ;
    input \2 ;
    output \3 ;
    input \4 ;


    initial
        begin
        end

endmodule
