// generated by newgenasym  Mon Nov 28 17:41:03 2016


module sn74lvc1g32 (a, b, gnddm, p3v3m, y);
    input a;
    input b;
    inout gnddm;
    inout p3v3m;
    output y;


    initial
        begin
        end

endmodule
