-- generated by newgenasym Mon Nov 28 17:41:03 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g32 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GNDDM:     INOUT  STD_LOGIC;    
	P3V3M:     INOUT  STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc1g32;
