// generated by newgenasym  Tue Dec 15 11:36:05 2009


module at45db161d (\cs# , gnd, \reset# , sck, si, so, vcc, \wp# );
    inout \cs# ;
    inout gnd;
    inout \reset# ;
    inout sck;
    inout si;
    inout so;
    inout vcc;
    inout \wp# ;


    initial
        begin
        end

endmodule
