-- generated by newgenasym Tue Dec 15 11:36:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity at45db161d is
    port (    
	\cs#\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\reset#\:  INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SI:        INOUT  STD_LOGIC;    
	SO:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	\wp#\:     INOUT  STD_LOGIC);
end at45db161d;
