// generated by newgenasym  Tue Jun 01 11:56:07 2004


module sn74lvc1g08 (a, b, gnddm, p3v3m, y);
    input a;
    input b;
    inout gnddm;
    inout p3v3m;
    output y;


    initial
        begin
        end

endmodule
