-- generated by newgenasym Fri Dec 15 16:15:49 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tc-0103\ is
    port (    
	KT1:       INOUT  STD_LOGIC;    
	KT2:       INOUT  STD_LOGIC);
end \tc-0103\;
