// generated by newgenasym  Tue Apr 19 17:18:56 2016


module idt8v44n003i (lock, n_ref, n_ref_out, nq, p_ref, p_ref_out, pq, reserv,
        sclk, sdata, vpp);
    inout lock;
    inout n_ref;
    inout n_ref_out;
    inout nq;
    inout p_ref;
    inout p_ref_out;
    inout pq;
    inout reserv;
    inout sclk;
    inout sdata;
    inout vpp;


    initial
        begin
        end

endmodule
