// generated by newgenasym  Tue Aug 25 18:58:45 2020


module zigbee_cc2530 (p0_0, p0_1, p0_2, p0_3, p0_4, p0_5, p0_6, p0_7, p1_0, p1_1,
        p1_2, p1_3, p1_4, p1_5, p1_6, p1_7, p2_0, p2_1, p2_2, reset);
    inout p0_0;
    inout p0_1;
    inout p0_2;
    inout p0_3;
    inout p0_4;
    inout p0_5;
    inout p0_6;
    inout p0_7;
    inout p1_0;
    inout p1_1;
    inout p1_2;
    inout p1_3;
    inout p1_4;
    inout p1_5;
    inout p1_6;
    inout p1_7;
    inout p2_0;
    inout p2_1;
    inout p2_2;
    inout reset;


    initial
        begin
        end

endmodule
