-- generated by newgenasym Tue Aug 25 18:58:45 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity zigbee_cc2530 is
    port (    
	P0_0:      INOUT  STD_LOGIC;    
	P0_1:      INOUT  STD_LOGIC;    
	P0_2:      INOUT  STD_LOGIC;    
	P0_3:      INOUT  STD_LOGIC;    
	P0_4:      INOUT  STD_LOGIC;    
	P0_5:      INOUT  STD_LOGIC;    
	P0_6:      INOUT  STD_LOGIC;    
	P0_7:      INOUT  STD_LOGIC;    
	P1_0:      INOUT  STD_LOGIC;    
	P1_1:      INOUT  STD_LOGIC;    
	P1_2:      INOUT  STD_LOGIC;    
	P1_3:      INOUT  STD_LOGIC;    
	P1_4:      INOUT  STD_LOGIC;    
	P1_5:      INOUT  STD_LOGIC;    
	P1_6:      INOUT  STD_LOGIC;    
	P1_7:      INOUT  STD_LOGIC;    
	P2_0:      INOUT  STD_LOGIC;    
	P2_1:      INOUT  STD_LOGIC;    
	P2_2:      INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC);
end zigbee_cc2530;
