// generated by newgenasym  Mon Jul 26 11:50:35 2004


module fis_10_7 (gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, in, out);
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input in;
    output out;


    initial
        begin
        end

endmodule
