-- generated by newgenasym Fri Dec 23 15:15:40 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tes5wi is
    port (    
	\+vin1\:   INOUT  STD_LOGIC;    
	\+vin2\:   INOUT  STD_LOGIC;    
	\+vout\:   INOUT  STD_LOGIC;    
	\-vin1\:   INOUT  STD_LOGIC;    
	\-vin2\:   INOUT  STD_LOGIC;    
	\-vout\:   INOUT  STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC);
end tes5wi;
