-- generated by newgenasym Wed Aug 15 17:32:57 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adf4108_v2 is
    port (    
	AGND1:     INOUT  STD_LOGIC;    
	AGND2:     INOUT  STD_LOGIC;    
	AGND3:     INOUT  STD_LOGIC;    
	AVDD1:     INOUT  STD_LOGIC;    
	AVDD2:     INOUT  STD_LOGIC;    
	CE:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CP:        INOUT  STD_LOGIC;    
	CPGND:     INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	DGND1:     INOUT  STD_LOGIC;    
	DGND2:     INOUT  STD_LOGIC;    
	DVDD1:     INOUT  STD_LOGIC;    
	DVDD2:     INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	MUXOUT:    INOUT  STD_LOGIC;    
	REF_IN:    INOUT  STD_LOGIC;    
	RFIN_A:    INOUT  STD_LOGIC;    
	RFIN_B:    INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	VP:        INOUT  STD_LOGIC);
end adf4108_v2;
