-- generated by newgenasym Wed Feb 07 14:13:32 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gs8161z36 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (20 DOWNTO 0);    
	ADV:       IN     STD_LOGIC;    
	\be*\:     IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	CK:        IN     STD_LOGIC;    
	\cke*\:    IN     STD_LOGIC;    
	D:         INOUT  STD_LOGIC_VECTOR (35 DOWNTO 0);    
	\e1*\:     IN     STD_LOGIC;    
	E2:        IN     STD_LOGIC;    
	\e3*\:     IN     STD_LOGIC;    
	\ft*\:     IN     STD_LOGIC;    
	\lbo*\:    IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	\we*\:     IN     STD_LOGIC;    
	ZZ:        IN     STD_LOGIC);
end gs8161z36;
