-- generated by newgenasym Wed Aug 26 11:56:53 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pld_4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end pld_4;
