-- generated by newgenasym Thu Oct 09 12:18:59 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g07 is
    port (    
	A:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc2g07;
