// generated by newgenasym  Mon Jul 26 14:55:51 2004


module max9126 (en, \en* , rin1, \rin1* , rin2, \rin2* , rin3, \rin3* , rin4, \rin4* ,
        rout1, rout2, rout3, rout4);
    input en;
    input \en* ;
    input rin1;
    input \rin1* ;
    input rin2;
    input \rin2* ;
    input rin3;
    input \rin3* ;
    input rin4;
    input \rin4* ;
    output rout1;
    output rout2;
    output rout3;
    output rout4;


    initial
        begin
        end

endmodule
