-- generated by newgenasym Mon Jul 26 14:55:51 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9126 is
    port (    
	EN:        IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	RIN1:      IN     STD_LOGIC;    
	\rin1*\:   IN     STD_LOGIC;    
	RIN2:      IN     STD_LOGIC;    
	\rin2*\:   IN     STD_LOGIC;    
	RIN3:      IN     STD_LOGIC;    
	\rin3*\:   IN     STD_LOGIC;    
	RIN4:      IN     STD_LOGIC;    
	\rin4*\:   IN     STD_LOGIC;    
	ROUT1:     OUT    STD_LOGIC;    
	ROUT2:     OUT    STD_LOGIC;    
	ROUT3:     OUT    STD_LOGIC;    
	ROUT4:     OUT    STD_LOGIC);
end max9126;
