// generated by newgenasym  Mon Sep 04 15:05:09 2017


module adl5802 (enbl, loin, loip, \op1+ , \op1- , \op2+ , \op2- , \rf1+ , \rf1- , \rf2+ ,
        \rf2- , vset);
    inout enbl;
    inout loin;
    inout loip;
    inout \op1+ ;
    inout \op1- ;
    inout \op2+ ;
    inout \op2- ;
    inout \rf1+ ;
    inout \rf1- ;
    inout \rf2+ ;
    inout \rf2- ;
    inout vset;


    initial
        begin
        end

endmodule
