-- generated by newgenasym Mon Sep 04 15:05:09 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5802 is
    port (    
	ENBL:      INOUT  STD_LOGIC;    
	LOIN:      INOUT  STD_LOGIC;    
	LOIP:      INOUT  STD_LOGIC;    
	\op1+\:    INOUT  STD_LOGIC;    
	\op1-\:    INOUT  STD_LOGIC;    
	\op2+\:    INOUT  STD_LOGIC;    
	\op2-\:    INOUT  STD_LOGIC;    
	\rf1+\:    INOUT  STD_LOGIC;    
	\rf1-\:    INOUT  STD_LOGIC;    
	\rf2+\:    INOUT  STD_LOGIC;    
	\rf2-\:    INOUT  STD_LOGIC;    
	VSET:      INOUT  STD_LOGIC);
end adl5802;
