-- generated by newgenasym Fri Aug 17 11:46:38 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bpf-c70\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \bpf-c70\;
