// generated by newgenasym  Wed Jul 07 10:40:39 2004


module sn74hc138 (a, b, c, g1, \g2a* , \g2b* , gndd, p5v0, y);
    input a;
    input b;
    input c;
    input g1;
    input \g2a* ;
    input \g2b* ;
    input gndd;
    input p5v0;
    output [7:0] y;


    initial
        begin
        end

endmodule
