-- generated by newgenasym Wed Jul 07 10:40:39 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74hc138 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	C:         IN     STD_LOGIC;    
	G1:        IN     STD_LOGIC;    
	\g2a*\:    IN     STD_LOGIC;    
	\g2b*\:    IN     STD_LOGIC;    
	GNDD:      IN     STD_LOGIC;    
	P5V0:      IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0));
end sn74hc138;
