-- generated by newgenasym Tue Nov 27 18:12:11 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds1820 is
    port (    
	DQ:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end ds1820;
