// generated by newgenasym  Mon Aug 30 20:25:02 2004


module \93lc66c  (cs, di, do, org, sk);
    input cs;
    input di;
    output do;
    input org;
    input sk;


    initial
        begin
        end

endmodule
