-- generated by newgenasym Mon Aug 30 20:25:02 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \93lc66c\ is
    port (    
	CS:        IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	DO:        OUT    STD_LOGIC;    
	ORG:       IN     STD_LOGIC;    
	SK:        IN     STD_LOGIC);
end \93lc66c\;
