// generated by newgenasym  Tue Jul 13 16:34:00 2004


module \adp-2-4  (gnd, isolate1, isolate2, port1, port2, sum);
    input gnd;
    input isolate1;
    input isolate2;
    inout port1;
    inout port2;
    inout sum;


    initial
        begin
        end

endmodule
