-- generated by newgenasym Tue Jul 13 16:34:00 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \adp-2-4\ is
    port (    
	GND:       IN     STD_LOGIC;    
	ISOLATE1:  IN     STD_LOGIC;    
	ISOLATE2:  IN     STD_LOGIC;    
	PORT1:     INOUT  STD_LOGIC;    
	PORT2:     INOUT  STD_LOGIC;    
	SUM:       INOUT  STD_LOGIC);
end \adp-2-4\;
