// generated by newgenasym  Tue Jun 08 17:16:41 2010


module \ltc1569-7  (\div/clk , gnd, \in+ , \in- , out, rx, \v+ , \v- );
    inout \div/clk ;
    inout gnd;
    inout \in+ ;
    inout \in- ;
    inout out;
    inout rx;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
