// generated by newgenasym  Thu Feb 02 06:35:17 2017


module stm32f030k6 (boot0, nrst, pa0, pa1, pa10_usart1_rx, pa11_usart1_cts,
        pa12_usart1_rts, pa13_swdio, pa14_swclk, pa15_spi1_nss,
        pa2_usart1_tx, pa3_usart1_rx, pa4_spi1_nss, pa5_spi1_sck,
        pa6_spi1_miso, pa7_spi1_mosi, pa8_usart1_ck,
        pa9_usart1_tx, pb0_tim3_ch3, pb1_tim3_ch4, pb3_spi1_sck,
        pb4_spi1_miso, pb5_spi1_mosi, pb6_i2c1_scl, pb7_i2c1_sda,
        pf0_oscin, pf1_oscout);
    inout boot0;
    inout nrst;
    inout pa0;
    inout pa1;
    inout pa10_usart1_rx;
    inout pa11_usart1_cts;
    inout pa12_usart1_rts;
    inout pa13_swdio;
    inout pa14_swclk;
    inout pa15_spi1_nss;
    inout pa2_usart1_tx;
    inout pa3_usart1_rx;
    inout pa4_spi1_nss;
    inout pa5_spi1_sck;
    inout pa6_spi1_miso;
    inout pa7_spi1_mosi;
    inout pa8_usart1_ck;
    inout pa9_usart1_tx;
    inout pb0_tim3_ch3;
    inout pb1_tim3_ch4;
    inout pb3_spi1_sck;
    inout pb4_spi1_miso;
    inout pb5_spi1_mosi;
    inout pb6_i2c1_scl;
    inout pb7_i2c1_sda;
    inout pf0_oscin;
    inout pf1_oscout;


    initial
        begin
        end

endmodule
