// generated by newgenasym  Tue May 17 15:07:27 2005


module sn74lvc2g14 (a, b, gndd, p3v3, \y1* , \y2* );
    input a;
    input b;
    input gndd;
    input p3v3;
    output \y1* ;
    output \y2* ;


    initial
        begin
        end

endmodule
