// generated by newgenasym  Tue Jul 01 15:26:03 2003


module max6831tz (\mr* , \reset* , wdi);
    input \mr* ;
    output \reset* ;
    input wdi;


    initial
        begin
        end

endmodule
