-- generated by newgenasym Tue Jul 01 15:26:03 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max6831tz is
    port (    
	\mr*\:     IN     STD_LOGIC;    
	\reset*\:  OUT    STD_LOGIC;    
	WDI:       IN     STD_LOGIC);
end max6831tz;
