// generated by newgenasym  Mon Jul 24 16:51:31 2017


module mic5205 (adj, en, gnd, in, out);
    inout adj;
    inout en;
    inout gnd;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
