-- generated by newgenasym Mon Jul 24 16:51:31 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mic5205 is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end mic5205;
