// generated by newgenasym  Thu Jul 26 14:25:50 2007


module \mna-6  (dc, gnd1, gnd2, gnd3, optin, optout, rfin, rfout, vs);
    inout dc;
    input gnd1;
    input gnd2;
    input gnd3;
    inout optin;
    inout optout;
    inout rfin;
    inout rfout;
    inout vs;


    initial
        begin
        end

endmodule
