-- generated by newgenasym Thu Jul 26 14:25:50 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \mna-6\ is
    port (    
	DC:        INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	OPTIN:     INOUT  STD_LOGIC;    
	OPTOUT:    INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	RFOUT:     INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end \mna-6\;
