// generated by newgenasym  Wed Aug 20 10:14:33 2014


module cdclvp1204 (in_sel, inn0, inn1, inp0, inp1, outn0, outn1, outn2, outn3,
        outp0, outp1, outp2, outp3, vac_ref);
    inout in_sel;
    inout inn0;
    inout inn1;
    inout inp0;
    inout inp1;
    inout outn0;
    inout outn1;
    inout outn2;
    inout outn3;
    inout outp0;
    inout outp1;
    inout outp2;
    inout outp3;
    inout vac_ref;


    initial
        begin
        end

endmodule
