-- generated by newgenasym Wed Aug 20 10:14:33 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cdclvp1204 is
    port (    
	IN_SEL:    INOUT  STD_LOGIC;    
	INN0:      INOUT  STD_LOGIC;    
	INN1:      INOUT  STD_LOGIC;    
	INP0:      INOUT  STD_LOGIC;    
	INP1:      INOUT  STD_LOGIC;    
	OUTN0:     INOUT  STD_LOGIC;    
	OUTN1:     INOUT  STD_LOGIC;    
	OUTN2:     INOUT  STD_LOGIC;    
	OUTN3:     INOUT  STD_LOGIC;    
	OUTP0:     INOUT  STD_LOGIC;    
	OUTP1:     INOUT  STD_LOGIC;    
	OUTP2:     INOUT  STD_LOGIC;    
	OUTP3:     INOUT  STD_LOGIC;    
	VAC_REF:   INOUT  STD_LOGIC);
end cdclvp1204;
