// generated by newgenasym  Tue Nov 21 17:49:07 2006


module test_raz (a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;


    initial
        begin
        end

endmodule
