// generated by newgenasym  Tue Dec 07 15:36:48 2004


module \3_1_6j  (pri, pri_dot, sec, sec_dot);
    inout pri;
    inout pri_dot;
    inout sec;
    inout sec_dot;


    initial
        begin
        end

endmodule
