// generated by newgenasym  Fri Apr 28 11:07:18 2017


module n25q256mb_16lead (c, dq0, dq1, dq2, dq3, \s# );
    inout c;
    inout dq0;
    inout dq1;
    inout dq2;
    inout dq3;
    inout \s# ;


    initial
        begin
        end

endmodule
