// generated by newgenasym  Wed Oct 31 12:46:14 2018


module tpd4s012 (\d+ , \d- , gnd, id, vbus);
    inout \d+ ;
    inout \d- ;
    input gnd;
    inout id;
    inout vbus;


    initial
        begin
        end

endmodule
