-- generated by newgenasym Wed Oct 31 12:46:14 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpd4s012 is
    port (    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC);
end tpd4s012;
