// generated by newgenasym  Tue Feb 12 13:50:51 2008


module xcf16pv048c (busy, ce, ceo, cf, clk, clkout, d, d0, en_ext_sel, \oe/rst ,
        rev_sel0, rev_sel1, tck, td0, tdi, tms);
    inout busy;
    inout ce;
    inout ceo;
    inout cf;
    inout clk;
    inout clkout;
    inout [7:1] d;
    inout d0;
    inout en_ext_sel;
    inout \oe/rst ;
    inout rev_sel0;
    inout rev_sel1;
    inout tck;
    inout td0;
    inout tdi;
    inout tms;


    initial
        begin
        end

endmodule
