-- generated by newgenasym Tue Feb 12 13:50:51 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xcf16pv048c is
    port (    
	BUSY:      INOUT  STD_LOGIC;    
	CE:        INOUT  STD_LOGIC;    
	CEO:       INOUT  STD_LOGIC;    
	CF:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CLKOUT:    INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC_VECTOR (7 DOWNTO 1);    
	D0:        INOUT  STD_LOGIC;    
	EN_EXT_SEL: INOUT  STD_LOGIC;    
	\oe/rst\:  INOUT  STD_LOGIC;    
	REV_SEL0:  INOUT  STD_LOGIC;    
	REV_SEL1:  INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TD0:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC);
end xcf16pv048c;
