// generated by newgenasym  Wed Jul 30 11:10:43 2003


module aha4540a_086pqc (cacpt, cclk, cdata, clsb, crdy, cstart, dacpt, dclk, dclkadj,
        ddata, dend, derr, dpclk, drdy, dstart, eacpt, eclk, edata,
        eend, epclk, erdy, estart, gout, ma, male, mcsn, mdata, mintn,
        mrdn_dsn, mrdy_dtackn, muxmode, mwrn_rwn, procmode, resetn,
        rotate, testi, testo, tristaten, uacpt, uclk, uclkadj, udata,
        urdy);
    output cacpt;
    input cclk;
    input [15:0] cdata;
    input clsb;
    input crdy;
    input cstart;
    input dacpt;
    input dclk;
    output [2:0] dclkadj;
    output [7:0] ddata;
    output dend;
    output derr;
    input dpclk;
    output drdy;
    output dstart;
    input eacpt;
    input eclk;
    output [7:0] edata;
    output eend;
    input epclk;
    output erdy;
    output estart;
    output [1:0] gout;
    input [6:0] ma;
    input male;
    input mcsn;
    inout [7:0] mdata;
    output mintn;
    input mrdn_dsn;
    output mrdy_dtackn;
    input muxmode;
    input mwrn_rwn;
    input procmode;
    input resetn;
    output rotate;
    input [6:0] testi;
    output [2:0] testo;
    input tristaten;
    output uacpt;
    input uclk;
    output [2:0] uclkadj;
    input [7:0] udata;
    input urdy;


    initial
        begin
        end

endmodule
