// generated by newgenasym  Fri Aug 17 12:35:37 2018


module \cpa-0501-510hds  (coupled, \input , \output , terminated);
    inout coupled;
    inout \input ;
    inout \output ;
    inout terminated;


    initial
        begin
        end

endmodule
