// generated by newgenasym  Thu Mar 15 10:44:37 2018


module \1469tk025  (alarm, caplp, capwd, compare, control, gate, ipwoff, \sens- ,
        vcc, vdd, wden, wdi, wdst);
    inout alarm;
    inout caplp;
    inout capwd;
    inout compare;
    inout control;
    inout gate;
    inout ipwoff;
    inout \sens- ;
    input vcc;
    input vdd;
    inout wden;
    inout wdi;
    inout wdst;


    initial
        begin
        end

endmodule
