// generated by newgenasym  Wed Dec 17 10:13:41 2003


module tps5461x (agnd, boot, fsel, pgnd, ph, pwrgd, pwrpad, rt, ss_ena, vbias,
        vin, vsense);
    input agnd;
    input boot;
    input fsel;
    inout [5:1] pgnd;
    inout [9:1] ph;
    output pwrgd;
    input pwrpad;
    input rt;
    output ss_ena;
    inout vbias;
    inout [5:1] vin;
    input vsense;


    initial
        begin
        end

endmodule
