// generated by newgenasym  Thu May 17 11:16:54 2007


module hmc451lc3 (gnd, rfin, rfout, vdd1, vdd2);
    input gnd;
    inout rfin;
    inout rfout;
    input vdd1;
    input vdd2;


    initial
        begin
        end

endmodule
