-- generated by newgenasym Thu May 17 11:16:54 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HMC451LC3 is
    port (    
	GND:       IN     STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	RFOUT:     INOUT  STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC);
end HMC451LC3;
