// generated by newgenasym  Mon Oct 13 16:44:57 2003


module bc847 (b1, b2, c1, c2, e1, e2);
    inout b1;
    inout b2;
    inout c1;
    inout c2;
    inout e1;
    inout e2;


    initial
        begin
        end

endmodule
