-- generated by newgenasym Mon Oct 13 16:44:57 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bc847 is
    port (    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	E1:        INOUT  STD_LOGIC;    
	E2:        INOUT  STD_LOGIC);
end bc847;
