// generated by newgenasym  Tue Apr 02 11:44:28 2013


module adm6320 (gnd, mr, reset, vcc, wdi);
    input gnd;
    input mr;
    output reset;
    input vcc;
    input wdi;


    initial
        begin
        end

endmodule
