-- generated by newgenasym Tue Apr 02 11:44:28 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm6320 is
    port (    
	GND:       IN     STD_LOGIC;    
	MR:        IN     STD_LOGIC;    
	RESET:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WDI:       IN     STD_LOGIC);
end adm6320;
