-- generated by newgenasym Thu Aug 30 17:58:25 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad9514 is
    port (    
	CLK:       IN     STD_LOGIC;    
	CLKB:      IN     STD_LOGIC;    
	OUT0:      OUT    STD_LOGIC;    
	OUT0B:     OUT    STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT1B:     OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	OUT2B:     OUT    STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	S0:        IN     STD_LOGIC;    
	S1:        IN     STD_LOGIC;    
	S10:       IN     STD_LOGIC;    
	S2:        IN     STD_LOGIC;    
	S3:        IN     STD_LOGIC;    
	S4:        IN     STD_LOGIC;    
	S5:        IN     STD_LOGIC;    
	S6:        IN     STD_LOGIC;    
	S7:        IN     STD_LOGIC;    
	S8:        IN     STD_LOGIC;    
	S9:        IN     STD_LOGIC;    
	SYNCB:     IN     STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ad9514;
