// generated by newgenasym  Wed Mar 30 17:19:10 2005


module \ltc4300-2  (acc, sclin, sclout, sdain, sdaout, vcc1, vcc2);
    inout acc;
    inout sclin;
    inout sclout;
    inout sdain;
    inout sdaout;
    inout vcc1;
    inout vcc2;


    initial
        begin
        end

endmodule
