-- generated by newgenasym Wed Mar 30 17:19:10 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ltc4300-2\ is
    port (    
	ACC:       INOUT  STD_LOGIC;    
	SCLIN:     INOUT  STD_LOGIC;    
	SCLOUT:    INOUT  STD_LOGIC;    
	SDAIN:     INOUT  STD_LOGIC;    
	SDAOUT:    INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC);
end \ltc4300-2\;
