-- generated by newgenasym Mon Jul 17 19:22:15 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PAC4_RES is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end PAC4_RES;
