// generated by newgenasym  Fri Aug 17 15:05:17 2012


module tps51200 (en, gnd, pgnd, pgood, pwrpad, refin, refout, vin, vldoin, vo,
        vosns);
    inout en;
    inout gnd;
    inout pgnd;
    inout pgood;
    input pwrpad;
    inout refin;
    inout refout;
    inout vin;
    inout vldoin;
    inout vo;
    inout vosns;


    initial
        begin
        end

endmodule
