// generated by newgenasym  Tue Sep 05 17:24:09 2017


module adm8829 (\cap+ , \cap- , gnd, in, out);
    inout \cap+ ;
    inout \cap- ;
    input gnd;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
