-- generated by newgenasym Sun Aug 01 19:08:05 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fin1001 is
    port (    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	\dout*\:   OUT    STD_LOGIC);
end fin1001;
