-- generated by newgenasym Wed May 23 17:06:17 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \69001_816\ is
    port (    
	\+12b\:    INOUT  STD_LOGIC;    
	\+12b1\:   INOUT  STD_LOGIC;    
	\+12bk\:   INOUT  STD_LOGIC;    
	\+12bk1\:  INOUT  STD_LOGIC;    
	\+27b\:    INOUT  STD_LOGIC;    
	\+27b1\:   INOUT  STD_LOGIC;    
	\-27b\:    INOUT  STD_LOGIC;    
	\-27b1\:   INOUT  STD_LOGIC;    
	ADC0:      INOUT  STD_LOGIC;    
	ADC1:      INOUT  STD_LOGIC;    
	ADC2:      INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	\int*\:    INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end \69001_816\;
