-- generated by newgenasym Wed Oct 15 17:22:50 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max6354syuk_t is
    port (    
	\mr*\:     IN     STD_LOGIC;    
	\rst*\:    OUT    STD_LOGIC);
end max6354syuk_t;
