-- generated by newgenasym Fri Feb 13 15:32:59 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hswa2_30dr is
    port (    
	\con 1\:   INOUT  STD_LOGIC;    
	\con 2\:   INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND10:     IN     STD_LOGIC;    
	GND11:     IN     STD_LOGIC;    
	GND12:     IN     STD_LOGIC;    
	GND13:     IN     STD_LOGIC;    
	GND14:     IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	GND5:      IN     STD_LOGIC;    
	GND6:      IN     STD_LOGIC;    
	GND7:      IN     STD_LOGIC;    
	GND8:      IN     STD_LOGIC;    
	GND9:      IN     STD_LOGIC;    
	PADDLE:    IN     STD_LOGIC;    
	\rf com\:  INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end hswa2_30dr;
