// generated by newgenasym  Tue Aug 19 16:11:33 2014


module adclk954 (clk0_p, clk0n, clk1_p, clk1n, in_sel, q0_p, q0n, q10_p, q10n,
        q11_p, q11n, q1_p, q1n, q2_p, q2n, q3_p, q3n, q4_p, q4n, q5_p,
        q5n, q6_p, q6n, q7_p, q7n, q8_p, q8n, q9_p, q9n, vref0, vref1,
        vt0, vt1);
    inout clk0_p;
    inout clk0n;
    inout clk1_p;
    inout clk1n;
    inout in_sel;
    inout q0_p;
    inout q0n;
    inout q10_p;
    inout q10n;
    inout q11_p;
    inout q11n;
    inout q1_p;
    inout q1n;
    inout q2_p;
    inout q2n;
    inout q3_p;
    inout q3n;
    inout q4_p;
    inout q4n;
    inout q5_p;
    inout q5n;
    inout q6_p;
    inout q6n;
    inout q7_p;
    inout q7n;
    inout q8_p;
    inout q8n;
    inout q9_p;
    inout q9n;
    inout vref0;
    inout vref1;
    inout vt0;
    inout vt1;


    initial
        begin
        end

endmodule
