-- generated by newgenasym Tue Aug 19 16:11:33 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adclk954 is
    port (    
	CLK0_P:    INOUT  STD_LOGIC;    
	CLK0N:     INOUT  STD_LOGIC;    
	CLK1_P:    INOUT  STD_LOGIC;    
	CLK1N:     INOUT  STD_LOGIC;    
	IN_SEL:    INOUT  STD_LOGIC;    
	Q0_P:      INOUT  STD_LOGIC;    
	Q0N:       INOUT  STD_LOGIC;    
	Q10_P:     INOUT  STD_LOGIC;    
	Q10N:      INOUT  STD_LOGIC;    
	Q11_P:     INOUT  STD_LOGIC;    
	Q11N:      INOUT  STD_LOGIC;    
	Q1_P:      INOUT  STD_LOGIC;    
	Q1N:       INOUT  STD_LOGIC;    
	Q2_P:      INOUT  STD_LOGIC;    
	Q2N:       INOUT  STD_LOGIC;    
	Q3_P:      INOUT  STD_LOGIC;    
	Q3N:       INOUT  STD_LOGIC;    
	Q4_P:      INOUT  STD_LOGIC;    
	Q4N:       INOUT  STD_LOGIC;    
	Q5_P:      INOUT  STD_LOGIC;    
	Q5N:       INOUT  STD_LOGIC;    
	Q6_P:      INOUT  STD_LOGIC;    
	Q6N:       INOUT  STD_LOGIC;    
	Q7_P:      INOUT  STD_LOGIC;    
	Q7N:       INOUT  STD_LOGIC;    
	Q8_P:      INOUT  STD_LOGIC;    
	Q8N:       INOUT  STD_LOGIC;    
	Q9_P:      INOUT  STD_LOGIC;    
	Q9N:       INOUT  STD_LOGIC;    
	VREF0:     INOUT  STD_LOGIC;    
	VREF1:     INOUT  STD_LOGIC;    
	VT0:       INOUT  STD_LOGIC;    
	VT1:       INOUT  STD_LOGIC);
end adclk954;
