// generated by newgenasym  Thu Jul 06 10:53:07 2017


module ds4520 (a0, a1, a2, io0, io1, io2, io3, io4, io5, io6, io7, io8, scl, sda);
    inout a0;
    inout a1;
    inout a2;
    inout io0;
    inout io1;
    inout io2;
    inout io3;
    inout io4;
    inout io5;
    inout io6;
    inout io7;
    inout io8;
    inout scl;
    inout sda;


    initial
        begin
        end

endmodule
