// generated by newgenasym  Tue Dec 15 10:49:54 2009


module ds1339 (gnd, scl, sda, \sqw/int , vbac, vcc, x1, x2);
    inout gnd;
    inout scl;
    inout sda;
    inout \sqw/int ;
    inout vbac;
    inout vcc;
    inout x1;
    inout x2;


    initial
        begin
        end

endmodule
