-- generated by newgenasym Thu Mar 11 16:54:51 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \142en8b\ is
    port (    
	A:         IN     STD_LOGIC;    
	X:         OUT    STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \142en8b\;
