// generated by newgenasym  Wed Mar 10 10:13:20 2004


module h11a817 (an, cat, col, em);
    input an;
    input cat;
    output col;
    output em;


    initial
        begin
        end

endmodule
