-- generated by newgenasym Wed Oct 31 15:15:44 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8061 is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\+vs\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\-vs\:     IN     STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end ad8061;
