// generated by newgenasym  Mon Jan 11 10:37:32 2010


module r1rw0416dsb (a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6,
        a7, a8, a9, \cs# , \i/o1 , \i/o10 , \i/o11 , \i/o12 , \i/o13 , \i/o14 , \i/o15 ,
        \i/o16 , \i/o2 , \i/o3 , \i/o4 , \i/o5 , \i/o6 , \i/o7 , \i/o8 , \i/o9 , \lb# , nc,
        \oe# , \ub# , vcc, vcc2, vss, vss2, \we# );
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout \cs# ;
    inout \i/o1 ;
    inout \i/o10 ;
    inout \i/o11 ;
    inout \i/o12 ;
    inout \i/o13 ;
    inout \i/o14 ;
    inout \i/o15 ;
    inout \i/o16 ;
    inout \i/o2 ;
    inout \i/o3 ;
    inout \i/o4 ;
    inout \i/o5 ;
    inout \i/o6 ;
    inout \i/o7 ;
    inout \i/o8 ;
    inout \i/o9 ;
    inout \lb# ;
    inout nc;
    inout \oe# ;
    inout \ub# ;
    inout vcc;
    inout vcc2;
    inout vss;
    inout vss2;
    inout \we# ;


    initial
        begin
        end

endmodule
