// generated by newgenasym  Fri Jun 06 16:19:58 2008


module bmp15_1 (\in+ , \in- , off, \out+ , \out- );
    input \in+ ;
    input \in- ;
    input off;
    output \out+ ;
    output \out- ;


    initial
        begin
        end

endmodule
