-- generated by newgenasym Tue Jan 10 14:45:12 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bpf-a400\ is
    port (    
	\rf in\:   INOUT  STD_LOGIC;    
	\rf out\:  INOUT  STD_LOGIC);
end \bpf-a400\;
