// generated by newgenasym  Fri May 23 10:53:01 2008


module atmega128 (aref, pa0, pa1, pa2, pa3, pa4, pa5, pa6, pa7, pb0, pb1, pb2, pb3,
        pb4, pb5, pb6, pb7, pc0, pc1, pc2, pc3, pc4, pc5, pc6, pc7, pd0,
        pd1, pd2, pd3, pd4, pd5, pd6, pd7, pe0, pe1, pe2, pe3, pe4, pe5,
        pe6, pe7, pen, pf0, pf1, pf2, pf3, pf4, pf5, pf6, pf7, pg0, pg1,
        pg2, pg3, pg4, reset, xtal1, xtal2);
    inout aref;
    inout pa0;
    inout pa1;
    inout pa2;
    inout pa3;
    inout pa4;
    inout pa5;
    inout pa6;
    inout pa7;
    inout pb0;
    inout pb1;
    inout pb2;
    inout pb3;
    inout pb4;
    inout pb5;
    inout pb6;
    inout pb7;
    inout pc0;
    inout pc1;
    inout pc2;
    inout pc3;
    inout pc4;
    inout pc5;
    inout pc6;
    inout pc7;
    inout pd0;
    inout pd1;
    inout pd2;
    inout pd3;
    inout pd4;
    inout pd5;
    inout pd6;
    inout pd7;
    inout pe0;
    inout pe1;
    inout pe2;
    inout pe3;
    inout pe4;
    inout pe5;
    inout pe6;
    inout pe7;
    inout pen;
    inout pf0;
    inout pf1;
    inout pf2;
    inout pf3;
    inout pf4;
    inout pf5;
    inout pf6;
    inout pf7;
    inout pg0;
    inout pg1;
    inout pg2;
    inout pg3;
    inout pg4;
    input reset;
    input xtal1;
    input xtal2;


    initial
        begin
        end

endmodule
