-- generated by newgenasym Wed Sep 13 11:33:38 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pe43704 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	\c0.25\:   INOUT  STD_LOGIC;    
	\c0.5\:    INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C16:       INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	C4:        INOUT  STD_LOGIC;    
	C8:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	PS:        INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	SI:        INOUT  STD_LOGIC;    
	\vss ext\: IN     STD_LOGIC);
end pe43704;
