// generated by newgenasym  Wed Dec 14 11:11:13 2011


module \tmo-1-02  (pri, pri_dot, sec, sec_dot);
    inout pri;
    inout pri_dot;
    inout sec;
    inout sec_dot;


    initial
        begin
        end

endmodule
