-- generated by newgenasym Wed Dec 14 11:11:13 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tmo-1-02\ is
    port (    
	PRI:       INOUT  STD_LOGIC;    
	PRI_DOT:   INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_DOT:   INOUT  STD_LOGIC);
end \tmo-1-02\;
