-- generated by newgenasym Fri Jul 13 16:41:47 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity T is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end T;
