// generated by newgenasym  Thu Feb 09 17:06:53 2006


module adp_2_4 (gnd, isolate1, isolate2, port1, port2, sum);
    input gnd;
    input isolate1;
    input isolate2;
    inout port1;
    inout port2;
    inout sum;


    initial
        begin
        end

endmodule
