-- generated by newgenasym Fri Jun 04 12:38:22 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tmm_103 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (6 DOWNTO 1));
end tmm_103;
