// generated by newgenasym  Mon Oct 13 17:00:32 2003


module pca9540 (sc0, sc1, scl, sd1, sda, sdo);
    inout sc0;
    inout sc1;
    inout scl;
    inout sd1;
    inout sda;
    inout sdo;


    initial
        begin
        end

endmodule
