-- generated by newgenasym Mon Oct 13 17:00:32 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pca9540 is
    port (    
	SC0:       INOUT  STD_LOGIC;    
	SC1:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SD1:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC);
end pca9540;
