-- generated by newgenasym Wed Oct 08 16:48:07 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jump2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end jump2;
