// generated by newgenasym  Mon May 07 12:59:06 2018


module epcs128 (asdi, data, dclk, ncs);
    inout asdi;
    inout data;
    inout dclk;
    inout ncs;


    initial
        begin
        end

endmodule
