// generated by newgenasym  Wed Nov 23 11:24:40 2005


module tps76328 (en, gnd, in, \nc/fb , out);
    input en;
    input gnd;
    input in;
    inout \nc/fb ;
    output out;


    initial
        begin
        end

endmodule
