-- generated by newgenasym Wed Nov 23 11:24:40 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps76328 is
    port (    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\nc/fb\:   INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end tps76328;
