-- generated by newgenasym Tue May 02 16:53:29 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity si570 is
    port (    
	\clk+\:    INOUT  STD_LOGIC;    
	\clk-\:    INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end si570;
