// generated by newgenasym  Wed May 17 17:26:26 2017


module tlk10232 (amuxa, amuxb, clkoutan, clkoutap, clkoutbn, clkoutbp, gpi0,
        hsrxan, hsrxap, hsrxbn, hsrxbp, hstxan, hstxap, hstxbn,
        hstxbp, ina0n, ina0p, ina1n, ina1p, ina2n, ina2p, ina3n,
        ina3p, inb0n, inb0p, inb1n, inb1p, inb2n, inb2p, inb3n, inb3p,
        losa, losb, ls_ok_in_a, ls_ok_in_b, ls_ok_out_a,
        ls_ok_out_b, mdc, mdio, mode_sel, out0n, out0p, out1n, out1p,
        out2n, out2p, out3n, out3p, outb0n, outb0p, outb1n, outb1p,
        outb2n, outb2p, outb3n, outb3p, pdtrxa_n, pdtrxb_n,
        prbs_pass, prbsen, prtad, refclk0n, refclk0p, refclk1n,
        refclk1p, reset_n, st, tck, tdi, tdo, testen, tms, trst_n);
    inout amuxa;
    inout amuxb;
    inout clkoutan;
    inout clkoutap;
    inout clkoutbn;
    inout clkoutbp;
    inout gpi0;
    inout hsrxan;
    inout hsrxap;
    inout hsrxbn;
    inout hsrxbp;
    inout hstxan;
    inout hstxap;
    inout hstxbn;
    inout hstxbp;
    inout ina0n;
    inout ina0p;
    inout ina1n;
    inout ina1p;
    inout ina2n;
    inout ina2p;
    inout ina3n;
    inout ina3p;
    inout inb0n;
    inout inb0p;
    inout inb1n;
    inout inb1p;
    inout inb2n;
    inout inb2p;
    inout inb3n;
    inout inb3p;
    inout losa;
    inout losb;
    inout ls_ok_in_a;
    inout ls_ok_in_b;
    inout ls_ok_out_a;
    inout ls_ok_out_b;
    inout mdc;
    inout mdio;
    inout mode_sel;
    inout out0n;
    inout out0p;
    inout out1n;
    inout out1p;
    inout out2n;
    inout out2p;
    inout out3n;
    inout out3p;
    inout outb0n;
    inout outb0p;
    inout outb1n;
    inout outb1p;
    inout outb2n;
    inout outb2p;
    inout outb3n;
    inout outb3p;
    inout pdtrxa_n;
    inout pdtrxb_n;
    inout prbs_pass;
    inout prbsen;
    inout [4:0] prtad;
    inout refclk0n;
    inout refclk0p;
    inout refclk1n;
    inout refclk1p;
    inout reset_n;
    inout st;
    inout tck;
    inout tdi;
    inout tdo;
    inout testen;
    inout tms;
    inout trst_n;


    initial
        begin
        end

endmodule
