// generated by newgenasym  Thu Mar 01 13:49:24 2018


module \612e_48fs_3  (a10, a12, a14, a16, a18, a2, a20, a22, a24, a26, a28, a30, a32,
        a4, a6, a8, c10, c12, c14, c16, c18, c2, c20, c22, c24, c26, c28,
        c30, c32, c4, c6, c8, e10, e12, e14, e16, e18, e2, e20, e22, e24,
        e26, e28, e30, e32, e4, e6, e8);
    inout a10;
    inout a12;
    inout a14;
    inout a16;
    inout a18;
    inout a2;
    inout a20;
    inout a22;
    inout a24;
    inout a26;
    inout a28;
    inout a30;
    inout a32;
    inout a4;
    inout a6;
    inout a8;
    inout c10;
    inout c12;
    inout c14;
    inout c16;
    inout c18;
    inout c2;
    inout c20;
    inout c22;
    inout c24;
    inout c26;
    inout c28;
    inout c30;
    inout c32;
    inout c4;
    inout c6;
    inout c8;
    inout e10;
    inout e12;
    inout e14;
    inout e16;
    inout e18;
    inout e2;
    inout e20;
    inout e22;
    inout e24;
    inout e26;
    inout e28;
    inout e30;
    inout e32;
    inout e4;
    inout e6;
    inout e8;


    initial
        begin
        end

endmodule
