// generated by newgenasym  Wed Jun 02 10:28:12 2004


module sn74lvc2g79 (\1clk , \1d , \1q , \2clk , \2d , \2q , gndd, p5v0);
    input \1clk ;
    input \1d ;
    output \1q ;
    input \2clk ;
    input \2d ;
    output \2q ;
    input gndd;
    input p5v0;


    initial
        begin
        end

endmodule
