// generated by newgenasym  Wed Dec 09 15:41:12 2009


module ad8138 (\+in , \+out , \-in , \-out , \v+ , \v- , vocm);
    inout \+in ;
    inout \+out ;
    inout \-in ;
    inout \-out ;
    inout \v+ ;
    inout \v- ;
    inout vocm;


    initial
        begin
        end

endmodule
