-- generated by newgenasym Tue Dec 15 17:24:32 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvcc3245 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	B6:        INOUT  STD_LOGIC;    
	B7:        INOUT  STD_LOGIC;    
	B8:        INOUT  STD_LOGIC;    
	DIR:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\oe#\:     INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB:      INOUT  STD_LOGIC);
end sn74lvcc3245;
