// generated by newgenasym  Tue Aug 31 15:33:50 2004


module jump5 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
