-- generated by newgenasym Tue Aug 31 15:33:50 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jump5 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end jump5;
