// generated by newgenasym  Wed Jun 30 14:44:37 2004


module op184 (in_a, \in_a* , \n.c. , null1, null2, out_a, \v+ , \v- );
    input in_a;
    input \in_a* ;
    inout \n.c. ;
    input null1;
    input null2;
    output out_a;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
