-- generated by newgenasym Wed Jun 30 14:44:37 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity op184 is
    port (    
	IN_A:      IN     STD_LOGIC;    
	\in_a*\:   IN     STD_LOGIC;    
	\n.c.\:    INOUT  STD_LOGIC;    
	NULL1:     IN     STD_LOGIC;    
	NULL2:     IN     STD_LOGIC;    
	OUT_A:     OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end op184;
