-- generated by newgenasym Fri Aug 22 17:48:52 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ics844021-01\ is
    port (    
	OE:        INOUT  STD_LOGIC;    
	Q:         INOUT  STD_LOGIC;    
	\q*\:      INOUT  STD_LOGIC;    
	XTAL_IN:   INOUT  STD_LOGIC;    
	XTAL_OUT:  INOUT  STD_LOGIC);
end \ics844021-01\;
