// generated by newgenasym  Thu May 25 16:56:59 2017


module \hdmr-19  (a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4,
        a5, a6, a7, a8, a9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;


    initial
        begin
        end

endmodule
