// generated by newgenasym  Thu May 25 12:08:18 2017


module mic2026 (ena, enb, flga, flgb, in, outa, outb);
    inout ena;
    inout enb;
    inout flga;
    inout flgb;
    inout in;
    inout outa;
    inout outb;


    initial
        begin
        end

endmodule
