// generated by newgenasym  Thu Jun 09 14:50:56 2011


module fst3253 (\1a , \1b1 , \1b2 , \1b3 , \1b4 , \2a , \2b1 , \2b2 , \2b3 , \2b4 , gnd, oe1, oe2, s,
        s0, vcc);
    inout \1a ;
    inout \1b1 ;
    inout \1b2 ;
    inout \1b3 ;
    inout \1b4 ;
    inout \2a ;
    inout \2b1 ;
    inout \2b2 ;
    inout \2b3 ;
    inout \2b4 ;
    input gnd;
    inout oe1;
    inout oe2;
    inout s;
    inout s0;
    input vcc;


    initial
        begin
        end

endmodule
