-- generated by newgenasym Thu Jun 09 14:50:56 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FST3253 is
    port (    
	\1a\:      INOUT  STD_LOGIC;    
	\1b1\:     INOUT  STD_LOGIC;    
	\1b2\:     INOUT  STD_LOGIC;    
	\1b3\:     INOUT  STD_LOGIC;    
	\1b4\:     INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2b1\:     INOUT  STD_LOGIC;    
	\2b2\:     INOUT  STD_LOGIC;    
	\2b3\:     INOUT  STD_LOGIC;    
	\2b4\:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OE1:       INOUT  STD_LOGIC;    
	OE2:       INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC;    
	S0:        INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end FST3253;
