// generated by newgenasym  Mon Nov 22 17:02:27 2004


module rcmd (\10 , \12 , \14 , \18 , \2 , \4 , \6 , \8 );
    input \10 ;
    input \12 ;
    input \14 ;
    input \18 ;
    input \2 ;
    input \4 ;
    input \6 ;
    input \8 ;


    initial
        begin
        end

endmodule
