-- generated by newgenasym Mon Nov 22 17:02:27 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rcmd is
    port (    
	\10\:      IN     STD_LOGIC;    
	\12\:      IN     STD_LOGIC;    
	\14\:      IN     STD_LOGIC;    
	\18\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end rcmd;
