// generated by newgenasym  Fri Dec 05 15:19:19 2003


module \564la8  (\1* , \2 , \3 , \4 , \5 );
    output \1* ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;


    initial
        begin
        end

endmodule
