// generated by newgenasym  Thu Mar 11 16:15:15 2004


module bmp6 (\in+ , \in- , off, \out+ , \out- );
    input \in+ ;
    input \in- ;
    input off;
    output \out+ ;
    output \out- ;


    initial
        begin
        end

endmodule
