-- generated by newgenasym Thu Mar 11 16:15:15 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BMP6 is
    port (    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	OFF:       IN     STD_LOGIC;    
	\out+\:    OUT    STD_LOGIC;    
	\out-\:    OUT    STD_LOGIC);
end BMP6;
