// generated by newgenasym  Fri Nov 27 13:09:23 2009


module ina134 (\+in , \-in , out, ref, sense, \v+ , \v- );
    inout \+in ;
    inout \-in ;
    inout out;
    inout ref;
    inout sense;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
