-- generated by newgenasym Fri Nov 27 13:09:23 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity INA134 is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end INA134;
