// generated by newgenasym  Thu Mar 02 17:04:29 2017


module pim300x (\-48_af , \-48_bf , \-48v_alarm , \-48v_out , \72v_cap , enable_af,
        enable_bf, logic_gnd, mgmt_pwr, shelf_gnd, vrtn_af,
        vrtn_bf, vrtn_out);
    inout \-48_af ;
    inout \-48_bf ;
    inout \-48v_alarm ;
    inout \-48v_out ;
    inout \72v_cap ;
    inout enable_af;
    inout enable_bf;
    inout logic_gnd;
    inout mgmt_pwr;
    inout shelf_gnd;
    inout vrtn_af;
    inout vrtn_bf;
    inout vrtn_out;


    initial
        begin
        end

endmodule
