-- generated by newgenasym Thu Mar 02 17:04:29 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pim300x is
    port (    
	\-48_af\:  INOUT  STD_LOGIC;    
	\-48_bf\:  INOUT  STD_LOGIC;    
	\-48v_alarm\: INOUT  STD_LOGIC;    
	\-48v_out\: INOUT  STD_LOGIC;    
	\72v_cap\: INOUT  STD_LOGIC;    
	ENABLE_AF: INOUT  STD_LOGIC;    
	ENABLE_BF: INOUT  STD_LOGIC;    
	LOGIC_GND: INOUT  STD_LOGIC;    
	MGMT_PWR:  INOUT  STD_LOGIC;    
	SHELF_GND: INOUT  STD_LOGIC;    
	VRTN_AF:   INOUT  STD_LOGIC;    
	VRTN_BF:   INOUT  STD_LOGIC;    
	VRTN_OUT:  INOUT  STD_LOGIC);
end pim300x;
