-- generated by newgenasym Tue Jun 22 11:51:13 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g07 is
    port (    
	A:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc2g07;
