// generated by newgenasym  Mon Oct 04 10:39:32 2010


module \m25pe16-vmw6  (\cs* , gnd, miso, mosi, \reset* , sck, vcc, \wp* );
    inout \cs* ;
    input gnd;
    inout miso;
    input mosi;
    input \reset* ;
    input sck;
    input vcc;
    inout \wp* ;


    initial
        begin
        end

endmodule
