-- generated by newgenasym Mon Oct 04 10:39:32 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \m25pe16-vmw6\ is
    port (    
	\cs*\:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	MISO:      INOUT  STD_LOGIC;    
	MOSI:      IN     STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	SCK:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\wp*\:     INOUT  STD_LOGIC);
end \m25pe16-vmw6\;
