// generated by newgenasym  Mon Sep 10 14:37:58 2012


module hmc900lp (calck, cmi, cmq, iin, iip, iqn, iqp, oin, oip, oqn, oqp, sclk,
        sdi, sdo, sen, vbg, vddbg, vddcal);
    inout calck;
    inout cmi;
    inout cmq;
    inout iin;
    inout iip;
    inout iqn;
    inout iqp;
    inout oin;
    inout oip;
    inout oqn;
    inout oqp;
    inout sclk;
    inout sdi;
    inout sdo;
    inout sen;
    inout vbg;
    inout vddbg;
    inout vddcal;


    initial
        begin
        end

endmodule
