-- generated by newgenasym Mon Sep 10 14:37:58 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc900lp is
    port (    
	CALCK:     INOUT  STD_LOGIC;    
	CMI:       INOUT  STD_LOGIC;    
	CMQ:       INOUT  STD_LOGIC;    
	IIN:       INOUT  STD_LOGIC;    
	IIP:       INOUT  STD_LOGIC;    
	IQN:       INOUT  STD_LOGIC;    
	IQP:       INOUT  STD_LOGIC;    
	OIN:       INOUT  STD_LOGIC;    
	OIP:       INOUT  STD_LOGIC;    
	OQN:       INOUT  STD_LOGIC;    
	OQP:       INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	SDI:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	SEN:       INOUT  STD_LOGIC;    
	VBG:       INOUT  STD_LOGIC;    
	VDDBG:     INOUT  STD_LOGIC;    
	VDDCAL:    INOUT  STD_LOGIC);
end hmc900lp;
