-- generated by newgenasym Sun Aug 01 19:11:06 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fin1002 is
    port (    
	RIN:       OUT    STD_LOGIC;    
	\rin*\:    OUT    STD_LOGIC;    
	ROUT:      IN     STD_LOGIC);
end fin1002;
