// generated by newgenasym  Wed Jun 15 14:38:30 2016


module lm3671 (en, fb, gnd, sw, vin);
    inout en;
    inout fb;
    input gnd;
    inout sw;
    inout vin;


    initial
        begin
        end

endmodule
