-- generated by newgenasym Wed Jun 15 14:38:30 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm3671 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end lm3671;
