// generated by newgenasym  Mon Nov 23 11:27:44 2009


module tes5wi (\+vin1 , \+vin2 , \+vout , \-vin1 , \-vin2 , \-vout , \on/off );
    inout \+vin1 ;
    inout \+vin2 ;
    inout \+vout ;
    inout \-vin1 ;
    inout \-vin2 ;
    inout \-vout ;
    inout \on/off ;


    initial
        begin
        end

endmodule
