// generated by newgenasym  Thu Aug 28 17:51:50 2014


module max16052 (cdelay, en, in, out);
    inout cdelay;
    inout en;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
