// generated by newgenasym  Mon Jul 17 15:22:27 2017


module tlv3011 (\in+ , \in- , out, ref);
    inout \in+ ;
    inout \in- ;
    inout out;
    inout ref;


    initial
        begin
        end

endmodule
