-- generated by newgenasym Mon Jul 17 15:22:27 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlv3011 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end tlv3011;
