// generated by newgenasym  Wed Apr 19 11:24:28 2006


module ad8132 (\+#20in , \+out , \-out , \in* , \v+ , \v- , vocm);
    inout \+#20in ;
    inout \+out ;
    inout \-out ;
    inout \in* ;
    inout \v+ ;
    inout \v- ;
    inout vocm;


    initial
        begin
        end

endmodule
