-- generated by newgenasym Wed Apr 19 11:24:28 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8132 is
    port (    
	\+ in\:    INOUT  STD_LOGIC;    
	\+out\:    INOUT  STD_LOGIC;    
	\-out\:    INOUT  STD_LOGIC;    
	\in*\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VOCM:      INOUT  STD_LOGIC);
end ad8132;
