-- generated by newgenasym Fri Apr 11 17:17:59 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \530ln1\ is
    port (    
	A:         IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \530ln1\;
