// generated by newgenasym  Sat Jun 09 14:54:47 2007


module cdcv304 (\1y0 , \1y1 , \1y2 , \1y3 , clkin, gnd, oe, vdd);
    inout \1y0 ;
    inout \1y1 ;
    inout \1y2 ;
    inout \1y3 ;
    inout clkin;
    inout gnd;
    inout oe;
    inout vdd;


    initial
        begin
        end

endmodule
