// generated by newgenasym  Tue Jul 17 15:06:17 2007


module max3384 (\c1+ , \c1- , \c2+ , \c2- , gnd, r1in, r1out, r2in, r2out, shdn, t1in,
        t1out, t2in, t2out, \v+ , \v- , vcc);
    inout \c1+ ;
    inout \c1- ;
    inout \c2+ ;
    inout \c2- ;
    inout gnd;
    inout r1in;
    inout r1out;
    inout r2in;
    inout r2out;
    inout shdn;
    inout t1in;
    inout t1out;
    inout t2in;
    inout t2out;
    inout \v+ ;
    inout \v- ;
    inout vcc;


    initial
        begin
        end

endmodule
