// generated by newgenasym  Tue Aug 28 16:21:01 2018


module altera_5agxma7g4f31 (\3a_as_data0_asdo , \3a_as_data1 , \3a_as_data2 , \3a_as_data3 ,
        \3a_clk0n_diffio_rx_b2n , \3a_clk0p_diffio_rx_b2p ,
        \3a_clk1n_diffio_rx_b4n , \3a_clk1p_diffio_rx_b4p ,
        \3a_clk2n_diffio_rx_b7n , \3a_clk2p_diffio_rx_b7p ,
        \3a_clk3n_diffio_rx_b9n , \3a_clk3p_diffio_rx_b9p , \3a_dclk ,
        \3a_diffio_rx_b11n , \3a_diffio_rx_b11p , \3a_diffio_rx_b13n ,
        \3a_diffio_rx_b13p , \3a_diffio_rx_b15n , \3a_diffio_rx_b15p ,
        \3a_diffio_tx_b10n , \3a_diffio_tx_b10p , \3a_diffio_tx_b12n ,
        \3a_diffio_tx_b12p , \3a_diffio_tx_b14n , \3a_diffio_tx_b14p ,
        \3a_diffio_tx_b3n , \3a_diffio_tx_b3p , \3a_diffio_tx_b8n ,
        \3a_diffio_tx_b8p ,
        \3a_fpll_bl_clkout0_fpll_bl_clkoutp_fpll_bl_fb0_diffio_tx_b5p ,
        \3a_fpll_bl_clkout1_fpll_bl_clkoutn_diffio_tx_b5n ,
        \3a_fpll_bl_clkout2_fpll_bl_fbp_fpll_bl_fb1_diffio_rx_b6p ,
        \3a_fpll_bl_clkout3_fpll_bl_fbn_diffio_rx_b6n ,
        \3a_io_ad25 , \3a_io_ae25 , \3a_io_diffio_tx_b1p , \3a_ncso ,
        \3a_rzq_0_diffio_tx_b1n , \3a_tck , \3a_tdi , \3a_tdo , \3a_tms ,
        \3d_clk4n_diffio_rx_b60n , \3d_clk4p_diffio_rx_b60p ,
        \3d_clk5n_diffio_rx_b62n , \3d_clk5p_diffio_rx_b62p ,
        \3d_clk6n_diffio_rx_b66n , \3d_clk6p_diffio_rx_b66p ,
        \3d_clk6p_diffio_rx_b68p , \3d_clk7n_diffio_rx_b68n ,
        \3d_diffio_rx_b55n , \3d_diffio_rx_b55p , \3d_diffio_rx_b57n ,
        \3d_diffio_rx_b57p , \3d_diffio_rx_b59n , \3d_diffio_rx_b59p ,
        \3d_diffio_tx_b54n , \3d_diffio_tx_b54p , \3d_diffio_tx_b56n ,
        \3d_diffio_tx_b56p , \3d_diffio_tx_b58n , \3d_diffio_tx_b58p ,
        \3d_diffio_tx_b61n , \3d_diffio_tx_b61p , \3d_diffio_tx_b65n ,
        \3d_diffio_tx_b65p , \3d_diffio_tx_b67n , \3d_diffio_tx_b67p ,
        \3d_fpll_bc_clkout0_fpll_bc_clkoutp_fpll_bc_fb0_diffio_tx_b63p ,
        \3d_fpll_bc_clkout1_fpll_bc_clkoutn_diffio_tx_b63n ,
        \3d_fpll_bc_clkout2_fpll_bc_fbp_fpll_bc_fb1_diffio_rx_b64p ,
        \3d_fpll_bc_clkout3_fpll_bc_fbn_diffio_rx_b64n ,
        \3d_io_y20 , \3d_vrefb3dn0 , \4a_clk10n_diffio_rx_b124n ,
        \4a_clk10p_diffio_rx_b124p , \4a_clk11n_diffio_rx_b120n ,
        \4a_clk11p_diffio_rx_b120p , \4a_clk8n_diffio_rx_b128n ,
        \4a_clk8p_diffio_rx_b128p , \4a_clk9n_diffio_rx_b126n ,
        \4a_clk9p_diffio_rx_b126p , \4a_diffio_rx_b115n_data5 ,
        \4a_diffio_rx_b115p_data6 , \4a_diffio_rx_b117n_data7 ,
        \4a_diffio_rx_b117p_data8 , \4a_diffio_rx_b119n_data9 ,
        \4a_diffio_rx_b119p_clkusr , \4a_diffio_tx_b114n_data10 ,
        \4a_diffio_tx_b114p_data11 , \4a_diffio_tx_b116n_data12 ,
        \4a_diffio_tx_b116p_data13 , \4a_diffio_tx_b118n_data14 ,
        \4a_diffio_tx_b118p_data15 , \4a_diffio_tx_b123n ,
        \4a_diffio_tx_b123p , \4a_diffio_tx_b125n ,
        \4a_diffio_tx_b125p , \4a_diffio_tx_b127n ,
        \4a_fpll_br_clkout0_fpll_br_clkoutp_fpll_br_fb0_diffio_tx_b121p ,
        \4a_fpll_br_clkout1_fpll_br_clkoutn_diffio_tx_b121n ,
        \4a_fpll_br_clkout2_fpll_br_fbp_fpll_br_fb1_diffio_rx_b122p ,
        \4a_fpll_br_clkout3_fpll_br_fbn_diffio_rx_b122n ,
        \4a_io_ac7 , \4a_rzq_1_diffio_tx_b127p , \4a_vrefb4an0 ,
        \4b_diffio_rx_b100n , \4b_diffio_rx_b100p ,
        \4b_diffio_rx_b102n , \4b_diffio_rx_b102p ,
        \4b_diffio_rx_b104n , \4b_diffio_rx_b104p ,
        \4b_diffio_rx_b106n , \4b_diffio_rx_b106p ,
        \4b_diffio_rx_b108n , \4b_diffio_rx_b108p ,
        \4b_diffio_rx_b110n , \4b_diffio_rx_b110p ,
        \4b_diffio_rx_b112n , \4b_diffio_rx_b112p ,
        \4b_diffio_rx_b113n , \4b_diffio_rx_b113p ,
        \4b_diffio_tx_b101n , \4b_diffio_tx_b101p ,
        \4b_diffio_tx_b103n , \4b_diffio_tx_b103p ,
        \4b_diffio_tx_b105n , \4b_diffio_tx_b105p ,
        \4b_diffio_tx_b107n , \4b_diffio_tx_b107p ,
        \4b_diffio_tx_b109n , \4b_diffio_tx_b109p ,
        \4b_diffio_tx_b111n , \4b_diffio_tx_b111p ,
        \4b_diffio_tx_b99n , \4b_diffio_tx_b99p , \4b_io_ae14 ,
        \4b_io_ae8 , \4b_vrefb4bn0 , \4c_diffio_rx_b85n ,
        \4c_diffio_rx_b85p , \4c_diffio_rx_b87n , \4c_diffio_rx_b87p ,
        \4c_diffio_rx_b89n , \4c_diffio_rx_b89p , \4c_diffio_rx_b90n ,
        \4c_diffio_rx_b90p , \4c_diffio_rx_b92n , \4c_diffio_rx_b92p ,
        \4c_diffio_rx_b94n , \4c_diffio_rx_b94p , \4c_diffio_rx_b96n ,
        \4c_diffio_rx_b96p , \4c_diffio_rx_b98n , \4c_diffio_rx_b98p ,
        \4c_diffio_tx_b84n , \4c_diffio_tx_b84p , \4c_diffio_tx_b86n ,
        \4c_diffio_tx_b86p , \4c_diffio_tx_b88n , \4c_diffio_tx_b88p ,
        \4c_diffio_tx_b91n , \4c_diffio_tx_b91p , \4c_diffio_tx_b93n ,
        \4c_diffio_tx_b93p , \4c_diffio_tx_b95n , \4c_diffio_tx_b95p ,
        \4c_diffio_tx_b97n , \4c_diffio_tx_b97p , \4c_vrefb4cn0 ,
        \4d_diffio_rx_b70n , \4d_diffio_rx_b70p , \4d_diffio_rx_b72n ,
        \4d_diffio_rx_b72p , \4d_diffio_rx_b74n , \4d_diffio_rx_b74p ,
        \4d_diffio_rx_b75n , \4d_diffio_rx_b75p , \4d_diffio_rx_b77n ,
        \4d_diffio_rx_b77p , \4d_diffio_rx_b79n , \4d_diffio_rx_b79p ,
        \4d_diffio_rx_b81n , \4d_diffio_rx_b81p , \4d_diffio_rx_b83n ,
        \4d_diffio_rx_b83p , \4d_diffio_tx_b69n , \4d_diffio_tx_b69p ,
        \4d_diffio_tx_b71n , \4d_diffio_tx_b71p , \4d_diffio_tx_b73n ,
        \4d_diffio_tx_b73p , \4d_diffio_tx_b76n , \4d_diffio_tx_b76p ,
        \4d_diffio_tx_b78n , \4d_diffio_tx_b78p , \4d_diffio_tx_b80n ,
        \4d_diffio_tx_b80p , \4d_diffio_tx_b82n , \4d_diffio_tx_b82p ,
        \4d_io_ad17 , \4d_io_ae17 , \7a_clk12n_diffio_rx_t1n ,
        \7a_clk12p_diffio_rx_t1p , \7a_clk13n_diffio_rx_t3n ,
        \7a_clk13p_diffio_rx_t3p , \7a_clk14n_diffio_rx_t5n ,
        \7a_clk14p_diffio_rx_t5p , \7a_clk15n_diffio_rx_t9n ,
        \7a_clk15p_diffio_rx_t9p , \7a_crc_error , \7a_cvp_confdone ,
        \7a_dev_clrn , \7a_dev_oe , \7a_diffio_tx_t11p ,
        \7a_diffio_tx_t2n , \7a_diffio_tx_t4n , \7a_diffio_tx_t4p ,
        \7a_diffio_tx_t6n , \7a_diffio_tx_t6p ,
        \7a_fpll_tr_clkout0_fpll_tr_clkoutp_fpll_tr_fb0_diffio_tx_t8p ,
        \7a_fpll_tr_clkout1_fpll_tr_clkoutn_diffio_tx_t8n ,
        \7a_fpll_tr_clkout2_fpll_tr_fbp_fpll_tr_fb1_diffio_rx_t7p ,
        \7a_fpll_tr_clkout3_fpll_tr_fbn_diffio_rx_t7n ,
        \7a_init_done , \7a_io_j6 , \7a_io_k6 , \7a_nceo , \7a_nperstl0 ,
        \7a_pr_done , \7a_pr_error , \7a_pr_ready , \7a_pr_request ,
        \7a_rzq_5_diffio_tx_t2p , \7b_diffio_rx_t16n ,
        \7b_diffio_rx_t16p , \7b_diffio_rx_t17n , \7b_diffio_rx_t17p ,
        \7b_diffio_rx_t19n , \7b_diffio_rx_t19p , \7b_diffio_rx_t21n ,
        \7b_diffio_rx_t21p , \7b_diffio_rx_t23n , \7b_diffio_rx_t23p ,
        \7b_diffio_rx_t25n , \7b_diffio_rx_t25p , \7b_diffio_rx_t27n ,
        \7b_diffio_rx_t27p , \7b_diffio_rx_t29n , \7b_diffio_rx_t29p ,
        \7b_diffio_tx_t18n , \7b_diffio_tx_t18p , \7b_diffio_tx_t20n ,
        \7b_diffio_tx_t20p , \7b_diffio_tx_t22n , \7b_diffio_tx_t22p ,
        \7b_diffio_tx_t24n , \7b_diffio_tx_t24p , \7b_diffio_tx_t26n ,
        \7b_diffio_tx_t26p , \7b_diffio_tx_t28n , \7b_diffio_tx_t28p ,
        \7b_diffio_tx_t30n , \7b_diffio_tx_t30p , \7b_io_j8 , \7b_io_k8 ,
        \7c_diffio_rx_t31n , \7c_diffio_rx_t31p , \7c_diffio_rx_t33n ,
        \7c_diffio_rx_t33p , \7c_diffio_rx_t35n , \7c_diffio_rx_t35p ,
        \7c_diffio_rx_t37n , \7c_diffio_rx_t37p , \7c_diffio_rx_t39n ,
        \7c_diffio_rx_t39p , \7c_diffio_rx_t40n , \7c_diffio_rx_t40p ,
        \7c_diffio_rx_t42n , \7c_diffio_rx_t42p , \7c_diffio_rx_t44n ,
        \7c_diffio_rx_t44p , \7c_diffio_tx_t32n , \7c_diffio_tx_t32p ,
        \7c_diffio_tx_t34n , \7c_diffio_tx_t34p , \7c_diffio_tx_t36n ,
        \7c_diffio_tx_t36p , \7c_diffio_tx_t38n , \7c_diffio_tx_t38p ,
        \7c_diffio_tx_t41n , \7c_diffio_tx_t41p , \7c_diffio_tx_t43n ,
        \7c_diffio_tx_t43p , \7c_diffio_tx_t45n , \7c_diffio_tx_t45p ,
        \7c_io_j13 , \7c_io_k13 , \7d_diffio_rx_t46p ,
        \7d_diffio_rx_t48n , \7d_diffio_rx_t48p , \7d_diffio_rx_t50n ,
        \7d_diffio_rx_t50p , \7d_diffio_rx_t52n , \7d_diffio_rx_t52p ,
        \7d_diffio_rx_t54n , \7d_diffio_rx_t54p , \7d_diffio_rx_t55n ,
        \7d_diffio_rx_t55p , \7d_diffio_rx_t57n , \7d_diffio_rx_t57p ,
        \7d_diffio_rx_t59n , \7d_diffio_rx_t59p , \7d_diffio_tx_t47n ,
        \7d_diffio_tx_t47p , \7d_diffio_tx_t49n , \7d_diffio_tx_t49p ,
        \7d_diffio_tx_t51n , \7d_diffio_tx_t51p , \7d_diffio_tx_t53n ,
        \7d_diffio_tx_t53p , \7d_diffio_tx_t56n , \7d_diffio_tx_t56p ,
        \7d_diffio_tx_t58n , \7d_diffio_tx_t58p , \7d_diffio_tx_t60n ,
        \7d_diffio_tx_t60p , \7d_io_g15 , \7d_io_j18 , \7d_io_k18 ,
        \8a_clk20n_diffio_rx_t127n , \8a_clk20p_diffio_rx_t127p ,
        \8a_clk21n_diffio_rx_t125n , \8a_clk21p_diffio_rx_t125p ,
        \8a_clk22n_diffio_rx_t122n , \8a_clk22p_diffio_rx_t122p ,
        \8a_clk23n_diffio_rx_t120n , \8a_clk23p_diffio_rx_t120p ,
        \8a_conf_done , \8a_diffio_rx_t114n , \8a_diffio_rx_t114p ,
        \8a_diffio_rx_t116n , \8a_diffio_rx_t116p ,
        \8a_diffio_rx_t118n , \8a_diffio_rx_t118p ,
        \8a_diffio_tx_t115n , \8a_diffio_tx_t115p ,
        \8a_diffio_tx_t117n , \8a_diffio_tx_t117p ,
        \8a_diffio_tx_t119n , \8a_diffio_tx_t119p ,
        \8a_diffio_tx_t121n , \8a_diffio_tx_t121p ,
        \8a_diffio_tx_t126n , \8a_diffio_tx_t126p ,
        \8a_diffio_tx_t128p ,
        \8a_fpll_tl_clkout0_fpll_tl_clkoutp_fpll_tl_fb0_diffio_tx_t124p ,
        \8a_fpll_tl_clkout1_fpll_tl_clkoutn_diffio_tx_t124n ,
        \8a_fpll_tl_clkout2_fpll_tl_fbp_fpll_tl_fb1_diffio_rx_t123p ,
        \8a_fpll_tl_clkout3_fpll_tl_fbn_diffio_rx_t123n ,
        \8a_io_g24 , \8a_io_h25 , \8a_msel0 , \8a_msel1 , \8a_msel2 ,
        \8a_msel3 , \8a_msel4 , \8a_nce , \8a_nconfig , \8a_nstatus ,
        \8a_rzq_6_diffio_tx_t128n , \8d_clk16n_diffio_rx_t69n ,
        \8d_clk16p_diffio_rx_t69p , \8d_clk17n_diffio_rx_t67n ,
        \8d_clk17p_diffio_rx_t67p , \8d_clk18n_diffio_rx_t63n ,
        \8d_clk19n_diffio_rx_t61n , \8d_clk19p_diffio_rx_t61p ,
        \8d_clk_18p_diffio_rx_t63p , \8d_diffio_rx_t70n ,
        \8d_diffio_rx_t70p , \8d_diffio_rx_t72n , \8d_diffio_rx_t72p ,
        \8d_diffio_rx_t74n , \8d_diffio_rx_t74p , \8d_diffio_tx_t62n ,
        \8d_diffio_tx_t62p , \8d_diffio_tx_t64n , \8d_diffio_tx_t64p ,
        \8d_diffio_tx_t68n , \8d_diffio_tx_t68p , \8d_diffio_tx_t71n ,
        \8d_diffio_tx_t71p , \8d_diffio_tx_t73n , \8d_diffio_tx_t73p ,
        \8d_diffio_tx_t75n , \8d_diffio_tx_t75p ,
        \8d_fpll_tc_clkout0_fpll_tc_clkoutp_fpll_tc_fb0_diffio_tx_t66p ,
        \8d_fpll_tc_clkout1_fpll_tc_clkoutn_diffio_tx_t66n ,
        \8d_fpll_tc_clkout2_fpll_tc_fbp_fpll_tc_fb1_diffio_rx_t65p ,
        \8d_fpll_tc_clkout3_fpll_tc_fbn_diffio_rx_t65n ,
        \8d_io_j21 , \8d_io_k21 , l0_gxb_rx_l0n_gxb_refclk_l0n,
        l0_gxb_rx_l0p_gxb_refclk_l0p,
        l0_gxb_rx_l1n_gxb_refclk_l1n,
        l0_gxb_rx_l1p_gxb_refclk_l1p,
        l0_gxb_rx_l2n_gxb_refclk_l2n,
        l0_gxb_rx_l2p_gxb_refclk_l2p,
        l0_gxb_rx_l3n_gxb_refclk_l3n,
        l0_gxb_rx_l3p_gxb_refclk_l3p,
        l0_gxb_rx_l4n_gxb_refclk_l4n,
        l0_gxb_rx_l4p_gxb_refclk_l4p,
        l0_gxb_rx_l5n_gxb_refclk_l5n,
        l0_gxb_rx_l5p_gxb_refclk_l5p, l0_gxb_tx_l0n,
        l0_gxb_tx_l0p, l0_gxb_tx_l1n, l0_gxb_tx_l1p,
        l0_gxb_tx_l2n, l0_gxb_tx_l2p, l0_gxb_tx_l3n,
        l0_gxb_tx_l3p, l0_gxb_tx_l4n, l0_gxb_tx_l4p,
        l0_gxb_tx_l5n, l0_gxb_tx_l5p, l0_refclk0ln, l0_refclk0lp,
        l0_refclk1ln, l0_refclk1lp,
        l1_gxb_rx_l6n_gxb_refclk_l6n,
        l1_gxb_rx_l6p_gxb_refclk_l6p,
        l1_gxb_rx_l7n_gxb_refclk_l7n,
        l1_gxb_rx_l7p_gxb_refclk_l7p,
        l1_gxb_rx_l8n_gxb_refclk_l8n,
        l1_gxb_rx_l8p_gxb_refclk_l8p, l1_gxb_tx_l6n,
        l1_gxb_tx_l6p, l1_gxb_tx_l7n, l1_gxb_tx_l7p,
        l1_gxb_tx_l8n, l1_gxb_tx_l8p, l1_refclk2ln, l1_refclk2lp,
        r0_gxb_rx_r0n_gxb_refclk_r0n,
        r0_gxb_rx_r0p_gxb_refclk_r0p,
        r0_gxb_rx_r1n_gxb_refclk_r1n,
        r0_gxb_rx_r1p_gxb_refclk_r1p,
        r0_gxb_rx_r2n_gxb_refclk_r2n,
        r0_gxb_rx_r2p_gxb_refclk_r2p, r0_gxb_tx_r0n,
        r0_gxb_tx_r0p, r0_gxb_tx_r1n, r0_gxb_tx_r1p,
        r0_gxb_tx_r2n, r0_gxb_tx_r2p, r0_refclk0rn, r0_refclk0rp,
        r1_gxb_rx_r10n_gxb_refclk_r10n,
        r1_gxb_rx_r10p_gxb_refclk_r10p,
        r1_gxb_rx_r11n_gxb_refclk_r11n,
        r1_gxb_rx_r11p_gxb_refclk_r11p,
        r1_gxb_rx_r6n_gxb_refclk_r6n,
        r1_gxb_rx_r6p_gxb_refclk_r6p,
        r1_gxb_rx_r7n_gxb_refclk_r7n,
        r1_gxb_rx_r7p_gxb_refclk_r7p,
        r1_gxb_rx_r8n_gxb_refclk_r8n,
        r1_gxb_rx_r8p_gxb_refclk_r8p,
        r1_gxb_rx_r9n_gxb_refclk_r9n,
        r1_gxb_rx_r9p_gxb_refclk_r9p, r1_gxb_tx_r10n,
        r1_gxb_tx_r10p, r1_gxb_tx_r11n, r1_gxb_tx_r11p,
        r1_gxb_tx_r6n, r1_gxb_tx_r6p, r1_gxb_tx_r7n,
        r1_gxb_tx_r7p, r1_gxb_tx_r8n, r1_gxb_tx_r8p,
        r1_gxb_tx_r9n, r1_gxb_tx_r9p, r1_refclk2rn, r1_refclk2rp,
        r1_refclk3rn, r1_refclk3rp, rref_br, rref_tl);
    inout \3a_as_data0_asdo ;
    inout \3a_as_data1 ;
    inout \3a_as_data2 ;
    inout \3a_as_data3 ;
    inout \3a_clk0n_diffio_rx_b2n ;
    inout \3a_clk0p_diffio_rx_b2p ;
    inout \3a_clk1n_diffio_rx_b4n ;
    inout \3a_clk1p_diffio_rx_b4p ;
    inout \3a_clk2n_diffio_rx_b7n ;
    inout \3a_clk2p_diffio_rx_b7p ;
    inout \3a_clk3n_diffio_rx_b9n ;
    inout \3a_clk3p_diffio_rx_b9p ;
    inout \3a_dclk ;
    inout \3a_diffio_rx_b11n ;
    inout \3a_diffio_rx_b11p ;
    inout \3a_diffio_rx_b13n ;
    inout \3a_diffio_rx_b13p ;
    inout \3a_diffio_rx_b15n ;
    inout \3a_diffio_rx_b15p ;
    inout \3a_diffio_tx_b10n ;
    inout \3a_diffio_tx_b10p ;
    inout \3a_diffio_tx_b12n ;
    inout \3a_diffio_tx_b12p ;
    inout \3a_diffio_tx_b14n ;
    inout \3a_diffio_tx_b14p ;
    inout \3a_diffio_tx_b3n ;
    inout \3a_diffio_tx_b3p ;
    inout \3a_diffio_tx_b8n ;
    inout \3a_diffio_tx_b8p ;
    inout \3a_fpll_bl_clkout0_fpll_bl_clkoutp_fpll_bl_fb0_diffio_tx_b5p ;
    inout \3a_fpll_bl_clkout1_fpll_bl_clkoutn_diffio_tx_b5n ;
    inout \3a_fpll_bl_clkout2_fpll_bl_fbp_fpll_bl_fb1_diffio_rx_b6p ;
    inout \3a_fpll_bl_clkout3_fpll_bl_fbn_diffio_rx_b6n ;
    inout \3a_io_ad25 ;
    inout \3a_io_ae25 ;
    inout \3a_io_diffio_tx_b1p ;
    inout \3a_ncso ;
    inout \3a_rzq_0_diffio_tx_b1n ;
    inout \3a_tck ;
    inout \3a_tdi ;
    inout \3a_tdo ;
    inout \3a_tms ;
    inout \3d_clk4n_diffio_rx_b60n ;
    inout \3d_clk4p_diffio_rx_b60p ;
    inout \3d_clk5n_diffio_rx_b62n ;
    inout \3d_clk5p_diffio_rx_b62p ;
    inout \3d_clk6n_diffio_rx_b66n ;
    inout \3d_clk6p_diffio_rx_b66p ;
    inout \3d_clk6p_diffio_rx_b68p ;
    inout \3d_clk7n_diffio_rx_b68n ;
    inout \3d_diffio_rx_b55n ;
    inout \3d_diffio_rx_b55p ;
    inout \3d_diffio_rx_b57n ;
    inout \3d_diffio_rx_b57p ;
    inout \3d_diffio_rx_b59n ;
    inout \3d_diffio_rx_b59p ;
    inout \3d_diffio_tx_b54n ;
    inout \3d_diffio_tx_b54p ;
    inout \3d_diffio_tx_b56n ;
    inout \3d_diffio_tx_b56p ;
    inout \3d_diffio_tx_b58n ;
    inout \3d_diffio_tx_b58p ;
    inout \3d_diffio_tx_b61n ;
    inout \3d_diffio_tx_b61p ;
    inout \3d_diffio_tx_b65n ;
    inout \3d_diffio_tx_b65p ;
    inout \3d_diffio_tx_b67n ;
    inout \3d_diffio_tx_b67p ;
    inout \3d_fpll_bc_clkout0_fpll_bc_clkoutp_fpll_bc_fb0_diffio_tx_b63p ;
    inout \3d_fpll_bc_clkout1_fpll_bc_clkoutn_diffio_tx_b63n ;
    inout \3d_fpll_bc_clkout2_fpll_bc_fbp_fpll_bc_fb1_diffio_rx_b64p ;
    inout \3d_fpll_bc_clkout3_fpll_bc_fbn_diffio_rx_b64n ;
    inout \3d_io_y20 ;
    inout \3d_vrefb3dn0 ;
    inout \4a_clk10n_diffio_rx_b124n ;
    inout \4a_clk10p_diffio_rx_b124p ;
    inout \4a_clk11n_diffio_rx_b120n ;
    inout \4a_clk11p_diffio_rx_b120p ;
    inout \4a_clk8n_diffio_rx_b128n ;
    inout \4a_clk8p_diffio_rx_b128p ;
    inout \4a_clk9n_diffio_rx_b126n ;
    inout \4a_clk9p_diffio_rx_b126p ;
    inout \4a_diffio_rx_b115n_data5 ;
    inout \4a_diffio_rx_b115p_data6 ;
    inout \4a_diffio_rx_b117n_data7 ;
    inout \4a_diffio_rx_b117p_data8 ;
    inout \4a_diffio_rx_b119n_data9 ;
    inout \4a_diffio_rx_b119p_clkusr ;
    inout \4a_diffio_tx_b114n_data10 ;
    inout \4a_diffio_tx_b114p_data11 ;
    inout \4a_diffio_tx_b116n_data12 ;
    inout \4a_diffio_tx_b116p_data13 ;
    inout \4a_diffio_tx_b118n_data14 ;
    inout \4a_diffio_tx_b118p_data15 ;
    inout \4a_diffio_tx_b123n ;
    inout \4a_diffio_tx_b123p ;
    inout \4a_diffio_tx_b125n ;
    inout \4a_diffio_tx_b125p ;
    inout \4a_diffio_tx_b127n ;
    inout \4a_fpll_br_clkout0_fpll_br_clkoutp_fpll_br_fb0_diffio_tx_b121p ;
    inout \4a_fpll_br_clkout1_fpll_br_clkoutn_diffio_tx_b121n ;
    inout \4a_fpll_br_clkout2_fpll_br_fbp_fpll_br_fb1_diffio_rx_b122p ;
    inout \4a_fpll_br_clkout3_fpll_br_fbn_diffio_rx_b122n ;
    inout \4a_io_ac7 ;
    inout \4a_rzq_1_diffio_tx_b127p ;
    inout \4a_vrefb4an0 ;
    inout \4b_diffio_rx_b100n ;
    inout \4b_diffio_rx_b100p ;
    inout \4b_diffio_rx_b102n ;
    inout \4b_diffio_rx_b102p ;
    inout \4b_diffio_rx_b104n ;
    inout \4b_diffio_rx_b104p ;
    inout \4b_diffio_rx_b106n ;
    inout \4b_diffio_rx_b106p ;
    inout \4b_diffio_rx_b108n ;
    inout \4b_diffio_rx_b108p ;
    inout \4b_diffio_rx_b110n ;
    inout \4b_diffio_rx_b110p ;
    inout \4b_diffio_rx_b112n ;
    inout \4b_diffio_rx_b112p ;
    inout \4b_diffio_rx_b113n ;
    inout \4b_diffio_rx_b113p ;
    inout \4b_diffio_tx_b101n ;
    inout \4b_diffio_tx_b101p ;
    inout \4b_diffio_tx_b103n ;
    inout \4b_diffio_tx_b103p ;
    inout \4b_diffio_tx_b105n ;
    inout \4b_diffio_tx_b105p ;
    inout \4b_diffio_tx_b107n ;
    inout \4b_diffio_tx_b107p ;
    inout \4b_diffio_tx_b109n ;
    inout \4b_diffio_tx_b109p ;
    inout \4b_diffio_tx_b111n ;
    inout \4b_diffio_tx_b111p ;
    inout \4b_diffio_tx_b99n ;
    inout \4b_diffio_tx_b99p ;
    inout \4b_io_ae14 ;
    inout \4b_io_ae8 ;
    inout \4b_vrefb4bn0 ;
    inout \4c_diffio_rx_b85n ;
    inout \4c_diffio_rx_b85p ;
    inout \4c_diffio_rx_b87n ;
    inout \4c_diffio_rx_b87p ;
    inout \4c_diffio_rx_b89n ;
    inout \4c_diffio_rx_b89p ;
    inout \4c_diffio_rx_b90n ;
    inout \4c_diffio_rx_b90p ;
    inout \4c_diffio_rx_b92n ;
    inout \4c_diffio_rx_b92p ;
    inout \4c_diffio_rx_b94n ;
    inout \4c_diffio_rx_b94p ;
    inout \4c_diffio_rx_b96n ;
    inout \4c_diffio_rx_b96p ;
    inout \4c_diffio_rx_b98n ;
    inout \4c_diffio_rx_b98p ;
    inout \4c_diffio_tx_b84n ;
    inout \4c_diffio_tx_b84p ;
    inout \4c_diffio_tx_b86n ;
    inout \4c_diffio_tx_b86p ;
    inout \4c_diffio_tx_b88n ;
    inout \4c_diffio_tx_b88p ;
    inout \4c_diffio_tx_b91n ;
    inout \4c_diffio_tx_b91p ;
    inout \4c_diffio_tx_b93n ;
    inout \4c_diffio_tx_b93p ;
    inout \4c_diffio_tx_b95n ;
    inout \4c_diffio_tx_b95p ;
    inout \4c_diffio_tx_b97n ;
    inout \4c_diffio_tx_b97p ;
    inout \4c_vrefb4cn0 ;
    inout \4d_diffio_rx_b70n ;
    inout \4d_diffio_rx_b70p ;
    inout \4d_diffio_rx_b72n ;
    inout \4d_diffio_rx_b72p ;
    inout \4d_diffio_rx_b74n ;
    inout \4d_diffio_rx_b74p ;
    inout \4d_diffio_rx_b75n ;
    inout \4d_diffio_rx_b75p ;
    inout \4d_diffio_rx_b77n ;
    inout \4d_diffio_rx_b77p ;
    inout \4d_diffio_rx_b79n ;
    inout \4d_diffio_rx_b79p ;
    inout \4d_diffio_rx_b81n ;
    inout \4d_diffio_rx_b81p ;
    inout \4d_diffio_rx_b83n ;
    inout \4d_diffio_rx_b83p ;
    inout \4d_diffio_tx_b69n ;
    inout \4d_diffio_tx_b69p ;
    inout \4d_diffio_tx_b71n ;
    inout \4d_diffio_tx_b71p ;
    inout \4d_diffio_tx_b73n ;
    inout \4d_diffio_tx_b73p ;
    inout \4d_diffio_tx_b76n ;
    inout \4d_diffio_tx_b76p ;
    inout \4d_diffio_tx_b78n ;
    inout \4d_diffio_tx_b78p ;
    inout \4d_diffio_tx_b80n ;
    inout \4d_diffio_tx_b80p ;
    inout \4d_diffio_tx_b82n ;
    inout \4d_diffio_tx_b82p ;
    inout \4d_io_ad17 ;
    inout \4d_io_ae17 ;
    inout \7a_clk12n_diffio_rx_t1n ;
    inout \7a_clk12p_diffio_rx_t1p ;
    inout \7a_clk13n_diffio_rx_t3n ;
    inout \7a_clk13p_diffio_rx_t3p ;
    inout \7a_clk14n_diffio_rx_t5n ;
    inout \7a_clk14p_diffio_rx_t5p ;
    inout \7a_clk15n_diffio_rx_t9n ;
    inout \7a_clk15p_diffio_rx_t9p ;
    inout \7a_crc_error ;
    inout \7a_cvp_confdone ;
    inout \7a_dev_clrn ;
    inout \7a_dev_oe ;
    inout \7a_diffio_tx_t11p ;
    inout \7a_diffio_tx_t2n ;
    inout \7a_diffio_tx_t4n ;
    inout \7a_diffio_tx_t4p ;
    inout \7a_diffio_tx_t6n ;
    inout \7a_diffio_tx_t6p ;
    inout \7a_fpll_tr_clkout0_fpll_tr_clkoutp_fpll_tr_fb0_diffio_tx_t8p ;
    inout \7a_fpll_tr_clkout1_fpll_tr_clkoutn_diffio_tx_t8n ;
    inout \7a_fpll_tr_clkout2_fpll_tr_fbp_fpll_tr_fb1_diffio_rx_t7p ;
    inout \7a_fpll_tr_clkout3_fpll_tr_fbn_diffio_rx_t7n ;
    inout \7a_init_done ;
    inout \7a_io_j6 ;
    inout \7a_io_k6 ;
    inout \7a_nceo ;
    inout \7a_nperstl0 ;
    inout \7a_pr_done ;
    inout \7a_pr_error ;
    inout \7a_pr_ready ;
    inout \7a_pr_request ;
    inout \7a_rzq_5_diffio_tx_t2p ;
    inout \7b_diffio_rx_t16n ;
    inout \7b_diffio_rx_t16p ;
    inout \7b_diffio_rx_t17n ;
    inout \7b_diffio_rx_t17p ;
    inout \7b_diffio_rx_t19n ;
    inout \7b_diffio_rx_t19p ;
    inout \7b_diffio_rx_t21n ;
    inout \7b_diffio_rx_t21p ;
    inout \7b_diffio_rx_t23n ;
    inout \7b_diffio_rx_t23p ;
    inout \7b_diffio_rx_t25n ;
    inout \7b_diffio_rx_t25p ;
    inout \7b_diffio_rx_t27n ;
    inout \7b_diffio_rx_t27p ;
    inout \7b_diffio_rx_t29n ;
    inout \7b_diffio_rx_t29p ;
    inout \7b_diffio_tx_t18n ;
    inout \7b_diffio_tx_t18p ;
    inout \7b_diffio_tx_t20n ;
    inout \7b_diffio_tx_t20p ;
    inout \7b_diffio_tx_t22n ;
    inout \7b_diffio_tx_t22p ;
    inout \7b_diffio_tx_t24n ;
    inout \7b_diffio_tx_t24p ;
    inout \7b_diffio_tx_t26n ;
    inout \7b_diffio_tx_t26p ;
    inout \7b_diffio_tx_t28n ;
    inout \7b_diffio_tx_t28p ;
    inout \7b_diffio_tx_t30n ;
    inout \7b_diffio_tx_t30p ;
    inout \7b_io_j8 ;
    inout \7b_io_k8 ;
    inout \7c_diffio_rx_t31n ;
    inout \7c_diffio_rx_t31p ;
    inout \7c_diffio_rx_t33n ;
    inout \7c_diffio_rx_t33p ;
    inout \7c_diffio_rx_t35n ;
    inout \7c_diffio_rx_t35p ;
    inout \7c_diffio_rx_t37n ;
    inout \7c_diffio_rx_t37p ;
    inout \7c_diffio_rx_t39n ;
    inout \7c_diffio_rx_t39p ;
    inout \7c_diffio_rx_t40n ;
    inout \7c_diffio_rx_t40p ;
    inout \7c_diffio_rx_t42n ;
    inout \7c_diffio_rx_t42p ;
    inout \7c_diffio_rx_t44n ;
    inout \7c_diffio_rx_t44p ;
    inout \7c_diffio_tx_t32n ;
    inout \7c_diffio_tx_t32p ;
    inout \7c_diffio_tx_t34n ;
    inout \7c_diffio_tx_t34p ;
    inout \7c_diffio_tx_t36n ;
    inout \7c_diffio_tx_t36p ;
    inout \7c_diffio_tx_t38n ;
    inout \7c_diffio_tx_t38p ;
    inout \7c_diffio_tx_t41n ;
    inout \7c_diffio_tx_t41p ;
    inout \7c_diffio_tx_t43n ;
    inout \7c_diffio_tx_t43p ;
    inout \7c_diffio_tx_t45n ;
    inout \7c_diffio_tx_t45p ;
    inout \7c_io_j13 ;
    inout \7c_io_k13 ;
    inout \7d_diffio_rx_t46p ;
    inout \7d_diffio_rx_t48n ;
    inout \7d_diffio_rx_t48p ;
    inout \7d_diffio_rx_t50n ;
    inout \7d_diffio_rx_t50p ;
    inout \7d_diffio_rx_t52n ;
    inout \7d_diffio_rx_t52p ;
    inout \7d_diffio_rx_t54n ;
    inout \7d_diffio_rx_t54p ;
    inout \7d_diffio_rx_t55n ;
    inout \7d_diffio_rx_t55p ;
    inout \7d_diffio_rx_t57n ;
    inout \7d_diffio_rx_t57p ;
    inout \7d_diffio_rx_t59n ;
    inout \7d_diffio_rx_t59p ;
    inout \7d_diffio_tx_t47n ;
    inout \7d_diffio_tx_t47p ;
    inout \7d_diffio_tx_t49n ;
    inout \7d_diffio_tx_t49p ;
    inout \7d_diffio_tx_t51n ;
    inout \7d_diffio_tx_t51p ;
    inout \7d_diffio_tx_t53n ;
    inout \7d_diffio_tx_t53p ;
    inout \7d_diffio_tx_t56n ;
    inout \7d_diffio_tx_t56p ;
    inout \7d_diffio_tx_t58n ;
    inout \7d_diffio_tx_t58p ;
    inout \7d_diffio_tx_t60n ;
    inout \7d_diffio_tx_t60p ;
    inout \7d_io_g15 ;
    inout \7d_io_j18 ;
    inout \7d_io_k18 ;
    inout \8a_clk20n_diffio_rx_t127n ;
    inout \8a_clk20p_diffio_rx_t127p ;
    inout \8a_clk21n_diffio_rx_t125n ;
    inout \8a_clk21p_diffio_rx_t125p ;
    inout \8a_clk22n_diffio_rx_t122n ;
    inout \8a_clk22p_diffio_rx_t122p ;
    inout \8a_clk23n_diffio_rx_t120n ;
    inout \8a_clk23p_diffio_rx_t120p ;
    inout \8a_conf_done ;
    inout \8a_diffio_rx_t114n ;
    inout \8a_diffio_rx_t114p ;
    inout \8a_diffio_rx_t116n ;
    inout \8a_diffio_rx_t116p ;
    inout \8a_diffio_rx_t118n ;
    inout \8a_diffio_rx_t118p ;
    inout \8a_diffio_tx_t115n ;
    inout \8a_diffio_tx_t115p ;
    inout \8a_diffio_tx_t117n ;
    inout \8a_diffio_tx_t117p ;
    inout \8a_diffio_tx_t119n ;
    inout \8a_diffio_tx_t119p ;
    inout \8a_diffio_tx_t121n ;
    inout \8a_diffio_tx_t121p ;
    inout \8a_diffio_tx_t126n ;
    inout \8a_diffio_tx_t126p ;
    inout \8a_diffio_tx_t128p ;
    inout \8a_fpll_tl_clkout0_fpll_tl_clkoutp_fpll_tl_fb0_diffio_tx_t124p ;
    inout \8a_fpll_tl_clkout1_fpll_tl_clkoutn_diffio_tx_t124n ;
    inout \8a_fpll_tl_clkout2_fpll_tl_fbp_fpll_tl_fb1_diffio_rx_t123p ;
    inout \8a_fpll_tl_clkout3_fpll_tl_fbn_diffio_rx_t123n ;
    inout \8a_io_g24 ;
    inout \8a_io_h25 ;
    inout \8a_msel0 ;
    inout \8a_msel1 ;
    inout \8a_msel2 ;
    inout \8a_msel3 ;
    inout \8a_msel4 ;
    inout \8a_nce ;
    inout \8a_nconfig ;
    inout \8a_nstatus ;
    inout \8a_rzq_6_diffio_tx_t128n ;
    inout \8d_clk16n_diffio_rx_t69n ;
    inout \8d_clk16p_diffio_rx_t69p ;
    inout \8d_clk17n_diffio_rx_t67n ;
    inout \8d_clk17p_diffio_rx_t67p ;
    inout \8d_clk18n_diffio_rx_t63n ;
    inout \8d_clk19n_diffio_rx_t61n ;
    inout \8d_clk19p_diffio_rx_t61p ;
    inout \8d_clk_18p_diffio_rx_t63p ;
    inout \8d_diffio_rx_t70n ;
    inout \8d_diffio_rx_t70p ;
    inout \8d_diffio_rx_t72n ;
    inout \8d_diffio_rx_t72p ;
    inout \8d_diffio_rx_t74n ;
    inout \8d_diffio_rx_t74p ;
    inout \8d_diffio_tx_t62n ;
    inout \8d_diffio_tx_t62p ;
    inout \8d_diffio_tx_t64n ;
    inout \8d_diffio_tx_t64p ;
    inout \8d_diffio_tx_t68n ;
    inout \8d_diffio_tx_t68p ;
    inout \8d_diffio_tx_t71n ;
    inout \8d_diffio_tx_t71p ;
    inout \8d_diffio_tx_t73n ;
    inout \8d_diffio_tx_t73p ;
    inout \8d_diffio_tx_t75n ;
    inout \8d_diffio_tx_t75p ;
    inout \8d_fpll_tc_clkout0_fpll_tc_clkoutp_fpll_tc_fb0_diffio_tx_t66p ;
    inout \8d_fpll_tc_clkout1_fpll_tc_clkoutn_diffio_tx_t66n ;
    inout \8d_fpll_tc_clkout2_fpll_tc_fbp_fpll_tc_fb1_diffio_rx_t65p ;
    inout \8d_fpll_tc_clkout3_fpll_tc_fbn_diffio_rx_t65n ;
    inout \8d_io_j21 ;
    inout \8d_io_k21 ;
    inout l0_gxb_rx_l0n_gxb_refclk_l0n;
    inout l0_gxb_rx_l0p_gxb_refclk_l0p;
    inout l0_gxb_rx_l1n_gxb_refclk_l1n;
    inout l0_gxb_rx_l1p_gxb_refclk_l1p;
    inout l0_gxb_rx_l2n_gxb_refclk_l2n;
    inout l0_gxb_rx_l2p_gxb_refclk_l2p;
    inout l0_gxb_rx_l3n_gxb_refclk_l3n;
    inout l0_gxb_rx_l3p_gxb_refclk_l3p;
    inout l0_gxb_rx_l4n_gxb_refclk_l4n;
    inout l0_gxb_rx_l4p_gxb_refclk_l4p;
    inout l0_gxb_rx_l5n_gxb_refclk_l5n;
    inout l0_gxb_rx_l5p_gxb_refclk_l5p;
    inout l0_gxb_tx_l0n;
    inout l0_gxb_tx_l0p;
    inout l0_gxb_tx_l1n;
    inout l0_gxb_tx_l1p;
    inout l0_gxb_tx_l2n;
    inout l0_gxb_tx_l2p;
    inout l0_gxb_tx_l3n;
    inout l0_gxb_tx_l3p;
    inout l0_gxb_tx_l4n;
    inout l0_gxb_tx_l4p;
    inout l0_gxb_tx_l5n;
    inout l0_gxb_tx_l5p;
    inout l0_refclk0ln;
    inout l0_refclk0lp;
    inout l0_refclk1ln;
    inout l0_refclk1lp;
    inout l1_gxb_rx_l6n_gxb_refclk_l6n;
    inout l1_gxb_rx_l6p_gxb_refclk_l6p;
    inout l1_gxb_rx_l7n_gxb_refclk_l7n;
    inout l1_gxb_rx_l7p_gxb_refclk_l7p;
    inout l1_gxb_rx_l8n_gxb_refclk_l8n;
    inout l1_gxb_rx_l8p_gxb_refclk_l8p;
    inout l1_gxb_tx_l6n;
    inout l1_gxb_tx_l6p;
    inout l1_gxb_tx_l7n;
    inout l1_gxb_tx_l7p;
    inout l1_gxb_tx_l8n;
    inout l1_gxb_tx_l8p;
    inout l1_refclk2ln;
    inout l1_refclk2lp;
    inout r0_gxb_rx_r0n_gxb_refclk_r0n;
    inout r0_gxb_rx_r0p_gxb_refclk_r0p;
    inout r0_gxb_rx_r1n_gxb_refclk_r1n;
    inout r0_gxb_rx_r1p_gxb_refclk_r1p;
    inout r0_gxb_rx_r2n_gxb_refclk_r2n;
    inout r0_gxb_rx_r2p_gxb_refclk_r2p;
    inout r0_gxb_tx_r0n;
    inout r0_gxb_tx_r0p;
    inout r0_gxb_tx_r1n;
    inout r0_gxb_tx_r1p;
    inout r0_gxb_tx_r2n;
    inout r0_gxb_tx_r2p;
    inout r0_refclk0rn;
    inout r0_refclk0rp;
    inout r1_gxb_rx_r10n_gxb_refclk_r10n;
    inout r1_gxb_rx_r10p_gxb_refclk_r10p;
    inout r1_gxb_rx_r11n_gxb_refclk_r11n;
    inout r1_gxb_rx_r11p_gxb_refclk_r11p;
    inout r1_gxb_rx_r6n_gxb_refclk_r6n;
    inout r1_gxb_rx_r6p_gxb_refclk_r6p;
    inout r1_gxb_rx_r7n_gxb_refclk_r7n;
    inout r1_gxb_rx_r7p_gxb_refclk_r7p;
    inout r1_gxb_rx_r8n_gxb_refclk_r8n;
    inout r1_gxb_rx_r8p_gxb_refclk_r8p;
    inout r1_gxb_rx_r9n_gxb_refclk_r9n;
    inout r1_gxb_rx_r9p_gxb_refclk_r9p;
    inout r1_gxb_tx_r10n;
    inout r1_gxb_tx_r10p;
    inout r1_gxb_tx_r11n;
    inout r1_gxb_tx_r11p;
    inout r1_gxb_tx_r6n;
    inout r1_gxb_tx_r6p;
    inout r1_gxb_tx_r7n;
    inout r1_gxb_tx_r7p;
    inout r1_gxb_tx_r8n;
    inout r1_gxb_tx_r8p;
    inout r1_gxb_tx_r9n;
    inout r1_gxb_tx_r9p;
    inout r1_refclk2rn;
    inout r1_refclk2rp;
    inout r1_refclk3rn;
    inout r1_refclk3rp;
    input rref_br;
    input rref_tl;


    initial
        begin
        end

endmodule
