-- generated by newgenasym Tue Sep 14 12:12:56 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc74vhc1gt126 is
    port (    
	\in\:      IN     STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end mc74vhc1gt126;
