// generated by newgenasym  Thu Dec 23 09:12:52 2004


module fan2503s (en, \err* , gnd, in, vout);
    input en;
    output \err* ;
    input gnd;
    input in;
    output vout;


    initial
        begin
        end

endmodule
