-- generated by newgenasym Tue Jul 04 17:01:58 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity QUARZ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end QUARZ;
