// generated by newgenasym  Thu Aug 07 18:37:42 2014


module \asp-134486-01-v2  (clk0_m2c_p, clk1_m2c_p, clk2_bidir_p, clk3_bidir_p,
        clk_dir, dp0_c2m_p, dp0_m2c_p, dp1_c2m_p, dp1_m2c_p,
        dp2_c2m_p, dp2_m2c_p, dp3_c2m_p, dp3_m2c_p, dp4_c2m_p,
        dp4_m2c_p, dp5_c2m_p, dp5_m2c_p, dp6_c2m_p, dp6_m2c_p,
        dp7_c2m_p, dp7_m2c_p, dp8_c2m_p, dp8_m2c_p, dp9_c2m_p,
        dp9_m2c_p, ga0, ga1, gbt_clk0_m2c_p, gbtclk1_m2c_p,
        ha00_c_cc, ha00_p_cc, ha01_n_cc, ha01_p_cc, ha02_p, ha03_p,
        ha04_p, ha05_p, ha06_p, ha07_p, ha08_p, ha09_p, ha10_p,
        ha11_p, ha12_p, ha13_p, ha14_p, ha15_p, ha16_p, ha17_n_cc,
        ha17_p_cc, ha18_p, ha19_p, ha20_p, ha21_p, ha22_p, ha23_p,
        hb00_n_cc, hb00_p_cc, hb01_p, hb02_p, hb03_p, hb04_p,
        hb05_p, hb06_n_cc, hb06_p_cc, hb07_p, hb08_p, hb09_p,
        hb10_p, hb11_p, hb12_p, hb13_p, hb14_p, hb15_p, hb16_p,
        hb17_n_cc, hb17_p_cc, hb18_p, hb19_p, hb20_p, hb21_p,
        la00_n__cc, la00_p__cc, la01_n_cc, la01_p_cc, la02_p,
        la03_p, la04_p, la05_p, la06_p, la07_p, la08_p, la09_p,
        la10_p, la11_p, la12_p, la13_p, la14_p, la15_p, la16_p,
        la17_n_cc, la17_p_cc, la18_n_cc, la18_p_cc, la19_p, la20_p,
        la21_p, la22_p, la23_p, la24_p, la25_p, la26_p, la27_p,
        la28_p, la29_p, la30_p, la31_p, la32_p, la33_p, pg_c2m,
        pg_m2c, prstn_m2c_l, res0, scl, sda, tck, tdi, tdo, tms,
        trst_l, vio_b_m2c, vio_b_m2c2, vref_a_m2c, vref_b_m2c);
    inout clk0_m2c_p;
    inout clk1_m2c_p;
    inout clk2_bidir_p;
    inout clk3_bidir_p;
    inout clk_dir;
    inout dp0_c2m_p;
    inout dp0_m2c_p;
    inout dp1_c2m_p;
    inout dp1_m2c_p;
    inout dp2_c2m_p;
    inout dp2_m2c_p;
    inout dp3_c2m_p;
    inout dp3_m2c_p;
    inout dp4_c2m_p;
    inout dp4_m2c_p;
    inout dp5_c2m_p;
    inout dp5_m2c_p;
    inout dp6_c2m_p;
    inout dp6_m2c_p;
    inout dp7_c2m_p;
    inout dp7_m2c_p;
    inout dp8_c2m_p;
    inout dp8_m2c_p;
    inout dp9_c2m_p;
    inout dp9_m2c_p;
    inout ga0;
    inout ga1;
    inout gbt_clk0_m2c_p;
    inout gbtclk1_m2c_p;
    inout ha00_c_cc;
    inout ha00_p_cc;
    inout ha01_n_cc;
    inout ha01_p_cc;
    inout ha02_p;
    inout ha03_p;
    inout ha04_p;
    inout ha05_p;
    inout ha06_p;
    inout ha07_p;
    inout ha08_p;
    inout ha09_p;
    inout ha10_p;
    inout ha11_p;
    inout ha12_p;
    inout ha13_p;
    inout ha14_p;
    inout ha15_p;
    inout ha16_p;
    inout ha17_n_cc;
    inout ha17_p_cc;
    inout ha18_p;
    inout ha19_p;
    inout ha20_p;
    inout ha21_p;
    inout ha22_p;
    inout ha23_p;
    inout hb00_n_cc;
    inout hb00_p_cc;
    inout hb01_p;
    inout hb02_p;
    inout hb03_p;
    inout hb04_p;
    inout hb05_p;
    inout hb06_n_cc;
    inout hb06_p_cc;
    inout hb07_p;
    inout hb08_p;
    inout hb09_p;
    inout hb10_p;
    inout hb11_p;
    inout hb12_p;
    inout hb13_p;
    inout hb14_p;
    inout hb15_p;
    inout hb16_p;
    inout hb17_n_cc;
    inout hb17_p_cc;
    inout hb18_p;
    inout hb19_p;
    inout hb20_p;
    inout hb21_p;
    inout la00_n__cc;
    inout la00_p__cc;
    inout la01_n_cc;
    inout la01_p_cc;
    inout la02_p;
    inout la03_p;
    inout la04_p;
    inout la05_p;
    inout la06_p;
    inout la07_p;
    inout la08_p;
    inout la09_p;
    inout la10_p;
    inout la11_p;
    inout la12_p;
    inout la13_p;
    inout la14_p;
    inout la15_p;
    inout la16_p;
    inout la17_n_cc;
    inout la17_p_cc;
    inout la18_n_cc;
    inout la18_p_cc;
    inout la19_p;
    inout la20_p;
    inout la21_p;
    inout la22_p;
    inout la23_p;
    inout la24_p;
    inout la25_p;
    inout la26_p;
    inout la27_p;
    inout la28_p;
    inout la29_p;
    inout la30_p;
    inout la31_p;
    inout la32_p;
    inout la33_p;
    inout pg_c2m;
    inout pg_m2c;
    inout prstn_m2c_l;
    inout res0;
    inout scl;
    inout sda;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout trst_l;
    inout vio_b_m2c;
    inout vio_b_m2c2;
    inout vref_a_m2c;
    inout vref_b_m2c;


    initial
        begin
        end

endmodule
