-- generated by newgenasym Tue Aug 31 18:24:11 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity qse_qte_020 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	GND:       INOUT  STD_LOGIC);
end qse_qte_020;
