-- generated by newgenasym Wed Aug 20 18:43:53 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc580st89 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end hmc580st89;
