-- generated by newgenasym Mon Sep 08 14:58:30 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity b82799co is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC);
end b82799co;
