// generated by newgenasym  Thu Dec 09 15:20:53 2004


module am29lv128_e (a, \byte* , \ce* , dq, dq15_a, \oe* , \reset* , rfu, ry_byn, vio, \we* ,
        wpn_acc);
    input [22:0] a;
    input \byte* ;
    input \ce* ;
    inout [14:0] dq;
    inout dq15_a;
    input \oe* ;
    input \reset* ;
    inout rfu;
    output ry_byn;
    input vio;
    input \we* ;
    input wpn_acc;


    initial
        begin
        end

endmodule
