-- generated by newgenasym Thu Dec 09 15:20:53 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity am29lv128_e is
    port (    
	A:         IN     STD_LOGIC_VECTOR (22 DOWNTO 0);    
	\byte*\:   IN     STD_LOGIC;    
	\ce*\:     IN     STD_LOGIC;    
	DQ:        INOUT  STD_LOGIC_VECTOR (14 DOWNTO 0);    
	DQ15_A:    INOUT  STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	RFU:       INOUT  STD_LOGIC;    
	RY_BYN:    OUT    STD_LOGIC;    
	VIO:       IN     STD_LOGIC;    
	\we*\:     IN     STD_LOGIC;    
	WPN_ACC:   IN     STD_LOGIC);
end am29lv128_e;
