-- generated by newgenasym Fri Dec 16 12:26:03 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity stm32f030f is
    port (    
	BOOT0:     INOUT  STD_LOGIC;    
	NRST:      INOUT  STD_LOGIC;    
	PA0:       INOUT  STD_LOGIC;    
	PA1:       INOUT  STD_LOGIC;    
	PA10:      INOUT  STD_LOGIC;    
	PA13:      INOUT  STD_LOGIC;    
	PA14:      INOUT  STD_LOGIC;    
	PA2:       INOUT  STD_LOGIC;    
	PA3:       INOUT  STD_LOGIC;    
	PA4:       INOUT  STD_LOGIC;    
	PA5:       INOUT  STD_LOGIC;    
	PA6:       INOUT  STD_LOGIC;    
	PA7:       INOUT  STD_LOGIC;    
	PA9:       INOUT  STD_LOGIC;    
	PB1:       INOUT  STD_LOGIC;    
	PF0_OSCIN: INOUT  STD_LOGIC;    
	PF1_OSCO:  INOUT  STD_LOGIC);
end stm32f030f;
