// generated by newgenasym  Mon Jun 05 17:16:48 2006


module \bnx012-01  (b, cb, cg, psg);
    input b;
    output cb;
    output cg;
    input psg;


    initial
        begin
        end

endmodule
