-- generated by newgenasym Mon Jun 05 17:16:48 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bnx012-01\ is
    port (    
	B:         IN     STD_LOGIC;    
	CB:        OUT    STD_LOGIC;    
	CG:        OUT    STD_LOGIC;    
	PSG:       IN     STD_LOGIC);
end \bnx012-01\;
