-- generated by newgenasym Tue Nov 14 13:26:35 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AT45DB321 is
    port (    
	\cs*\:     INOUT  STD_LOGIC;    
	\rdy/busy\: INOUT  STD_LOGIC;    
	\reset*\:  INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SI:        INOUT  STD_LOGIC;    
	SO:        INOUT  STD_LOGIC;    
	\wp*\:     INOUT  STD_LOGIC);
end AT45DB321;
