-- generated by newgenasym Thu Dec 04 14:22:16 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity b827 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC);
end b827;
