// generated by newgenasym  Mon Apr 22 15:50:28 2013


module \tbu-p40-g  (in1, in2, out1, out2);
    inout in1;
    inout in2;
    inout out1;
    inout out2;


    initial
        begin
        end

endmodule
