// generated by newgenasym  Tue May 02 10:34:31 2017


module \1324rs1  (en, \in* , in_p, \out* , out_p);
    inout en;
    inout \in* ;
    inout in_p;
    inout \out* ;
    inout out_p;


    initial
        begin
        end

endmodule
