// generated by newgenasym  Fri Jul 07 18:17:29 2006


module jtag (gnd, tck, tdi, tdo, tms, vref);
    inout [6:0] gnd;
    input tck;
    input tdi;
    output tdo;
    input tms;
    input vref;


    initial
        begin
        end

endmodule
