-- generated by newgenasym Wed Dec 13 11:38:25 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1636pp3u\ is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A10:       INOUT  STD_LOGIC;    
	A11:       INOUT  STD_LOGIC;    
	A12:       INOUT  STD_LOGIC;    
	A13:       INOUT  STD_LOGIC;    
	A14:       INOUT  STD_LOGIC;    
	A15:       INOUT  STD_LOGIC;    
	A16:       INOUT  STD_LOGIC;    
	A17:       INOUT  STD_LOGIC;    
	A18:       INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	A9:        INOUT  STD_LOGIC;    
	A9_HV:     INOUT  STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	D6:        INOUT  STD_LOGIC;    
	D7:        INOUT  STD_LOGIC;    
	MRST:      INOUT  STD_LOGIC;    
	NCE:       INOUT  STD_LOGIC;    
	NOE:       INOUT  STD_LOGIC;    
	NWE:       INOUT  STD_LOGIC;    
	OE_HV:     INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SEL_SPI:   INOUT  STD_LOGIC;    
	SI:        INOUT  STD_LOGIC;    
	SO:        INOUT  STD_LOGIC;    
	STROBE:    INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC);
end \1636pp3u\;
