// generated by newgenasym  Fri Aug 03 13:27:27 2007


module xp02 (\0vm , \3 , \34 , reset);
    inout \0vm ;
    inout \3 ;
    inout \34 ;
    inout reset;


    initial
        begin
        end

endmodule
