-- generated by newgenasym Fri Aug 03 13:27:27 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XP02 is
    port (    
	\0vm\:     INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\34\:      INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC);
end XP02;
