// generated by newgenasym  Wed May 03 15:38:41 2017


module fin1104 (en, \en- , \in1+ , \in1- , \in2+ , \in2- , \in3+ , \in3- , \in4+ , \in4- , \out1+ ,
        \out1- , \out2+ , \out2- , \out3+ , \out3- , \out4+ , \out4- , vbb);
    inout en;
    inout \en- ;
    inout \in1+ ;
    inout \in1- ;
    inout \in2+ ;
    inout \in2- ;
    inout \in3+ ;
    inout \in3- ;
    inout \in4+ ;
    inout \in4- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out2+ ;
    inout \out2- ;
    inout \out3+ ;
    inout \out3- ;
    inout \out4+ ;
    inout \out4- ;
    inout vbb;


    initial
        begin
        end

endmodule
