-- generated by newgenasym Wed May 03 15:38:41 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fin1104 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	\en-\:     INOUT  STD_LOGIC;    
	\in1+\:    INOUT  STD_LOGIC;    
	\in1-\:    INOUT  STD_LOGIC;    
	\in2+\:    INOUT  STD_LOGIC;    
	\in2-\:    INOUT  STD_LOGIC;    
	\in3+\:    INOUT  STD_LOGIC;    
	\in3-\:    INOUT  STD_LOGIC;    
	\in4+\:    INOUT  STD_LOGIC;    
	\in4-\:    INOUT  STD_LOGIC;    
	\out1+\:   INOUT  STD_LOGIC;    
	\out1-\:   INOUT  STD_LOGIC;    
	\out2+\:   INOUT  STD_LOGIC;    
	\out2-\:   INOUT  STD_LOGIC;    
	\out3+\:   INOUT  STD_LOGIC;    
	\out3-\:   INOUT  STD_LOGIC;    
	\out4+\:   INOUT  STD_LOGIC;    
	\out4-\:   INOUT  STD_LOGIC;    
	VBB:       INOUT  STD_LOGIC);
end fin1104;
