-- generated by newgenasym Wed Jul 21 15:28:54 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g17_1 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GNDDM:     IN     STD_LOGIC;    
	P3V3M:     IN     STD_LOGIC;    
	Y1:        OUT    STD_LOGIC;    
	Y2:        OUT    STD_LOGIC);
end sn74lvc2g17_1;
