// generated by newgenasym  Wed Aug 15 10:34:23 2018


module adf4351 (ce, clk, cpout, data, ld, le, muxout, pdbrf, ref_in, rfout_an,
        rfout_ap, rfout_bn, rfout_bp, rset, sw, temp, vcom, vref,
        vtune);
    inout ce;
    inout clk;
    inout cpout;
    inout data;
    inout ld;
    inout le;
    inout muxout;
    inout pdbrf;
    inout ref_in;
    inout rfout_an;
    inout rfout_ap;
    inout rfout_bn;
    inout rfout_bp;
    inout rset;
    inout sw;
    inout temp;
    inout vcom;
    inout vref;
    inout vtune;


    initial
        begin
        end

endmodule
