-- generated by newgenasym Wed Aug 15 10:34:23 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adf4351 is
    port (    
	CE:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CPOUT:     INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	LD:        INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	MUXOUT:    INOUT  STD_LOGIC;    
	PDBRF:     INOUT  STD_LOGIC;    
	REF_IN:    INOUT  STD_LOGIC;    
	RFOUT_AN:  INOUT  STD_LOGIC;    
	RFOUT_AP:  INOUT  STD_LOGIC;    
	RFOUT_BN:  INOUT  STD_LOGIC;    
	RFOUT_BP:  INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	TEMP:      INOUT  STD_LOGIC;    
	VCOM:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VTUNE:     INOUT  STD_LOGIC);
end adf4351;
