// generated by newgenasym  Wed Mar 21 15:11:39 2007


module cwf_10 (adc0, adc1, adc2, gnd1, gnd2, gnd3, gnd4, \int* , scl, sda);
    inout adc0;
    inout adc1;
    inout adc2;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout \int* ;
    inout scl;
    inout sda;


    initial
        begin
        end

endmodule
