-- generated by newgenasym Wed Mar 21 15:11:39 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CWF_10 is
    port (    
	ADC0:      INOUT  STD_LOGIC;    
	ADC1:      INOUT  STD_LOGIC;    
	ADC2:      INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	\int*\:    INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end CWF_10;
