// generated by newgenasym  Tue Aug 22 16:09:01 2017


module tps7a8300 (\1.6v , \100mv , \200mv , \400mv , \50mv , \800mv , bias, en, fb, in1, in2,
        in3, \nr/ss , out1, out2, out3, pg, sns);
    inout \1.6v ;
    inout \100mv ;
    inout \200mv ;
    inout \400mv ;
    inout \50mv ;
    inout \800mv ;
    inout bias;
    inout en;
    inout fb;
    inout in1;
    inout in2;
    inout in3;
    inout \nr/ss ;
    inout out1;
    inout out2;
    inout out3;
    inout pg;
    inout sns;


    initial
        begin
        end

endmodule
