-- generated by newgenasym Tue Aug 22 16:09:01 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps7a8300 is
    port (    
	\1.6v\:    INOUT  STD_LOGIC;    
	\100mv\:   INOUT  STD_LOGIC;    
	\200mv\:   INOUT  STD_LOGIC;    
	\400mv\:   INOUT  STD_LOGIC;    
	\50mv\:    INOUT  STD_LOGIC;    
	\800mv\:   INOUT  STD_LOGIC;    
	BIAS:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	\nr/ss\:   INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	SNS:       INOUT  STD_LOGIC);
end tps7a8300;
