-- generated by newgenasym Wed Sep 13 13:06:03 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc580st89 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end hmc580st89;
