// generated by newgenasym  Fri Dec 09 16:27:48 2011


module adf4001 (ce, clk, cp, data, le, muxout, refin, rfina, rfinb, rset, vp);
    inout ce;
    inout clk;
    inout cp;
    inout data;
    inout le;
    inout muxout;
    inout refin;
    inout rfina;
    inout rfinb;
    inout rset;
    inout vp;


    initial
        begin
        end

endmodule
