// generated by newgenasym  Mon May 22 17:16:28 2017


module adclk946 (clk, clk_n, q0_n, q0_p, q1_n, q1_p, q2_n, q2_p, q3_n, q3_p,
        q4_n, q4_p, q5_n, q5_p, vref, vt);
    inout clk;
    inout clk_n;
    inout q0_n;
    inout q0_p;
    inout q1_n;
    inout q1_p;
    inout q2_n;
    inout q2_p;
    inout q3_n;
    inout q3_p;
    inout q4_n;
    inout q4_p;
    inout q5_n;
    inout q5_p;
    inout vref;
    inout vt;


    initial
        begin
        end

endmodule
