-- generated by newgenasym Mon May 22 17:16:28 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adclk946 is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	CLK_N:     INOUT  STD_LOGIC;    
	Q0_N:      INOUT  STD_LOGIC;    
	Q0_P:      INOUT  STD_LOGIC;    
	Q1_N:      INOUT  STD_LOGIC;    
	Q1_P:      INOUT  STD_LOGIC;    
	Q2_N:      INOUT  STD_LOGIC;    
	Q2_P:      INOUT  STD_LOGIC;    
	Q3_N:      INOUT  STD_LOGIC;    
	Q3_P:      INOUT  STD_LOGIC;    
	Q4_N:      INOUT  STD_LOGIC;    
	Q4_P:      INOUT  STD_LOGIC;    
	Q5_N:      INOUT  STD_LOGIC;    
	Q5_P:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VT:        INOUT  STD_LOGIC);
end adclk946;
