// generated by newgenasym  Wed Oct 31 12:01:12 2018


module lp38500sd_adj (adj, in1, in2, in3, out1, out2, out3);
    inout adj;
    inout in1;
    inout in2;
    inout in3;
    inout out1;
    inout out2;
    inout out3;


    initial
        begin
        end

endmodule
