-- generated by newgenasym Wed Oct 31 12:01:12 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lp38500sd_adj is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC);
end lp38500sd_adj;
