// generated by newgenasym  Tue Dec 15 17:24:32 2009


module sn74lvcc3245 (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8, dir,
        gnd, gnd1, gnd2, nc, \oe# , vcca, vccb);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout dir;
    inout gnd;
    inout gnd1;
    inout gnd2;
    inout nc;
    inout \oe# ;
    inout vcca;
    inout vccb;


    initial
        begin
        end

endmodule
