-- generated by newgenasym Thu Aug 16 16:15:33 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pat is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end pat;
