-- generated by newgenasym Wed Apr 21 13:50:21 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \521_9450\ is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC);
end \521_9450\;
