// generated by newgenasym  Wed Nov 12 15:20:23 2003


module \564ln2  (\1 , \10* , \11 , \12* , \13 , \2* , \3 , \4* , \5 , \6* , \8* , \9 );
    input \1 ;
    output \10* ;
    input \11 ;
    output \12* ;
    input \13 ;
    output \2* ;
    input \3 ;
    output \4* ;
    input \5 ;
    output \6* ;
    output \8* ;
    input \9 ;


    initial
        begin
        end

endmodule
