-- generated by newgenasym Wed Nov 12 15:20:23 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \564ln2\ is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10*\:     OUT    STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12*\:     OUT    STD_LOGIC;    
	\13\:      IN     STD_LOGIC;    
	\2*\:      OUT    STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4*\:      OUT    STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6*\:      OUT    STD_LOGIC;    
	\8*\:      OUT    STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end \564ln2\;
