// generated by newgenasym  Tue Mar 09 15:59:10 2010


module ds90c402m (gnd, \ri1+ , \ri1- , \ri2+ , \ri2- , ro1, ro2, vcc);
    inout gnd;
    inout \ri1+ ;
    inout \ri1- ;
    inout \ri2+ ;
    inout \ri2- ;
    inout ro1;
    inout ro2;
    inout vcc;


    initial
        begin
        end

endmodule
