-- generated by newgenasym Tue Mar 09 15:59:10 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90c402m is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\ri1+\:    INOUT  STD_LOGIC;    
	\ri1-\:    INOUT  STD_LOGIC;    
	\ri2+\:    INOUT  STD_LOGIC;    
	\ri2-\:    INOUT  STD_LOGIC;    
	RO1:       INOUT  STD_LOGIC;    
	RO2:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ds90c402m;
