// generated by newgenasym  Fri Mar 18 11:05:17 2016


module ad9956 (cp_out, cp_rset, \cs* , dac_rset, \drv* , drv_p, drv_rset,
        \i/o_reset , \i/o_update , iout, \iout* , \pllosc* , pllosc_p,
        \pllref* , pllref_p, ps0, ps1, ps2, \refclk* , refclk_p, reset,
        sclk, \sdi/o , sdo, sync_in, sync_out);
    output cp_out;
    inout cp_rset;
    input \cs* ;
    inout dac_rset;
    output \drv* ;
    output drv_p;
    inout drv_rset;
    inout \i/o_reset ;
    input \i/o_update ;
    inout iout;
    inout \iout* ;
    input \pllosc* ;
    input pllosc_p;
    input \pllref* ;
    input pllref_p;
    input ps0;
    input ps1;
    input ps2;
    input \refclk* ;
    input refclk_p;
    inout reset;
    input sclk;
    inout \sdi/o ;
    output sdo;
    inout sync_in;
    inout sync_out;


    initial
        begin
        end

endmodule
