// generated by newgenasym  Mon Sep 27 11:07:02 2004


module qs3vh257 (\e* , gndd, i0a, i0b, i0c, i0d, i1a, i1b, i1c, i1d, p3v3, s, ya, yb,
        yc, yd);
    input \e* ;
    input gndd;
    inout i0a;
    inout i0b;
    inout i0c;
    inout i0d;
    inout i1a;
    inout i1b;
    inout i1c;
    inout i1d;
    input p3v3;
    input s;
    inout ya;
    inout yb;
    inout yc;
    inout yd;


    initial
        begin
        end

endmodule
