-- generated by newgenasym Mon Sep 27 11:07:02 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity QS3VH257 is
    port (    
	\e*\:      IN     STD_LOGIC;    
	GNDD:      IN     STD_LOGIC;    
	I0A:       INOUT  STD_LOGIC;    
	I0B:       INOUT  STD_LOGIC;    
	I0C:       INOUT  STD_LOGIC;    
	I0D:       INOUT  STD_LOGIC;    
	I1A:       INOUT  STD_LOGIC;    
	I1B:       INOUT  STD_LOGIC;    
	I1C:       INOUT  STD_LOGIC;    
	I1D:       INOUT  STD_LOGIC;    
	P3V3:      IN     STD_LOGIC;    
	S:         IN     STD_LOGIC;    
	YA:        INOUT  STD_LOGIC;    
	YB:        INOUT  STD_LOGIC;    
	YC:        INOUT  STD_LOGIC;    
	YD:        INOUT  STD_LOGIC);
end QS3VH257;
