-- generated by newgenasym Thu Aug 12 13:03:03 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \smox/060/b1\ is
    port (    
	X:         INOUT  STD_LOGIC);
end \smox/060/b1\;
