// generated by newgenasym  Thu Apr 10 12:36:53 2003


module \1002xl1  (clcr, clct, clr, crl, d1, d2, d3, d4, d5, d6, d7, d8, da, dar, de,
        eint, epe, eze, ezr, fe, pe, pi, q1, q2, q3, q4, q5, q6, q7, q8, qp,
        sbs, sdi, sdo, str, stsp, thre, tsre, wls1, wls2);
    input clcr;
    input clct;
    input clr;
    input crl;
    input d1;
    input d2;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input d8;
    output da;
    input dar;
    output de;
    input eint;
    input epe;
    input eze;
    input ezr;
    output fe;
    output pe;
    input pi;
    output q1;
    output q2;
    output q3;
    output q4;
    output q5;
    output q6;
    output q7;
    output q8;
    output qp;
    input sbs;
    input sdi;
    output sdo;
    input str;
    output stsp;
    output thre;
    output tsre;
    input wls1;
    input wls2;


    initial
        begin
        end

endmodule
