-- generated by newgenasym Thu Apr 10 12:36:53 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1002xl1\ is
    port (    
	CLCR:      IN     STD_LOGIC;    
	CLCT:      IN     STD_LOGIC;    
	CLR:       IN     STD_LOGIC;    
	CRL:       IN     STD_LOGIC;    
	D1:        IN     STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        IN     STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        IN     STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        IN     STD_LOGIC;    
	D8:        IN     STD_LOGIC;    
	DA:        OUT    STD_LOGIC;    
	DAR:       IN     STD_LOGIC;    
	DE:        OUT    STD_LOGIC;    
	EINT:      IN     STD_LOGIC;    
	EPE:       IN     STD_LOGIC;    
	EZE:       IN     STD_LOGIC;    
	EZR:       IN     STD_LOGIC;    
	FE:        OUT    STD_LOGIC;    
	PE:        OUT    STD_LOGIC;    
	PI:        IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	Q8:        OUT    STD_LOGIC;    
	QP:        OUT    STD_LOGIC;    
	SBS:       IN     STD_LOGIC;    
	SDI:       IN     STD_LOGIC;    
	SDO:       OUT    STD_LOGIC;    
	STR:       IN     STD_LOGIC;    
	STSP:      OUT    STD_LOGIC;    
	THRE:      OUT    STD_LOGIC;    
	TSRE:      OUT    STD_LOGIC;    
	WLS1:      IN     STD_LOGIC;    
	WLS2:      IN     STD_LOGIC);
end \1002xl1\;
