// generated by newgenasym  Mon Jul 29 11:24:34 2013


module pex8311 (\ads# , \bar0enb# , \bd_sel# , \bigend# , \blast# , breqi, breqo,
        \bterm# , bton, bunri, \ccs# , clkin, clkout, \dack#0 , \dack#1 ,
        \dmpaf/eot# , dp0, dp1, dp2, dp3, dreq0, dreq1, eeclk, eecs,
        \eecs# , \eedi/do , eerdata, eesk, eewrdata, gpio0, gpio1, gpio2,
        gpio3, \iddqen# , itdo, la, lbe, lclk, ld, lhold, lholda, \linti# ,
        \linto# , \lreset# , \lserr# , \lw/r# , mode0, mode1, nct4, pern0,
        perp0, \perst# , petn0, petp0, plxt1, plxt2, \pmein# , \pmeout# ,
        pwr_ok, \ready# , \refclk+ , \refclk- , \root_complex# , smc, tck,
        tdi, tdo, test, tmc, tmc1, tmc2, tms, \trst# , \useri/llocki# ,
        \usero/llocko# , \wait# , \wakein# , \wakeout# );
    inout \ads# ;
    input \bar0enb# ;
    input \bd_sel# ;
    input \bigend# ;
    inout \blast# ;
    input breqi;
    output breqo;
    inout \bterm# ;
    input bton;
    input bunri;
    input \ccs# ;
    input clkin;
    output clkout;
    inout \dack#0 ;
    inout \dack#1 ;
    inout \dmpaf/eot# ;
    inout dp0;
    inout dp1;
    inout dp2;
    inout dp3;
    input dreq0;
    input dreq1;
    inout eeclk;
    inout eecs;
    inout \eecs# ;
    inout \eedi/do ;
    inout eerdata;
    inout eesk;
    inout eewrdata;
    inout gpio0;
    inout gpio1;
    inout gpio2;
    inout gpio3;
    input \iddqen# ;
    inout itdo;
    inout [31:2] la;
    inout [3:0] lbe;
    input lclk;
    inout [31:0] ld;
    output lhold;
    input lholda;
    input \linti# ;
    output \linto# ;
    inout \lreset# ;
    output \lserr# ;
    inout \lw/r# ;
    input mode0;
    input mode1;
    inout nct4;
    input pern0;
    input perp0;
    inout \perst# ;
    output petn0;
    output petp0;
    input plxt1;
    input plxt2;
    input \pmein# ;
    output \pmeout# ;
    output pwr_ok;
    inout \ready# ;
    input \refclk+ ;
    input \refclk- ;
    input \root_complex# ;
    input smc;
    inout tck;
    inout tdi;
    inout tdo;
    input test;
    input tmc;
    input tmc1;
    input tmc2;
    inout tms;
    inout \trst# ;
    input \useri/llocki# ;
    output \usero/llocko# ;
    inout \wait# ;
    input \wakein# ;
    inout \wakeout# ;


    initial
        begin
        end

endmodule
