// generated by newgenasym  Fri May 28 14:54:07 2004


module msa_2111 (rf_in, rf_out, shield1, shield2);
    input rf_in;
    output rf_out;
    input shield1;
    input shield2;


    initial
        begin
        end

endmodule
