-- generated by newgenasym Mon Feb 21 16:08:18 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ten40_2412wi is
    port (    
	\+sense\:  INOUT  STD_LOGIC;    
	\+vin\:    INOUT  STD_LOGIC;    
	\+vout\:   INOUT  STD_LOGIC;    
	\-sense\:  INOUT  STD_LOGIC;    
	\-vin\:    INOUT  STD_LOGIC;    
	\-vout\:   INOUT  STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC);
end ten40_2412wi;
