// generated by newgenasym  Fri Nov 19 13:53:15 2004


module cdp68hc68p1m (\ce* , d0, d1, d2, d3, d4, d5, d6, d7, id0, id1, miso, mosi, sck,
        vdd, vss);
    input \ce* ;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    input id0;
    input id1;
    output miso;
    input mosi;
    input sck;
    input vdd;
    input vss;


    initial
        begin
        end

endmodule
