// generated by newgenasym  Tue Jun 29 10:33:57 2004


module max5382l_1 (gndd, out, p3v3, scl, sda);
    input gndd;
    output out;
    input p3v3;
    input scl;
    inout sda;


    initial
        begin
        end

endmodule
