-- generated by newgenasym Tue Jun 29 10:33:57 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max5382l_1 is
    port (    
	GNDD:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	P3V3:      IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end max5382l_1;
