-- generated by newgenasym Mon Oct 23 13:32:14 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tc2-72t\ is
    port (    
	PRI:       INOUT  STD_LOGIC;    
	\pri dot\: INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	\sec ct\:  INOUT  STD_LOGIC;    
	\sec dot\: INOUT  STD_LOGIC);
end \tc2-72t\;
