-- generated by newgenasym Thu Nov 27 17:48:32 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PLATA1 is
    port (    
	\2\:       IN     std_logic;    
	\4\:       IN     std_logic;    
	\5\:       IN     std_logic;    
	\7\:       OUT    std_logic;    
	\9\:       OUT    std_logic);
end PLATA1;
