// generated by newgenasym  Thu Jan 10 14:59:31 2008


module ad9480 (\clk+ , \clk- , d0_c, d0_t, d1_c, d1_t, d2_c, d2_t, d3_c, d3_t,
        d4_c, d4_t, d5_c, d5_t, d6_c, d6_t, d7_c, d7_t, \dco+ , \dco- ,
        lvdsbias, pwdn, s1, sense, \vin+ , \vin- , vref);
    inout \clk+ ;
    inout \clk- ;
    inout d0_c;
    inout d0_t;
    inout d1_c;
    inout d1_t;
    inout d2_c;
    inout d2_t;
    inout d3_c;
    inout d3_t;
    inout d4_c;
    inout d4_t;
    inout d5_c;
    inout d5_t;
    inout d6_c;
    inout d6_t;
    inout d7_c;
    inout d7_t;
    inout \dco+ ;
    inout \dco- ;
    inout lvdsbias;
    inout pwdn;
    inout s1;
    inout sense;
    inout \vin+ ;
    inout \vin- ;
    inout vref;


    initial
        begin
        end

endmodule
