-- generated by newgenasym Thu Jan 10 14:59:31 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD9480 is
    port (    
	\clk+\:    INOUT  STD_LOGIC;    
	\clk-\:    INOUT  STD_LOGIC;    
	D0_C:      INOUT  STD_LOGIC;    
	D0_T:      INOUT  STD_LOGIC;    
	D1_C:      INOUT  STD_LOGIC;    
	D1_T:      INOUT  STD_LOGIC;    
	D2_C:      INOUT  STD_LOGIC;    
	D2_T:      INOUT  STD_LOGIC;    
	D3_C:      INOUT  STD_LOGIC;    
	D3_T:      INOUT  STD_LOGIC;    
	D4_C:      INOUT  STD_LOGIC;    
	D4_T:      INOUT  STD_LOGIC;    
	D5_C:      INOUT  STD_LOGIC;    
	D5_T:      INOUT  STD_LOGIC;    
	D6_C:      INOUT  STD_LOGIC;    
	D6_T:      INOUT  STD_LOGIC;    
	D7_C:      INOUT  STD_LOGIC;    
	D7_T:      INOUT  STD_LOGIC;    
	\dco+\:    INOUT  STD_LOGIC;    
	\dco-\:    INOUT  STD_LOGIC;    
	LVDSBIAS:  INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end AD9480;
