// generated by newgenasym  Fri Jul 20 11:30:30 2007


module ad8313 (comm, inhi, inlo, pwdn, vout, vpos, vpos2, vset);
    inout comm;
    inout inhi;
    inout inlo;
    inout pwdn;
    inout vout;
    inout vpos;
    inout vpos2;
    inout vset;


    initial
        begin
        end

endmodule
