-- generated by newgenasym Fri Jul 20 11:30:30 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8313 is
    port (    
	COMM:      INOUT  STD_LOGIC;    
	INHI:      INOUT  STD_LOGIC;    
	INLO:      INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VPOS:      INOUT  STD_LOGIC;    
	VPOS2:     INOUT  STD_LOGIC;    
	VSET:      INOUT  STD_LOGIC);
end ad8313;
