-- generated by newgenasym Mon Oct 20 17:01:12 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3384eeap is
    port (    
	\c1+\:     IN     STD_LOGIC;    
	\c1-\:     IN     STD_LOGIC;    
	\c2+\:     IN     STD_LOGIC;    
	\c2-\:     IN     STD_LOGIC;    
	R1IN:      IN     STD_LOGIC;    
	R1OUT:     OUT    STD_LOGIC;    
	R2IN:      IN     STD_LOGIC;    
	R2OUT:     OUT    STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC;    
	T1IN:      IN     STD_LOGIC;    
	T1OUT:     OUT    STD_LOGIC;    
	T2IN:      IN     STD_LOGIC;    
	T2OUT:     OUT    STD_LOGIC;    
	\v+\:      OUT    STD_LOGIC;    
	\v-\:      OUT    STD_LOGIC);
end max3384eeap;
