// generated by newgenasym  Tue May 15 16:17:28 2007


module adf4108 (agnd, avdd, ce, clk, cp, cpgnd, data, dgnd, dvdd, le, muxout,
        refin, rfina, rfinb, rset, vp);
    inout agnd;
    inout avdd;
    inout ce;
    inout clk;
    inout cp;
    inout cpgnd;
    inout data;
    inout dgnd;
    inout dvdd;
    inout le;
    inout muxout;
    inout refin;
    inout rfina;
    inout rfinb;
    inout rset;
    inout vp;


    initial
        begin
        end

endmodule
