-- generated by newgenasym Tue May 15 16:17:28 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADF4108 is
    port (    
	AGND:      INOUT  STD_LOGIC;    
	AVDD:      INOUT  STD_LOGIC;    
	CE:        INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CP:        INOUT  STD_LOGIC;    
	CPGND:     INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	DGND:      INOUT  STD_LOGIC;    
	DVDD:      INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	MUXOUT:    INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	RFINA:     INOUT  STD_LOGIC;    
	RFINB:     INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	VP:        INOUT  STD_LOGIC);
end ADF4108;
