// generated by newgenasym  Wed Sep 05 14:55:25 2012


module hmc624lflp4e (acg1, acg2, acg3, acg4, acg5, acg6, attin, attout, clk, d0, d1,
        d2, d3, d4, d5, le, \p/s , pup1, pup2, serin, serout);
    inout acg1;
    inout acg2;
    inout acg3;
    inout acg4;
    inout acg5;
    inout acg6;
    inout attin;
    inout attout;
    inout clk;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout le;
    inout \p/s ;
    inout pup1;
    inout pup2;
    inout serin;
    inout serout;


    initial
        begin
        end

endmodule
