-- generated by newgenasym Wed Sep 05 14:55:25 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc624lflp4e is
    port (    
	ACG1:      INOUT  STD_LOGIC;    
	ACG2:      INOUT  STD_LOGIC;    
	ACG3:      INOUT  STD_LOGIC;    
	ACG4:      INOUT  STD_LOGIC;    
	ACG5:      INOUT  STD_LOGIC;    
	ACG6:      INOUT  STD_LOGIC;    
	ATTIN:     INOUT  STD_LOGIC;    
	ATTOUT:    INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	\p/s\:     INOUT  STD_LOGIC;    
	PUP1:      INOUT  STD_LOGIC;    
	PUP2:      INOUT  STD_LOGIC;    
	SERIN:     INOUT  STD_LOGIC;    
	SEROUT:    INOUT  STD_LOGIC);
end hmc624lflp4e;
