-- generated by newgenasym Thu Nov 13 18:09:28 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sma_142_0701_551 is
    port (    
	IN1:       INOUT  STD_LOGIC);
end sma_142_0701_551;
