// generated by newgenasym  Wed Aug 20 18:00:32 2014


module adl5350 (\if , loin, rf, vpose);
    inout \if ;
    inout loin;
    inout rf;
    inout vpose;


    initial
        begin
        end

endmodule
