// generated by newgenasym  Fri Nov 20 13:16:19 2009


module isp (\+5v , led, miso, mosi, res, sck);
    inout \+5v ;
    inout led;
    inout miso;
    inout mosi;
    inout res;
    inout sck;


    initial
        begin
        end

endmodule
