-- generated by newgenasym Fri Nov 20 13:16:19 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity isp is
    port (    
	\+5v\:     INOUT  STD_LOGIC;    
	LED:       INOUT  STD_LOGIC;    
	MISO:      INOUT  STD_LOGIC;    
	MOSI:      INOUT  STD_LOGIC;    
	RES:       INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC);
end isp;
