-- generated by newgenasym Wed Aug 13 15:15:21 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1324uv1u\ is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \1324uv1u\;
