// generated by newgenasym  Fri Aug 10 14:26:03 2007


module mxocr (gnd, out, vc, vcc, vref);
    inout gnd;
    inout out;
    inout vc;
    inout vcc;
    inout vref;


    initial
        begin
        end

endmodule
