// generated by newgenasym  Thu Aug 14 11:59:27 2014


module hmc221b (a, b, rf1, rf2, rfc);
    inout a;
    inout b;
    inout rf1;
    inout rf2;
    inout rfc;


    initial
        begin
        end

endmodule
