-- generated by newgenasym Thu Aug 14 11:59:27 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc221b is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RFC:       INOUT  STD_LOGIC);
end hmc221b;
