-- generated by newgenasym Wed Aug 26 19:18:29 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity b220_a is
    port (    
	A:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end b220_a;
