// generated by newgenasym  Tue Aug 17 17:41:39 2004


module mic39101 (en, \err* , vin, vout);
    input en;
    output \err* ;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
