-- generated by newgenasym Tue Aug 17 17:41:39 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mic39101 is
    port (    
	EN:        IN     STD_LOGIC;    
	\err*\:    OUT    STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end mic39101;
