// generated by newgenasym  Wed Dec 09 11:06:36 2009


module cdcv304 (\1y0 , \1y1 , \1y2 , \1y3 , clkin, gnd, oe, \vdd_3.3v );
    inout \1y0 ;
    inout \1y1 ;
    inout \1y2 ;
    inout \1y3 ;
    inout clkin;
    inout gnd;
    inout oe;
    inout \vdd_3.3v ;


    initial
        begin
        end

endmodule
