-- generated by newgenasym Wed Dec 09 11:06:36 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cdcv304 is
    port (    
	\1y0\:     INOUT  STD_LOGIC;    
	\1y1\:     INOUT  STD_LOGIC;    
	\1y2\:     INOUT  STD_LOGIC;    
	\1y3\:     INOUT  STD_LOGIC;    
	CLKIN:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	\vdd_3.3v\: INOUT  STD_LOGIC);
end cdcv304;
