-- generated by newgenasym Mon Aug 30 12:47:52 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity qs3vh257 is
    port (    
	\e*\:      IN     STD_LOGIC;    
	I0A:       INOUT  STD_LOGIC;    
	I0B:       INOUT  STD_LOGIC;    
	I0C:       INOUT  STD_LOGIC;    
	I0D:       INOUT  STD_LOGIC;    
	I1A:       INOUT  STD_LOGIC;    
	I1B:       INOUT  STD_LOGIC;    
	I1C:       INOUT  STD_LOGIC;    
	I1D:       INOUT  STD_LOGIC;    
	S:         IN     STD_LOGIC;    
	YA:        INOUT  STD_LOGIC;    
	YB:        INOUT  STD_LOGIC;    
	YC:        INOUT  STD_LOGIC;    
	YD:        INOUT  STD_LOGIC);
end qs3vh257;
