// generated by newgenasym  Tue Jul 01 14:41:41 2003


module pkf5510si (aux, \in+ , \in- , \nor , out1, rc, rtn, sync, vadj);
    input aux;
    input \in+ ;
    input \in- ;
    input \nor ;
    output out1;
    input rc;
    output rtn;
    input sync;
    input vadj;


    initial
        begin
        end

endmodule
