-- generated by newgenasym Tue Jul 01 14:41:41 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pkf5510si is
    port (    
	AUX:       IN     STD_LOGIC;    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\nor\:     IN     STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	RC:        IN     STD_LOGIC;    
	RTN:       OUT    STD_LOGIC;    
	SYNC:      IN     STD_LOGIC;    
	VADJ:      IN     STD_LOGIC);
end pkf5510si;
