// generated by newgenasym  Thu Jan 12 13:14:26 2017


module xc6slx9 (cmpcs_b_2, done_2, io_l12n_d2_miso3_2,
        io_l12p_d1_miso2_2, io_l13n_d10_2, io_l13p_m1_2,
        io_l14n_d12_2, io_l14p_d11_2, io_l1n_m0_cmpmiso_2,
        io_l1n_vref_0, io_l1n_vref_1, io_l1n_vref_3, io_l1p_1,
        io_l1p_3, io_l1p_cclk_2, io_l1p_hswapen_0, io_l2n_0,
        io_l2n_3, io_l2n_cmpmosi_2, io_l2p_0, io_l2p_3,
        io_l2p_cmpclk_2, io_l30n_gclk0_usercclk_2,
        io_l30p_gclk1_d13_2, io_l31n_gclk30_d15_2,
        io_l31p_gclk31_d14_2, io_l32n_1, io_l32p_1, io_l33n_1,
        io_l33p_1, io_l34n_1, io_l34n_gclk18_0, io_l34p_1,
        io_l34p_gclk19_0, io_l35n_gclk16_0, io_l35p_gclk17_0,
        io_l36n_3, io_l36n_gclk14_0, io_l36p_3, io_l36p_gclk15_0,
        io_l37n_3, io_l37n_gclk12_0, io_l37p_3, io_l37p_gclk13_0,
        io_l3n_0, io_l3n_mosi_csi_b_miso0_2, io_l3p_0,
        io_l3p_d0_din_miso_miso1_2, io_l40n_gclk10_1,
        io_l40p_gclk11_1, io_l41n_gclk26_3, io_l41n_gclk8_1,
        io_l41p_gclk27_3, io_l41p_gclk9_irdy1_1,
        io_l42n_gclk24_3, io_l42n_gclk6_trdy1_1,
        io_l42p_gclk25_trdy2_3, io_l42p_gclk7_1,
        io_l43n_gclk22_irdy2_3, io_l43n_gclk4_1,
        io_l43p_gclk23_3, io_l43p_gclk5_1, io_l44n_gclk20_3,
        io_l44p_gclk21_3, io_l45n_1, io_l45p_1, io_l46n_1,
        io_l46p_1, io_l47n_1, io_l47p_1, io_l48n_rdwr_b_vref_2,
        io_l48p_d7_2, io_l49n_3, io_l49n_d4_2, io_l49p_3,
        io_l49p_d3_2, io_l4n_0, io_l4p_0, io_l50n_3, io_l50p_3,
        io_l51n_3, io_l51p_3, io_l52n_3, io_l52p_3, io_l62n_d6_2,
        io_l62n_vref_0, io_l62p_0, io_l62p_d5_2, io_l63n_scp6_0,
        io_l63p_scp7_0, io_l64n_d9_2, io_l64n_scp4_0,
        io_l64p_d8_2, io_l64p_scp5_0, io_l65n_cso_b_2,
        io_l65n_scp2_0, io_l65p_init_b_2, io_l65p_scp3_0,
        io_l66n_scp0_0, io_l66p_scp1_0, io_l74n_dout_busy_1,
        io_l74p_awake_1, io_l83n_vref_3, io_l83p_3, program_b_2,
        suspend, tck, tdi, tdo, tms);
    inout cmpcs_b_2;
    inout done_2;
    inout io_l12n_d2_miso3_2;
    inout io_l12p_d1_miso2_2;
    inout io_l13n_d10_2;
    inout io_l13p_m1_2;
    inout io_l14n_d12_2;
    inout io_l14p_d11_2;
    inout io_l1n_m0_cmpmiso_2;
    inout io_l1n_vref_0;
    inout io_l1n_vref_1;
    inout io_l1n_vref_3;
    inout io_l1p_1;
    inout io_l1p_3;
    inout io_l1p_cclk_2;
    inout io_l1p_hswapen_0;
    inout io_l2n_0;
    inout io_l2n_3;
    inout io_l2n_cmpmosi_2;
    inout io_l2p_0;
    inout io_l2p_3;
    inout io_l2p_cmpclk_2;
    inout io_l30n_gclk0_usercclk_2;
    inout io_l30p_gclk1_d13_2;
    inout io_l31n_gclk30_d15_2;
    inout io_l31p_gclk31_d14_2;
    inout io_l32n_1;
    inout io_l32p_1;
    inout io_l33n_1;
    inout io_l33p_1;
    inout io_l34n_1;
    inout io_l34n_gclk18_0;
    inout io_l34p_1;
    inout io_l34p_gclk19_0;
    inout io_l35n_gclk16_0;
    inout io_l35p_gclk17_0;
    inout io_l36n_3;
    inout io_l36n_gclk14_0;
    inout io_l36p_3;
    inout io_l36p_gclk15_0;
    inout io_l37n_3;
    inout io_l37n_gclk12_0;
    inout io_l37p_3;
    inout io_l37p_gclk13_0;
    inout io_l3n_0;
    inout io_l3n_mosi_csi_b_miso0_2;
    inout io_l3p_0;
    inout io_l3p_d0_din_miso_miso1_2;
    inout io_l40n_gclk10_1;
    inout io_l40p_gclk11_1;
    inout io_l41n_gclk26_3;
    inout io_l41n_gclk8_1;
    inout io_l41p_gclk27_3;
    inout io_l41p_gclk9_irdy1_1;
    inout io_l42n_gclk24_3;
    inout io_l42n_gclk6_trdy1_1;
    inout io_l42p_gclk25_trdy2_3;
    inout io_l42p_gclk7_1;
    inout io_l43n_gclk22_irdy2_3;
    inout io_l43n_gclk4_1;
    inout io_l43p_gclk23_3;
    inout io_l43p_gclk5_1;
    inout io_l44n_gclk20_3;
    inout io_l44p_gclk21_3;
    inout io_l45n_1;
    inout io_l45p_1;
    inout io_l46n_1;
    inout io_l46p_1;
    inout io_l47n_1;
    inout io_l47p_1;
    inout io_l48n_rdwr_b_vref_2;
    inout io_l48p_d7_2;
    inout io_l49n_3;
    inout io_l49n_d4_2;
    inout io_l49p_3;
    inout io_l49p_d3_2;
    inout io_l4n_0;
    inout io_l4p_0;
    inout io_l50n_3;
    inout io_l50p_3;
    inout io_l51n_3;
    inout io_l51p_3;
    inout io_l52n_3;
    inout io_l52p_3;
    inout io_l62n_d6_2;
    inout io_l62n_vref_0;
    inout io_l62p_0;
    inout io_l62p_d5_2;
    inout io_l63n_scp6_0;
    inout io_l63p_scp7_0;
    inout io_l64n_d9_2;
    inout io_l64n_scp4_0;
    inout io_l64p_d8_2;
    inout io_l64p_scp5_0;
    inout io_l65n_cso_b_2;
    inout io_l65n_scp2_0;
    inout io_l65p_init_b_2;
    inout io_l65p_scp3_0;
    inout io_l66n_scp0_0;
    inout io_l66p_scp1_0;
    inout io_l74n_dout_busy_1;
    inout io_l74p_awake_1;
    inout io_l83n_vref_3;
    inout io_l83p_3;
    inout program_b_2;
    inout suspend;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;


    initial
        begin
        end

endmodule
