// generated by newgenasym  Tue Dec 07 16:39:50 2004


module vft14 (fa, gnd, out, vcc);
    input fa;
    input gnd;
    output out;
    input vcc;


    initial
        begin
        end

endmodule
