-- generated by newgenasym Tue Dec 07 16:39:50 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity vft14 is
    port (    
	FA:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end vft14;
