// generated by newgenasym  Fri Aug 17 16:49:51 2012


module tps3808 (ct, gnd, mr, reset, sence, vdd);
    inout ct;
    inout gnd;
    inout mr;
    inout reset;
    inout sence;
    inout vdd;


    initial
        begin
        end

endmodule
