-- generated by newgenasym Fri Aug 17 16:49:51 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps3808 is
    port (    
	CT:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	MR:        INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	SENCE:     INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end tps3808;
