-- generated by newgenasym Tue Jun 27 17:40:29 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity p200ts is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end p200ts;
