-- generated by newgenasym Mon Oct 04 13:24:54 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm811sart is
    port (    
	GND:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	\rst*\:    INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end adm811sart;
