-- generated by newgenasym Mon Dec 27 15:06:41 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lat is
    port (    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end lat;
