// generated by newgenasym  Tue Jun 15 17:34:12 2004


module bmp10 (in, \in+ , \in- , out, \out+ , \out- );
    input in;
    input \in+ ;
    input \in- ;
    output out;
    output \out+ ;
    output \out- ;


    initial
        begin
        end

endmodule
