-- generated by newgenasym Fri Dec 01 16:15:26 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MINIUSB is
    port (    
	\+5v\:     INOUT  STD_LOGIC;    
	\data+\:   INOUT  STD_LOGIC;    
	\data-\:   INOUT  STD_LOGIC;    
	GROUND:    INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	SHIELD:    INOUT  STD_LOGIC_VECTOR (6 DOWNTO 1));
end MINIUSB;
