-- generated by newgenasym Mon Aug 30 18:35:02 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res4_array is
    port (    
	LPIN:      INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1);    
	RPIN:      INOUT  STD_LOGIC_VECTOR (8 DOWNTO 5));
end res4_array;
