// generated by newgenasym  Tue Jun 29 10:34:41 2004


module ds1077 (ctrl, out, scl, sda);
    input [1:0] ctrl;
    output [1:0] out;
    input scl;
    inout sda;


    initial
        begin
        end

endmodule
