// generated by newgenasym  Fri Dec 15 14:56:57 2017


module \mwdm2l-9  (io1, io2, io3, io4, io5, io6, io7, io8, io9);
    inout io1;
    inout io2;
    inout io3;
    inout io4;
    inout io5;
    inout io6;
    inout io7;
    inout io8;
    inout io9;


    initial
        begin
        end

endmodule
