-- generated by newgenasym Thu Jun 19 17:22:20 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX1490 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12\:      IN     STD_LOGIC;    
	\13\:      OUT    STD_LOGIC;    
	\14\:      OUT    STD_LOGIC;    
	\15\:      OUT    STD_LOGIC;    
	\16\:      OUT    STD_LOGIC;    
	\17\:      OUT    STD_LOGIC;    
	\18\:      OUT    STD_LOGIC;    
	\19\:      OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\20\:      OUT    STD_LOGIC;    
	\21\:      OUT    STD_LOGIC;    
	\22\:      OUT    STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end MAX1490;
