-- generated by newgenasym Wed Aug 15 18:05:55 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rlm_43_5w is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end rlm_43_5w;
