// generated by newgenasym  Wed Sep 26 10:20:01 2007


module xp1mpwr (\+3.3vma , \+5vma , \0vma , \0vma2 );
    inout \+3.3vma ;
    inout \+5vma ;
    inout \0vma ;
    inout \0vma2 ;


    initial
        begin
        end

endmodule
