-- generated by newgenasym Wed Sep 26 10:20:01 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xp1mpwr is
    port (    
	\+3.3vma\: INOUT  STD_LOGIC;    
	\+5vma\:   INOUT  STD_LOGIC;    
	\0vma\:    INOUT  STD_LOGIC;    
	\0vma2\:   INOUT  STD_LOGIC);
end xp1mpwr;
