-- generated by newgenasym Wed May 31 16:17:27 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cp2104n is
    port (    
	CTS:       INOUT  STD_LOGIC;    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	DCD:       INOUT  STD_LOGIC;    
	DSR:       INOUT  STD_LOGIC;    
	DTR:       INOUT  STD_LOGIC;    
	GPIO0:     INOUT  STD_LOGIC;    
	GPIO1:     INOUT  STD_LOGIC;    
	GPIO2:     INOUT  STD_LOGIC;    
	GPIO3:     INOUT  STD_LOGIC;    
	RI:        INOUT  STD_LOGIC;    
	RST:       INOUT  STD_LOGIC;    
	RTS:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	SUSPEND:   INOUT  STD_LOGIC;    
	SUSPENDN:  INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VIO:       INOUT  STD_LOGIC;    
	VPP:       INOUT  STD_LOGIC;    
	VREGIN:    INOUT  STD_LOGIC);
end cp2104n;
