-- generated by newgenasym Tue Jan 10 13:01:51 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity wiz820io is
    port (    
	MISO:      INOUT  STD_LOGIC;    
	MOSI:      INOUT  STD_LOGIC;    
	NINT:      INOUT  STD_LOGIC;    
	NRESET:    INOUT  STD_LOGIC;    
	NSS:       INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC);
end wiz820io;
