-- generated by newgenasym Wed Jul 21 11:25:33 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \pld-2\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \pld-2\;
