// generated by newgenasym  Wed Feb 07 10:59:01 2007


module gs8640z36 (a, adv, \be* , ck, \cke* , d, \e1* , e2, \e3* , \ft* , \lbo* , \oe* , \we* , zz);
    input [20:0] a;
    input adv;
    input [3:0] \be* ;
    input ck;
    input \cke* ;
    inout [35:0] d;
    input \e1* ;
    input e2;
    input \e3* ;
    input \ft* ;
    input \lbo* ;
    input \oe* ;
    input \we* ;
    input zz;


    initial
        begin
        end

endmodule
