// generated by newgenasym  Thu May 18 10:05:57 2017


module ad8342 (exrb, ifom, ifop, locm, loin, pwdn, rfcm, rfin, vpdc, vplo,
        vpmx);
    inout exrb;
    inout ifom;
    inout ifop;
    inout locm;
    inout loin;
    inout pwdn;
    inout rfcm;
    inout rfin;
    input vpdc;
    input vplo;
    input vpmx;


    initial
        begin
        end

endmodule
