-- generated by newgenasym Thu May 18 10:05:57 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8342 is
    port (    
	EXRB:      INOUT  STD_LOGIC;    
	IFOM:      INOUT  STD_LOGIC;    
	IFOP:      INOUT  STD_LOGIC;    
	LOCM:      INOUT  STD_LOGIC;    
	LOIN:      INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	RFCM:      INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	VPDC:      IN     STD_LOGIC;    
	VPLO:      IN     STD_LOGIC;    
	VPMX:      IN     STD_LOGIC);
end ad8342;
