-- generated by newgenasym Thu Jan 14 11:21:27 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bnx016 is
    port (    
	B:         INOUT  STD_LOGIC;    
	CB:        INOUT  STD_LOGIC;    
	CG:        INOUT  STD_LOGIC;    
	PSG:       INOUT  STD_LOGIC);
end bnx016;
