-- generated by newgenasym Fri Nov 25 16:01:50 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ss12d10 is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC);
end ss12d10;
