-- generated by newgenasym Fri Jul 07 18:17:29 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity JTAG is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (6 DOWNTO 0);    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC);
end JTAG;
