// generated by newgenasym  Fri May 28 10:39:34 2004


module ad3ps_1 (in, out1, out2, out3, shield1, shield2, shield3, shield4);
    input in;
    output out1;
    output out2;
    output out3;
    input shield1;
    input shield2;
    input shield3;
    input shield4;


    initial
        begin
        end

endmodule
