-- generated by newgenasym Fri May 28 10:39:34 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad3ps_1 is
    port (    
	\in\:      IN     STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	OUT3:      OUT    STD_LOGIC;    
	SHIELD1:   IN     STD_LOGIC;    
	SHIELD2:   IN     STD_LOGIC;    
	SHIELD3:   IN     STD_LOGIC;    
	SHIELD4:   IN     STD_LOGIC);
end ad3ps_1;
