// generated by newgenasym  Mon Oct 20 16:59:09 2003


module \74lv153pw_dh  (\1e* , \1i0 , \1i1 , \1i2 , \1i3 , \1y , \2e* , \2i0 , \2i1 , \2i2 , \2i3 , \2y , s0, s1);
    input \1e* ;
    input \1i0 ;
    input \1i1 ;
    input \1i2 ;
    input \1i3 ;
    output \1y ;
    input \2e* ;
    input \2i0 ;
    input \2i1 ;
    input \2i2 ;
    input \2i3 ;
    output \2y ;
    input s0;
    input s1;


    initial
        begin
        end

endmodule
