-- generated by newgenasym Mon Oct 20 16:59:09 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lv153pw_dh\ is
    port (    
	\1e*\:     IN     STD_LOGIC;    
	\1i0\:     IN     STD_LOGIC;    
	\1i1\:     IN     STD_LOGIC;    
	\1i2\:     IN     STD_LOGIC;    
	\1i3\:     IN     STD_LOGIC;    
	\1y\:      OUT    STD_LOGIC;    
	\2e*\:     IN     STD_LOGIC;    
	\2i0\:     IN     STD_LOGIC;    
	\2i1\:     IN     STD_LOGIC;    
	\2i2\:     IN     STD_LOGIC;    
	\2i3\:     IN     STD_LOGIC;    
	\2y\:      OUT    STD_LOGIC;    
	S0:        IN     STD_LOGIC;    
	S1:        IN     STD_LOGIC);
end \74lv153pw_dh\;
