-- generated by newgenasym Tue Jul 25 16:51:11 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity idtf1102nb is
    port (    
	GND_24:    INOUT  STD_LOGIC;    
	\if_a+\:   INOUT  STD_LOGIC;    
	\if_a-\:   INOUT  STD_LOGIC;    
	\if_b+\:   INOUT  STD_LOGIC;    
	\if_b-\:   INOUT  STD_LOGIC;    
	IF_BIASA:  INOUT  STD_LOGIC;    
	IF_BIASB:  INOUT  STD_LOGIC;    
	LCMODE:    INOUT  STD_LOGIC;    
	LO1_ADJ:   INOUT  STD_LOGIC;    
	LO2_ADJ:   INOUT  STD_LOGIC;    
	LO_IN:     INOUT  STD_LOGIC;    
	LO_IN_ALT: INOUT  STD_LOGIC;    
	LO_RTN:    INOUT  STD_LOGIC;    
	RF_A:      INOUT  STD_LOGIC;    
	RF_A_RTN:  INOUT  STD_LOGIC;    
	RF_B:      INOUT  STD_LOGIC;    
	RF_B_RTN:  INOUT  STD_LOGIC;    
	STBY:      INOUT  STD_LOGIC);
end idtf1102nb;
