-- generated by newgenasym Wed Sep 13 12:56:07 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lfcn_490 is
    port (    
	\rf in\:   INOUT  STD_LOGIC;    
	\rf out\:  INOUT  STD_LOGIC);
end lfcn_490;
