// generated by newgenasym  Tue Mar 22 17:06:34 2005


module erni64785 (a, b, c, d, e, f);
    inout [22:1] a;
    inout [22:1] b;
    inout [22:1] c;
    inout [22:1] d;
    inout [22:1] e;
    inout [22:1] f;


    initial
        begin
        end

endmodule
