-- generated by newgenasym Tue Mar 22 17:06:34 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity erni64785 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	C:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	D:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	E:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1);    
	F:         INOUT  STD_LOGIC_VECTOR (22 DOWNTO 1));
end erni64785;
