-- generated by newgenasym Mon Nov 13 12:31:55 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xp6 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	\cs#\:     INOUT  STD_LOGIC;    
	DB0:       INOUT  STD_LOGIC;    
	DB1:       INOUT  STD_LOGIC;    
	DB2:       INOUT  STD_LOGIC;    
	DB3:       INOUT  STD_LOGIC;    
	DB4:       INOUT  STD_LOGIC;    
	DB5:       INOUT  STD_LOGIC;    
	DB6:       INOUT  STD_LOGIC;    
	DB7:       INOUT  STD_LOGIC;    
	FGND:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\rd#\:     INOUT  STD_LOGIC;    
	\res#\:    INOUT  STD_LOGIC;    
	SEL1:      INOUT  STD_LOGIC;    
	V0:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VEE:       INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC;    
	\wr#\:     INOUT  STD_LOGIC);
end xp6;
