-- generated by newgenasym Wed Nov 24 16:46:38 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity C_PR is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end C_PR;
