-- generated by newgenasym Tue Oct 21 13:19:26 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crc4a8e is
    port (    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	IN4:       INOUT  STD_LOGIC;    
	IN5:       INOUT  STD_LOGIC;    
	IN6:       INOUT  STD_LOGIC;    
	IN7:       INOUT  STD_LOGIC;    
	IN8:       INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC;    
	OUT4:      INOUT  STD_LOGIC;    
	OUT5:      INOUT  STD_LOGIC;    
	OUT6:      INOUT  STD_LOGIC;    
	OUT7:      INOUT  STD_LOGIC;    
	OUT8:      INOUT  STD_LOGIC);
end crc4a8e;
