// generated by newgenasym  Wed Apr 06 15:29:16 2011


module ad607 (com1, com2, dmip, fdin, fltr, gain, gref, ifhi, iflo, ifop,
        iout, loip, mxop, prup, qout, rfhi, rflo, vmid, vps1, vps2);
    inout com1;
    inout com2;
    inout dmip;
    inout fdin;
    inout fltr;
    inout gain;
    inout gref;
    inout ifhi;
    inout iflo;
    inout ifop;
    inout iout;
    inout loip;
    inout mxop;
    inout prup;
    inout qout;
    inout rfhi;
    inout rflo;
    inout vmid;
    inout vps1;
    inout vps2;


    initial
        begin
        end

endmodule
