-- generated by newgenasym Wed Apr 06 15:29:16 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad607 is
    port (    
	COM1:      INOUT  STD_LOGIC;    
	COM2:      INOUT  STD_LOGIC;    
	DMIP:      INOUT  STD_LOGIC;    
	FDIN:      INOUT  STD_LOGIC;    
	FLTR:      INOUT  STD_LOGIC;    
	GAIN:      INOUT  STD_LOGIC;    
	GREF:      INOUT  STD_LOGIC;    
	IFHI:      INOUT  STD_LOGIC;    
	IFLO:      INOUT  STD_LOGIC;    
	IFOP:      INOUT  STD_LOGIC;    
	IOUT:      INOUT  STD_LOGIC;    
	LOIP:      INOUT  STD_LOGIC;    
	MXOP:      INOUT  STD_LOGIC;    
	PRUP:      INOUT  STD_LOGIC;    
	QOUT:      INOUT  STD_LOGIC;    
	RFHI:      INOUT  STD_LOGIC;    
	RFLO:      INOUT  STD_LOGIC;    
	VMID:      INOUT  STD_LOGIC;    
	VPS1:      INOUT  STD_LOGIC;    
	VPS2:      INOUT  STD_LOGIC);
end ad607;
