// generated by newgenasym  Mon Nov 01 12:16:30 2004


module c8051f060tqfp100 (\/rst* , \0vref , \1vref , \1xtal , \2vref , \2xtal , ain, aing, canrx,
        cantx, cnvstr, dac, monen, \p0. , \p1. , \p2. , \p3. , \p4. , \p5. , \p6. ,
        \p7. , tck, tdi, tdo, tms, vbgap, vref, vrefd, vrgnd);
    inout \/rst* ;
    inout \0vref ;
    inout \1vref ;
    input \1xtal ;
    input \2vref ;
    output \2xtal ;
    input [1:0] ain;
    input [1:0] aing;
    input canrx;
    output cantx;
    input [1:0] cnvstr;
    output [1:0] dac;
    input monen;
    inout [7:0] \p0. ;
    inout [7:0] \p1. ;
    inout [7:0] \p2. ;
    inout [7:0] \p3. ;
    inout [7:5] \p4. ;
    inout [7:0] \p5. ;
    inout [7:0] \p6. ;
    inout [7:0] \p7. ;
    input tck;
    input tdi;
    output tdo;
    input tms;
    output [1:0] vbgap;
    inout vref;
    input vrefd;
    input [1:0] vrgnd;


    initial
        begin
        end

endmodule
