-- generated by newgenasym Mon Nov 01 12:16:30 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity C8051F060TQFP100 is
    port (    
	\/rst*\:   INOUT  STD_LOGIC;    
	\0vref\:   INOUT  STD_LOGIC;    
	\1vref\:   INOUT  STD_LOGIC;    
	\1xtal\:   IN     STD_LOGIC;    
	\2vref\:   IN     STD_LOGIC;    
	\2xtal\:   OUT    STD_LOGIC;    
	AIN:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	AING:      IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	CANRX:     IN     STD_LOGIC;    
	CANTX:     OUT    STD_LOGIC;    
	CNVSTR:    IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	DAC:       OUT    STD_LOGIC_VECTOR (1 DOWNTO 0);    
	MONEN:     IN     STD_LOGIC;    
	\p0.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p1.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p2.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p3.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p4.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 5);    
	\p5.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p6.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\p7.\:     INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	TCK:       IN     STD_LOGIC;    
	TDI:       IN     STD_LOGIC;    
	TDO:       OUT    STD_LOGIC;    
	TMS:       IN     STD_LOGIC;    
	VBGAP:     OUT    STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VREF:      INOUT  STD_LOGIC;    
	VREFD:     IN     STD_LOGIC;    
	VRGND:     IN     STD_LOGIC_VECTOR (1 DOWNTO 0));
end C8051F060TQFP100;
