// generated by newgenasym  Fri Dec 01 16:09:54 2017


module kpfa_2507 (bl, com, gre, red);
    inout bl;
    inout com;
    inout gre;
    inout red;


    initial
        begin
        end

endmodule
