-- generated by newgenasym Fri Dec 01 16:09:54 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity kpfa_2507 is
    port (    
	BL:        INOUT  STD_LOGIC;    
	COM:       INOUT  STD_LOGIC;    
	GRE:       INOUT  STD_LOGIC;    
	RED:       INOUT  STD_LOGIC);
end kpfa_2507;
