// generated by newgenasym  Mon Nov 22 17:25:49 2004


module mic37301 (en, \err* , vin, vout);
    input en;
    output \err* ;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
