-- generated by newgenasym Tue Aug 10 15:33:18 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlp_181 is
    port (    
	AN:        INOUT  STD_LOGIC;    
	CAT:       INOUT  STD_LOGIC;    
	EM:        INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end tlp_181;
