-- generated by newgenasym Tue Jun 01 10:31:28 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity qse_20 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (20 DOWNTO 1);    
	GNDD:      INOUT  STD_LOGIC);
end qse_20;
