// generated by newgenasym  Wed Nov 30 16:23:08 2011


module adum2402 (ve1, ve2, via, vib, vic, vid, voa, vob, voc, vod);
    inout ve1;
    inout ve2;
    inout via;
    inout vib;
    inout vic;
    inout vid;
    inout voa;
    inout vob;
    inout voc;
    inout vod;


    initial
        begin
        end

endmodule
