-- generated by newgenasym Wed Nov 30 16:23:08 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adum2402 is
    port (    
	VE1:       INOUT  STD_LOGIC;    
	VE2:       INOUT  STD_LOGIC;    
	VIA:       INOUT  STD_LOGIC;    
	VIB:       INOUT  STD_LOGIC;    
	VIC:       INOUT  STD_LOGIC;    
	VID:       INOUT  STD_LOGIC;    
	VOA:       INOUT  STD_LOGIC;    
	VOB:       INOUT  STD_LOGIC;    
	VOC:       INOUT  STD_LOGIC;    
	VOD:       INOUT  STD_LOGIC);
end adum2402;
