-- generated by newgenasym Wed Aug 06 18:33:45 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1273pa5y\ is
    port (    
	\clk+\:    INOUT  STD_LOGIC;    
	\clk-\:    INOUT  STD_LOGIC;    
	DB0:       INOUT  STD_LOGIC;    
	DB1:       INOUT  STD_LOGIC;    
	DB10:      INOUT  STD_LOGIC;    
	DB11:      INOUT  STD_LOGIC;    
	DB12:      INOUT  STD_LOGIC;    
	DB13:      INOUT  STD_LOGIC;    
	DB2:       INOUT  STD_LOGIC;    
	DB3:       INOUT  STD_LOGIC;    
	DB4:       INOUT  STD_LOGIC;    
	DB5:       INOUT  STD_LOGIC;    
	DB6:       INOUT  STD_LOGIC;    
	DB7:       INOUT  STD_LOGIC;    
	DB8:       INOUT  STD_LOGIC;    
	DB9:       INOUT  STD_LOGIC;    
	DIV0:      INOUT  STD_LOGIC;    
	DIV1:      INOUT  STD_LOGIC;    
	FSADJ:     INOUT  STD_LOGIC;    
	IOUTA:     INOUT  STD_LOGIC;    
	IOUTB:     INOUT  STD_LOGIC;    
	LPF:       INOUT  STD_LOGIC;    
	MOD0:      INOUT  STD_LOGIC;    
	MOD1:      INOUT  STD_LOGIC;    
	PLLLOCK:   INOUT  STD_LOGIC;    
	REFIO:     INOUT  STD_LOGIC;    
	REFLO:     INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	SLEEP:     INOUT  STD_LOGIC);
end \1273pa5y\;
