// generated by newgenasym  Tue Oct 21 15:34:57 2003


module lpd16 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    output \12 ;
    input \13 ;
    output \14 ;
    input \15 ;
    output \16 ;
    output \2 ;
    input \3 ;
    output \4 ;
    input \5 ;
    output \6 ;
    input \7 ;
    output \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
