-- generated by newgenasym Tue Oct 21 15:34:57 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lpd16 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12\:      OUT    STD_LOGIC;    
	\13\:      IN     STD_LOGIC;    
	\14\:      OUT    STD_LOGIC;    
	\15\:      IN     STD_LOGIC;    
	\16\:      OUT    STD_LOGIC;    
	\2\:       OUT    STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       OUT    STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       OUT    STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       OUT    STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end lpd16;
