-- generated by newgenasym Wed May 16 15:44:59 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad820 is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\+vs\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\-vs\:     INOUT  STD_LOGIC;    
	\n.c.\:    INOUT  STD_LOGIC;    
	\null\:    INOUT  STD_LOGIC;    
	NULL2:     INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end ad820;
