// generated by newgenasym  Sat Jun 21 14:37:09 2003


module sn05230d (ch, cl, d, r, rs, vr);
    input ch;
    input cl;
    output d;
    output r;
    input rs;
    input vr;


    initial
        begin
        end

endmodule
