-- generated by newgenasym Sat Jun 21 14:37:09 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn05230d is
    port (    
	CH:        IN     STD_LOGIC;    
	CL:        IN     STD_LOGIC;    
	D:         OUT    STD_LOGIC;    
	R:         OUT    STD_LOGIC;    
	RS:        IN     STD_LOGIC;    
	VR:        IN     STD_LOGIC);
end sn05230d;
