// generated by newgenasym  Tue Aug 10 11:05:03 2010


module \thd#2012-1211  (\+vin1 , \+vin2 , \+vout , \-vin1 , \-vin2 , \-vout , en, \n.c1 , \n.c2 );
    inout \+vin1 ;
    inout \+vin2 ;
    inout \+vout ;
    inout \-vin1 ;
    inout \-vin2 ;
    inout \-vout ;
    inout en;
    inout \n.c1 ;
    inout \n.c2 ;


    initial
        begin
        end

endmodule
