// generated by newgenasym  Tue May 20 13:29:31 2008


module adcm604 (q, \q- , vcci, vee, vn, vp);
    inout q;
    inout \q- ;
    inout vcci;
    inout vee;
    inout vn;
    inout vp;


    initial
        begin
        end

endmodule
