-- generated by newgenasym Tue May 20 13:29:31 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adcm604 is
    port (    
	Q:         INOUT  STD_LOGIC;    
	\q-\:      INOUT  STD_LOGIC;    
	VCCI:      INOUT  STD_LOGIC;    
	VEE:       INOUT  STD_LOGIC;    
	VN:        INOUT  STD_LOGIC;    
	VP:        INOUT  STD_LOGIC);
end adcm604;
