// generated by newgenasym  Tue Jun 27 17:04:30 2017


module adl5519 (adja, adjb, clpa, clpb, fbka, fbkb, inha, inhb, inla, inlb,
        outa, outb, outn, outp, pwdn, temp, vlvl, vref, vsta, vstb);
    inout adja;
    inout adjb;
    inout clpa;
    inout clpb;
    inout fbka;
    inout fbkb;
    inout inha;
    inout inhb;
    inout inla;
    inout inlb;
    inout outa;
    inout outb;
    inout outn;
    inout outp;
    inout pwdn;
    inout temp;
    inout vlvl;
    inout vref;
    inout vsta;
    inout vstb;


    initial
        begin
        end

endmodule
