-- generated by newgenasym Tue Jun 27 17:04:30 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5519 is
    port (    
	ADJA:      INOUT  STD_LOGIC;    
	ADJB:      INOUT  STD_LOGIC;    
	CLPA:      INOUT  STD_LOGIC;    
	CLPB:      INOUT  STD_LOGIC;    
	FBKA:      INOUT  STD_LOGIC;    
	FBKB:      INOUT  STD_LOGIC;    
	INHA:      INOUT  STD_LOGIC;    
	INHB:      INOUT  STD_LOGIC;    
	INLA:      INOUT  STD_LOGIC;    
	INLB:      INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	OUTN:      INOUT  STD_LOGIC;    
	OUTP:      INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	TEMP:      INOUT  STD_LOGIC;    
	VLVL:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VSTA:      INOUT  STD_LOGIC;    
	VSTB:      INOUT  STD_LOGIC);
end adl5519;
