-- generated by newgenasym Mon Jun 07 16:32:58 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4624 is
    port (    
	ASW_C:     IN     STD_LOGIC;    
	ASW_O:     IN     STD_LOGIC;    
	COM:       OUT    STD_LOGIC;    
	GNDD:      INOUT  STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	P5V0:      INOUT  STD_LOGIC);
end max4624;
