// generated by newgenasym  Thu Aug 16 13:23:18 2018


module tc1_1x (pri, \pri#20dot , sec, \sec#20dot );
    inout pri;
    inout \pri#20dot ;
    inout sec;
    inout \sec#20dot ;


    initial
        begin
        end

endmodule
