-- generated by newgenasym Tue Jul 19 16:58:14 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max1615 is
    port (    
	\5/3\:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	SHDN:      INOUT  STD_LOGIC);
end max1615;
