// generated by newgenasym  Fri May 28 15:49:38 2004


module fin1532 (en, \en* , p5v0, \r_in1+ , \r_in1- , \r_in2+ , \r_in2- , \r_in3+ ,
        \r_in3- , \r_in4+ , \r_in4- , r_out1, r_out2, r_out3, r_out4,
        shield);
    input en;
    input \en* ;
    input p5v0;
    input \r_in1+ ;
    input \r_in1- ;
    input \r_in2+ ;
    input \r_in2- ;
    input \r_in3+ ;
    input \r_in3- ;
    input \r_in4+ ;
    input \r_in4- ;
    output r_out1;
    output r_out2;
    output r_out3;
    output r_out4;
    input shield;


    initial
        begin
        end

endmodule
