-- generated by newgenasym Fri May 28 15:49:38 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fin1532 is
    port (    
	EN:        IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	P5V0:      IN     STD_LOGIC;    
	\r_in1+\:  IN     STD_LOGIC;    
	\r_in1-\:  IN     STD_LOGIC;    
	\r_in2+\:  IN     STD_LOGIC;    
	\r_in2-\:  IN     STD_LOGIC;    
	\r_in3+\:  IN     STD_LOGIC;    
	\r_in3-\:  IN     STD_LOGIC;    
	\r_in4+\:  IN     STD_LOGIC;    
	\r_in4-\:  IN     STD_LOGIC;    
	R_OUT1:    OUT    STD_LOGIC;    
	R_OUT2:    OUT    STD_LOGIC;    
	R_OUT3:    OUT    STD_LOGIC;    
	R_OUT4:    OUT    STD_LOGIC;    
	SHIELD:    IN     STD_LOGIC);
end fin1532;
