// generated by newgenasym  Wed Dec 28 12:14:39 2011


module w5100 (\1v8_out , addr0, addr1, addr10, addr11, addr12, addr13,
        addr14, addr2, addr3, addr4, addr5, addr6, addr7, addr8,
        addr9, colled, cs, data0, data1, data2, data3, data4, data5,
        data6, data7, fdxled, int, linkled, miso, mosi, opmode0,
        opmode1, opmode2, rd, reset, rset_bg, rxin, rxip, rxled, sclk,
        scs, sen, spdled, test_mode0, test_mode1, test_mode2,
        test_mode3, txled, txon, txop, wr, xtln, xtlp);
    inout \1v8_out ;
    inout addr0;
    inout addr1;
    inout addr10;
    inout addr11;
    inout addr12;
    inout addr13;
    inout addr14;
    inout addr2;
    inout addr3;
    inout addr4;
    inout addr5;
    inout addr6;
    inout addr7;
    inout addr8;
    inout addr9;
    inout colled;
    inout cs;
    inout data0;
    inout data1;
    inout data2;
    inout data3;
    inout data4;
    inout data5;
    inout data6;
    inout data7;
    inout fdxled;
    inout int;
    inout linkled;
    inout miso;
    inout mosi;
    inout opmode0;
    inout opmode1;
    inout opmode2;
    inout rd;
    inout reset;
    inout rset_bg;
    inout rxin;
    inout rxip;
    inout rxled;
    inout sclk;
    inout scs;
    inout sen;
    inout spdled;
    inout test_mode0;
    inout test_mode1;
    inout test_mode2;
    inout test_mode3;
    inout txled;
    inout txon;
    inout txop;
    inout wr;
    inout xtln;
    inout xtlp;


    initial
        begin
        end

endmodule
