// generated by newgenasym  Wed Dec 14 17:56:17 2011


module ad7451 (cs_n, sclk, sdata, \vin+ , \vin- , vref);
    inout cs_n;
    inout sclk;
    inout sdata;
    inout \vin+ ;
    inout \vin- ;
    inout vref;


    initial
        begin
        end

endmodule
