-- generated by newgenasym Wed Dec 14 17:56:17 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7451 is
    port (    
	CS_N:      INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	SDATA:     INOUT  STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ad7451;
