-- generated by newgenasym Thu Oct 11 16:08:09 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4707 is
    port (    
	COM:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	NO:        INOUT  STD_LOGIC);
end max4707;
