// generated by newgenasym  Thu Sep 10 16:36:02 2020


module mp2307 (bs, comp, en, fb, in, ss, sw);
    inout bs;
    inout comp;
    inout en;
    inout fb;
    inout in;
    inout ss;
    inout sw;


    initial
        begin
        end

endmodule
