// generated by newgenasym  Tue Jun 29 10:35:27 2004


module ds1077_1 (ctrl, gndd, out, p3v3, scl, sda);
    input [1:0] ctrl;
    input gndd;
    output [1:0] out;
    input p3v3;
    input scl;
    inout sda;


    initial
        begin
        end

endmodule
