// generated by newgenasym  Thu Aug 16 16:49:06 2012


module trf372017 (bbi_n, bbi_p, bbq_n, bbq_p, clk, cp_out, data, ext_vco, ld,
        le, lo_out_n, lo_out_p, ps, rdbk, refin, rfout, rsvd, scan_en,
        vtune);
    inout bbi_n;
    inout bbi_p;
    inout bbq_n;
    inout bbq_p;
    inout clk;
    inout cp_out;
    inout data;
    inout ext_vco;
    inout ld;
    inout le;
    inout lo_out_n;
    inout lo_out_p;
    inout ps;
    inout rdbk;
    inout refin;
    inout rfout;
    inout rsvd;
    inout scan_en;
    inout vtune;


    initial
        begin
        end

endmodule
