-- generated by newgenasym Thu Aug 16 16:49:06 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TRF372017 is
    port (    
	BBI_N:     INOUT  STD_LOGIC;    
	BBI_P:     INOUT  STD_LOGIC;    
	BBQ_N:     INOUT  STD_LOGIC;    
	BBQ_P:     INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CP_OUT:    INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	EXT_VCO:   INOUT  STD_LOGIC;    
	LD:        INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	LO_OUT_N:  INOUT  STD_LOGIC;    
	LO_OUT_P:  INOUT  STD_LOGIC;    
	PS:        INOUT  STD_LOGIC;    
	RDBK:      INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	RFOUT:     INOUT  STD_LOGIC;    
	RSVD:      INOUT  STD_LOGIC;    
	SCAN_EN:   INOUT  STD_LOGIC;    
	VTUNE:     INOUT  STD_LOGIC);
end TRF372017;
