-- generated by newgenasym Thu Aug 16 13:43:45 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bpf_c70 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end bpf_c70;
