// generated by newgenasym  Wed May 02 17:37:06 2012


module ds90c401 (\d01+ , \d01- , di1, di2, \do2+ , \do2- );
    inout \d01+ ;
    inout \d01- ;
    inout di1;
    inout di2;
    inout \do2+ ;
    inout \do2- ;


    initial
        begin
        end

endmodule
