-- generated by newgenasym Wed May 02 17:37:06 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90c401 is
    port (    
	\d01+\:    INOUT  STD_LOGIC;    
	\d01-\:    INOUT  STD_LOGIC;    
	DI1:       INOUT  STD_LOGIC;    
	DI2:       INOUT  STD_LOGIC;    
	\do2+\:    INOUT  STD_LOGIC;    
	\do2-\:    INOUT  STD_LOGIC);
end ds90c401;
