// generated by newgenasym  Wed Oct 31 15:58:35 2007


module \69001-816-1  (b19, b20, b22, b24, b25, b26, b27, b28, b29, b30, b31, b32, c1,
        c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c2, c20, c21,
        c22, c23, c24, c25, c26, c27, c28, c29, c3, c30, c31, c32, c4, c5,
        c6, c7, c8, c9);
    inout b19;
    inout b20;
    inout b22;
    inout b24;
    inout b25;
    inout b26;
    inout b27;
    inout b28;
    inout b29;
    inout b30;
    inout b31;
    inout b32;
    inout c1;
    inout c10;
    inout c11;
    inout c12;
    inout c13;
    inout c14;
    inout c15;
    inout c16;
    inout c17;
    inout c18;
    inout c19;
    inout c2;
    inout c20;
    inout c21;
    inout c22;
    inout c23;
    inout c24;
    inout c25;
    inout c26;
    inout c27;
    inout c28;
    inout c29;
    inout c3;
    inout c30;
    inout c31;
    inout c32;
    inout c4;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    inout c9;


    initial
        begin
        end

endmodule
