// generated by newgenasym  Thu Apr 10 11:01:13 2003


module pld10 (\1 , \10 , \2 , \3 , \4 , \5 , \9 );
    input \1 ;
    input \10 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \9 ;


    initial
        begin
        end

endmodule
