-- generated by newgenasym Thu Aug 16 16:28:29 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fpcn2_50 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	TERM:      INOUT  STD_LOGIC);
end fpcn2_50;
