// generated by newgenasym  Thu Jul 01 15:26:13 2004


module p82b96td (gndd, p3v3, rx, ry, sx, sy, tx, ty);
    input gndd;
    input p3v3;
    input rx;
    input ry;
    inout sx;
    inout sy;
    output tx;
    output ty;


    initial
        begin
        end

endmodule
