-- generated by newgenasym Thu Jul 01 15:26:13 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity p82b96td is
    port (    
	GNDD:      IN     STD_LOGIC;    
	P3V3:      IN     STD_LOGIC;    
	RX:        IN     STD_LOGIC;    
	RY:        IN     STD_LOGIC;    
	SX:        INOUT  STD_LOGIC;    
	SY:        INOUT  STD_LOGIC;    
	TX:        OUT    STD_LOGIC;    
	TY:        OUT    STD_LOGIC);
end p82b96td;
