// generated by newgenasym  Wed Aug 26 18:01:55 2020


module a6211 (boot, cs, en, sw, ton, vcc, vin);
    inout boot;
    inout cs;
    inout en;
    inout sw;
    inout ton;
    input vcc;
    inout vin;


    initial
        begin
        end

endmodule
