-- generated by newgenasym Wed Aug 26 18:01:55 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity a6211 is
    port (    
	BOOT:      INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	TON:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end a6211;
