// generated by newgenasym  Fri Sep 17 13:07:44 2004


module esd_strip (bstrip, strip, tstrip);
    inout [2:1] bstrip;
    inout [3:3] strip;
    inout [2:1] tstrip;


    initial
        begin
        end

endmodule
