-- generated by newgenasym Fri Sep 17 13:07:44 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esd_strip is
    port (    
	BSTRIP:    INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	STRIP:     INOUT  STD_LOGIC_VECTOR (3 DOWNTO 3);    
	TSTRIP:    INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1));
end esd_strip;
