// generated by newgenasym  Wed Feb 09 14:46:21 2005


module c8051f310 (\alert* , c2d, \int* , miso, mosi, pio1, pio2, pio3, \rst* , scl,
        sclk, \scs* , sda);
    output \alert* ;
    inout c2d;
    input \int* ;
    input miso;
    output mosi;
    inout [7:0] pio1;
    inout [7:0] pio2;
    inout [4:1] pio3;
    input \rst* ;
    input scl;
    input sclk;
    input \scs* ;
    inout sda;


    initial
        begin
        end

endmodule
