-- generated by newgenasym Wed Feb 09 14:46:21 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity C8051F310 is
    port (    
	\alert*\:  OUT    STD_LOGIC;    
	C2D:       INOUT  STD_LOGIC;    
	\int*\:    IN     STD_LOGIC;    
	MISO:      IN     STD_LOGIC;    
	MOSI:      OUT    STD_LOGIC;    
	PIO1:      INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	PIO2:      INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	PIO3:      INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1);    
	\rst*\:    IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	\scs*\:    IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC);
end C8051F310;
