-- generated by newgenasym Fri Aug 08 16:15:37 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmz12010 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	\ss/trin\: INOUT  STD_LOGIC);
end lmz12010;
