// generated by newgenasym  Mon Apr 28 15:39:39 2008


module cy7c68013a_56 (clkout, dminus, dplus, flaga, flagb, flagc, ifclk, pa0, pa1,
        pa2, pa3, pa4, pa5, pa6, pa7, pb0, pb1, pb2, pb3, pb4, pb5, pb6,
        pb7, pd0, pd1, pd2, pd3, pd4, pd5, pd6, pd7, reserv, reset, scl,
        sda, slrd, slwr, wakeup, xtalin, xtalout);
    inout clkout;
    inout dminus;
    inout dplus;
    inout flaga;
    inout flagb;
    inout flagc;
    inout ifclk;
    inout pa0;
    inout pa1;
    inout pa2;
    inout pa3;
    inout pa4;
    inout pa5;
    inout pa6;
    inout pa7;
    inout pb0;
    inout pb1;
    inout pb2;
    inout pb3;
    inout pb4;
    inout pb5;
    inout pb6;
    inout pb7;
    inout pd0;
    inout pd1;
    inout pd2;
    inout pd3;
    inout pd4;
    inout pd5;
    inout pd6;
    inout pd7;
    inout reserv;
    inout reset;
    inout scl;
    inout sda;
    inout slrd;
    inout slwr;
    inout wakeup;
    inout xtalin;
    inout xtalout;


    initial
        begin
        end

endmodule
