-- generated by newgenasym Mon Apr 28 15:39:39 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cy7c68013a_56 is
    port (    
	CLKOUT:    INOUT  STD_LOGIC;    
	DMINUS:    INOUT  STD_LOGIC;    
	DPLUS:     INOUT  STD_LOGIC;    
	FLAGA:     INOUT  STD_LOGIC;    
	FLAGB:     INOUT  STD_LOGIC;    
	FLAGC:     INOUT  STD_LOGIC;    
	IFCLK:     INOUT  STD_LOGIC;    
	PA0:       INOUT  STD_LOGIC;    
	PA1:       INOUT  STD_LOGIC;    
	PA2:       INOUT  STD_LOGIC;    
	PA3:       INOUT  STD_LOGIC;    
	PA4:       INOUT  STD_LOGIC;    
	PA5:       INOUT  STD_LOGIC;    
	PA6:       INOUT  STD_LOGIC;    
	PA7:       INOUT  STD_LOGIC;    
	PB0:       INOUT  STD_LOGIC;    
	PB1:       INOUT  STD_LOGIC;    
	PB2:       INOUT  STD_LOGIC;    
	PB3:       INOUT  STD_LOGIC;    
	PB4:       INOUT  STD_LOGIC;    
	PB5:       INOUT  STD_LOGIC;    
	PB6:       INOUT  STD_LOGIC;    
	PB7:       INOUT  STD_LOGIC;    
	PD0:       INOUT  STD_LOGIC;    
	PD1:       INOUT  STD_LOGIC;    
	PD2:       INOUT  STD_LOGIC;    
	PD3:       INOUT  STD_LOGIC;    
	PD4:       INOUT  STD_LOGIC;    
	PD5:       INOUT  STD_LOGIC;    
	PD6:       INOUT  STD_LOGIC;    
	PD7:       INOUT  STD_LOGIC;    
	RESERV:    INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SLRD:      INOUT  STD_LOGIC;    
	SLWR:      INOUT  STD_LOGIC;    
	WAKEUP:    INOUT  STD_LOGIC;    
	XTALIN:    INOUT  STD_LOGIC;    
	XTALOUT:   INOUT  STD_LOGIC);
end cy7c68013a_56;
