-- generated by newgenasym Fri Mar 23 11:29:52 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \kt-93\ is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end \kt-93\;
