// generated by newgenasym  Tue Dec 27 17:32:27 2011


module \rd1-125  (\gnr+ , \gnr- , rct, \rd+ , \rd- , tct, \td+ , \td- , \yel+ , \yel- );
    inout \gnr+ ;
    inout \gnr- ;
    inout rct;
    inout \rd+ ;
    inout \rd- ;
    inout tct;
    inout \td+ ;
    inout \td- ;
    inout \yel+ ;
    inout \yel- ;


    initial
        begin
        end

endmodule
