-- generated by newgenasym Tue Dec 27 17:32:27 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \rd1-125\ is
    port (    
	\gnr+\:    INOUT  STD_LOGIC;    
	\gnr-\:    INOUT  STD_LOGIC;    
	RCT:       INOUT  STD_LOGIC;    
	\rd+\:     INOUT  STD_LOGIC;    
	\rd-\:     INOUT  STD_LOGIC;    
	TCT:       INOUT  STD_LOGIC;    
	\td+\:     INOUT  STD_LOGIC;    
	\td-\:     INOUT  STD_LOGIC;    
	\yel+\:    INOUT  STD_LOGIC;    
	\yel-\:    INOUT  STD_LOGIC);
end \rd1-125\;
