// generated by newgenasym  Thu Dec 08 11:46:11 2011


module atmega128l (\adc0/pf0 , \adc1/pf1 , \adc2/pf2 , \adc3/pf3 , aref, avcc, gnd1,
        gnd2, gnd3, \ic1/pd4 , \ic3/pe7 , \miso/pb3 , \mosi/pb2 , \oc1a/pb5 ,
        \oc1b/pb6 , \oc2/pb7 , \oc3a/pe3 , \oc3b/pe4 , \oc3c/pe5 , \oco/pb4 ,
        pa0, pa1, pa2, pa3, pa4, pa5, pa6, pa7, pc0, pc1, pc2, pc3, pc4,
        pc5, pc6, pc7, \pen# , pg0, pg1, pg2, \reset# , \rxd0/pdi , \rxd1/pd2 ,
        \sck/pb1 , \scl/pdo , \sda/pd1 , \ss/pb0 , \t1/pd6 , \t2/pd7 , \t3/pe6 ,
        \tck/pf4 , \tdi/pf7 , \tdo/pf6 , \tms/pf5 , \tosc1/pg4 , \tosc2/pg3 ,
        \txd0/pdo , \txd1/pd3 , vcc, vcc2, \xck0/pe2 , \xck1/pd5 , xtal1,
        xtal2);
    inout \adc0/pf0 ;
    inout \adc1/pf1 ;
    inout \adc2/pf2 ;
    inout \adc3/pf3 ;
    inout aref;
    inout avcc;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout \ic1/pd4 ;
    inout \ic3/pe7 ;
    inout \miso/pb3 ;
    inout \mosi/pb2 ;
    inout \oc1a/pb5 ;
    inout \oc1b/pb6 ;
    inout \oc2/pb7 ;
    inout \oc3a/pe3 ;
    inout \oc3b/pe4 ;
    inout \oc3c/pe5 ;
    inout \oco/pb4 ;
    inout pa0;
    inout pa1;
    inout pa2;
    inout pa3;
    inout pa4;
    inout pa5;
    inout pa6;
    inout pa7;
    inout pc0;
    inout pc1;
    inout pc2;
    inout pc3;
    inout pc4;
    inout pc5;
    inout pc6;
    inout pc7;
    inout \pen# ;
    inout pg0;
    inout pg1;
    inout pg2;
    inout \reset# ;
    inout \rxd0/pdi ;
    inout \rxd1/pd2 ;
    inout \sck/pb1 ;
    inout \scl/pdo ;
    inout \sda/pd1 ;
    inout \ss/pb0 ;
    inout \t1/pd6 ;
    inout \t2/pd7 ;
    inout \t3/pe6 ;
    inout \tck/pf4 ;
    inout \tdi/pf7 ;
    inout \tdo/pf6 ;
    inout \tms/pf5 ;
    inout \tosc1/pg4 ;
    inout \tosc2/pg3 ;
    inout \txd0/pdo ;
    inout \txd1/pd3 ;
    inout vcc;
    inout vcc2;
    inout \xck0/pe2 ;
    inout \xck1/pd5 ;
    inout xtal1;
    inout xtal2;


    initial
        begin
        end

endmodule
