-- generated by newgenasym Thu Mar 27 16:35:55 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity transf is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end transf;
