-- generated by newgenasym Fri Apr 28 09:39:01 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity n25q256mb_v2 is
    port (    
	C:         INOUT  STD_LOGIC;    
	DQ0:       INOUT  STD_LOGIC;    
	DQ1:       INOUT  STD_LOGIC;    
	DQ2:       INOUT  STD_LOGIC;    
	DQ3:       INOUT  STD_LOGIC;    
	\s#\:      INOUT  STD_LOGIC);
end n25q256mb_v2;
