-- generated by newgenasym Thu Jul 20 17:10:31 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SN74LVC1G80 is
    port (    
	CLK:       IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC);
end SN74LVC1G80;
