-- generated by newgenasym Thu May 24 11:11:36 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pat is
    port (    
	INPUT:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end pat;
