-- generated by newgenasym Fri Dec 01 16:17:31 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XP5 is
    port (    
	COL1:      INOUT  STD_LOGIC;    
	COL2:      INOUT  STD_LOGIC;    
	COL3:      INOUT  STD_LOGIC;    
	COL4:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	ROW1:      INOUT  STD_LOGIC;    
	ROW2:      INOUT  STD_LOGIC;    
	ROW3:      INOUT  STD_LOGIC;    
	ROW4:      INOUT  STD_LOGIC);
end XP5;
