-- generated by newgenasym Wed Dec 22 11:52:15 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity vt_npn is
    port (    
	b:         INOUT  STD_LOGIC;    
	c:         INOUT  STD_LOGIC;    
	e:         INOUT  STD_LOGIC);
end vt_npn;
