-- generated by newgenasym Mon Nov 20 12:20:09 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity JUMPER3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end JUMPER3;
