-- generated by newgenasym Thu Jul 03 11:11:06 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc3g07 is
    port (    
	A:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc3g07;
