// generated by newgenasym  Mon Oct 01 12:07:32 2012


module \tcm9-1  (p, pdot, sec, secct, secdot);
    inout p;
    inout pdot;
    inout sec;
    inout secct;
    inout secdot;


    initial
        begin
        end

endmodule
