// generated by newgenasym  Tue Apr 10 12:29:05 2018


module hmc832 (bias, cen, cp, \ld/sdo , rfn, rfp, sck, sdi, sen, vtune, xrefp);
    inout bias;
    inout cen;
    inout cp;
    inout \ld/sdo ;
    inout rfn;
    inout rfp;
    inout sck;
    inout sdi;
    inout sen;
    inout vtune;
    inout xrefp;


    initial
        begin
        end

endmodule
