// generated by newgenasym  Fri Jun 30 18:13:47 2006


module ds1337c (gnd, \inta* , \intb* , scl, sda, vcc);
    input gnd;
    output \inta* ;
    output \intb* ;
    inout scl;
    inout sda;
    input vcc;


    initial
        begin
        end

endmodule
