-- generated by newgenasym Fri Jun 30 18:13:47 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds1337c is
    port (    
	GND:       IN     STD_LOGIC;    
	\inta*\:   OUT    STD_LOGIC;    
	\intb*\:   OUT    STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end ds1337c;
