// generated by newgenasym  Wed Jul 05 11:18:56 2006


module max7384 (clk, ec, gnd, \rst* , sp, vcc, vcl);
    inout clk;
    input ec;
    input gnd;
    output \rst* ;
    input sp;
    input vcc;
    input vcl;


    initial
        begin
        end

endmodule
