-- generated by newgenasym Wed Jul 05 11:18:56 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max7384 is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	EC:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\rst*\:    OUT    STD_LOGIC;    
	SP:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VCL:       IN     STD_LOGIC);
end max7384;
