// generated by newgenasym  Mon Dec 14 15:42:26 2009


module ft2232d (\3v3out , acbus0, acbus1, acbus2, acbus3, adbus0, adbus1,
        adbus2, adbus3, adbus4, adbus5, adbus6, adbus7, agnd, avcc,
        bcbus0, bcbus1, bcbus2, bcbus3, bdbus0, bdbus1, bdbus2,
        bdbus3, bdbus4, bdbus5, bdbus6, bdbus7, eecs, eedata, eesk,
        gnd, gnd2, gnd3, gnd4, \pwren# , \reset# , \rstout# , \si/wua ,
        \si/wub , test, usbdm, usbdp, vcc, vcc2, vccioa, vcciob, xtin,
        xtout);
    inout \3v3out ;
    inout acbus0;
    inout acbus1;
    inout acbus2;
    inout acbus3;
    inout adbus0;
    inout adbus1;
    inout adbus2;
    inout adbus3;
    inout adbus4;
    inout adbus5;
    inout adbus6;
    inout adbus7;
    inout agnd;
    inout avcc;
    inout bcbus0;
    inout bcbus1;
    inout bcbus2;
    inout bcbus3;
    inout bdbus0;
    inout bdbus1;
    inout bdbus2;
    inout bdbus3;
    inout bdbus4;
    inout bdbus5;
    inout bdbus6;
    inout bdbus7;
    inout eecs;
    inout eedata;
    inout eesk;
    inout gnd;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout \pwren# ;
    inout \reset# ;
    inout \rstout# ;
    inout \si/wua ;
    inout \si/wub ;
    inout test;
    inout usbdm;
    inout usbdp;
    inout vcc;
    inout vcc2;
    inout vccioa;
    inout vcciob;
    inout xtin;
    inout xtout;


    initial
        begin
        end

endmodule
