-- generated by newgenasym Mon Aug 31 13:42:30 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity kf128_3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end kf128_3;
