// generated by newgenasym  Wed Mar 09 17:58:16 2005


module actste01 (gnd, gnd1, gnd2, out, vc, vdd);
    input gnd;
    input gnd1;
    input gnd2;
    output out;
    input vc;
    input vdd;


    initial
        begin
        end

endmodule
