-- generated by newgenasym Wed Mar 09 17:58:16 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ACTSTE01 is
    port (    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VC:        IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end ACTSTE01;
