// generated by newgenasym  Tue Jul 17 11:26:18 2007


module sn74lvc1g04 (a, gnd, nc, vcc, y);
    inout a;
    inout gnd;
    inout nc;
    inout vcc;
    inout y;


    initial
        begin
        end

endmodule
