-- generated by newgenasym Tue Jul 17 11:26:18 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SN74LVC1G04 is
    port (    
	A:         INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC);
end SN74LVC1G04;
