-- generated by newgenasym Tue Nov 29 18:06:21 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sg8002ca is
    port (    
	CLK:       OUT    STD_LOGIC;    
	OE:        IN     STD_LOGIC);
end sg8002ca;
