-- generated by newgenasym Fri Oct 22 17:31:43 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c_nfm21c is
    port (    
	\0ut\:     OUT    STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	SHIELD:    IN     STD_LOGIC);
end c_nfm21c;
