// generated by newgenasym  Thu Aug 26 21:13:15 2004


module \25lc040  (\cs* , \hold* , miso, mosi, sck, \wp* );
    input \cs* ;
    input \hold* ;
    output miso;
    input mosi;
    input sck;
    input \wp* ;


    initial
        begin
        end

endmodule
