// generated by newgenasym  Fri Jul 16 15:24:34 2004


module lt1568ign (\en* , gnda, gndb, inva, invb, \n.c. , outa, \outa* , outb, \outb* ,
        sa, sb, \v1+ , \v1- , \v2+ , \v2- );
    input \en* ;
    input gnda;
    input gndb;
    input inva;
    input invb;
    inout \n.c. ;
    output outa;
    output \outa* ;
    output outb;
    output \outb* ;
    input sa;
    input sb;
    input \v1+ ;
    input \v1- ;
    input \v2+ ;
    input \v2- ;


    initial
        begin
        end

endmodule
