// generated by newgenasym  Fri Jul 20 17:15:08 2007


module max5424 (cs, din, gnd, h, l, sclk, vdd, w);
    inout cs;
    inout din;
    input gnd;
    inout h;
    inout l;
    inout sclk;
    input vdd;
    inout w;


    initial
        begin
        end

endmodule
