-- generated by newgenasym Tue Feb 27 12:55:31 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xc9536xl is
    port (    
	IO11:      INOUT  STD_LOGIC;    
	IO110:     INOUT  STD_LOGIC;    
	IO111:     INOUT  STD_LOGIC;    
	IO112:     INOUT  STD_LOGIC;    
	IO113:     INOUT  STD_LOGIC;    
	IO114:     INOUT  STD_LOGIC;    
	IO115:     INOUT  STD_LOGIC;    
	IO116:     INOUT  STD_LOGIC;    
	IO117:     INOUT  STD_LOGIC;    
	IO12:      INOUT  STD_LOGIC;    
	IO13_GCK1: INOUT  STD_LOGIC;    
	IO14:      INOUT  STD_LOGIC;    
	IO15_GCK2: INOUT  STD_LOGIC;    
	IO16:      INOUT  STD_LOGIC;    
	IO17_GCK3: INOUT  STD_LOGIC;    
	IO18:      INOUT  STD_LOGIC;    
	IO19:      INOUT  STD_LOGIC;    
	IO21:      INOUT  STD_LOGIC;    
	IO210:     INOUT  STD_LOGIC;    
	IO211:     INOUT  STD_LOGIC;    
	IO212:     INOUT  STD_LOGIC;    
	IO213:     INOUT  STD_LOGIC;    
	IO214:     INOUT  STD_LOGIC;    
	IO215:     INOUT  STD_LOGIC;    
	IO216:     INOUT  STD_LOGIC;    
	IO217:     INOUT  STD_LOGIC;    
	IO22:      INOUT  STD_LOGIC;    
	IO23_GTS1: INOUT  STD_LOGIC;    
	IO24:      INOUT  STD_LOGIC;    
	IO25_GTS2: INOUT  STD_LOGIC;    
	IO26_GSR:  INOUT  STD_LOGIC;    
	IO27:      INOUT  STD_LOGIC;    
	IO28:      INOUT  STD_LOGIC;    
	IO29:      INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC;    
	TDO:       INOUT  STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC);
end xc9536xl;
