// generated by newgenasym  Thu Apr 10 11:58:19 2003


module cnp30 (a1, a10, a7, a8, a9, b10, b9, c5, c6, c7, c8);
    input a1;
    input a10;
    input a7;
    input a8;
    input a9;
    input b10;
    input b9;
    input c5;
    input c6;
    input c7;
    input c8;


    initial
        begin
        end

endmodule
