-- generated by newgenasym Thu Dec 23 15:21:15 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bas70dw-04\ is
    port (    
	A:         INOUT  STD_LOGIC;    
	AC:        INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end \bas70dw-04\;
