// generated by newgenasym  Fri May 21 11:07:35 2004


module fin1104 (dout1, \dout1* , dout2, \dout2* , dout3, \dout3* , dout4, \dout4* ,
        en, \en* , rin1, \rin1* , rin2, \rin2* , rin3, \rin3* , rin4, \rin4* ,
        vbb);
    output dout1;
    output \dout1* ;
    output dout2;
    output \dout2* ;
    output dout3;
    output \dout3* ;
    output dout4;
    output \dout4* ;
    input en;
    input \en* ;
    input rin1;
    input \rin1* ;
    input rin2;
    input \rin2* ;
    input rin3;
    input \rin3* ;
    input rin4;
    input \rin4* ;
    inout vbb;


    initial
        begin
        end

endmodule
