-- generated by newgenasym Fri May 21 11:07:35 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FIN1104 is
    port (    
	DOUT1:     OUT    STD_LOGIC;    
	\dout1*\:  OUT    STD_LOGIC;    
	DOUT2:     OUT    STD_LOGIC;    
	\dout2*\:  OUT    STD_LOGIC;    
	DOUT3:     OUT    STD_LOGIC;    
	\dout3*\:  OUT    STD_LOGIC;    
	DOUT4:     OUT    STD_LOGIC;    
	\dout4*\:  OUT    STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	RIN1:      IN     STD_LOGIC;    
	\rin1*\:   IN     STD_LOGIC;    
	RIN2:      IN     STD_LOGIC;    
	\rin2*\:   IN     STD_LOGIC;    
	RIN3:      IN     STD_LOGIC;    
	\rin3*\:   IN     STD_LOGIC;    
	RIN4:      IN     STD_LOGIC;    
	\rin4*\:   IN     STD_LOGIC;    
	VBB:       INOUT  STD_LOGIC);
end FIN1104;
