// generated by newgenasym  Wed Aug 20 11:20:54 2014


module lmk03001 (bias, clkout0, \clkout0* , clkout1, \clkout1* , clkout2,
        \clkout2* , clkout3, \clkout3* , clkout4, \clkout4* , clkout5,
        \clkout5* , clkout6, \clkout6* , clkout7, \clkout7* , clkuwire,
        cpout, datawire, fout, goe, ld, ldobyp1, ldobyp2, leuwire,
        oscin, \oscin* , \sync* );
    inout bias;
    inout clkout0;
    inout \clkout0* ;
    inout clkout1;
    inout \clkout1* ;
    inout clkout2;
    inout \clkout2* ;
    inout clkout3;
    inout \clkout3* ;
    inout clkout4;
    inout \clkout4* ;
    inout clkout5;
    inout \clkout5* ;
    inout clkout6;
    inout \clkout6* ;
    inout clkout7;
    inout \clkout7* ;
    inout clkuwire;
    inout cpout;
    inout datawire;
    inout fout;
    input goe;
    inout ld;
    input ldobyp1;
    input ldobyp2;
    inout leuwire;
    inout oscin;
    inout \oscin* ;
    inout \sync* ;


    initial
        begin
        end

endmodule
