// generated by newgenasym  Thu May 25 15:18:49 2017


module rj45_hfj11_1g41e (chs_gnd, gnd, \ledg+ , \ledg- , \ledy+ , \ledy- , mtg1, mtg2, \td1+ ,
        \td1- , \td2+ , \td2- , \td3+ , \td3- , \tdo+ , \tdo- );
    inout chs_gnd;
    inout gnd;
    inout \ledg+ ;
    inout \ledg- ;
    inout \ledy+ ;
    inout \ledy- ;
    inout mtg1;
    inout mtg2;
    inout \td1+ ;
    inout \td1- ;
    inout \td2+ ;
    inout \td2- ;
    inout \td3+ ;
    inout \td3- ;
    inout \tdo+ ;
    inout \tdo- ;


    initial
        begin
        end

endmodule
