-- generated by newgenasym Thu May 25 15:18:49 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45_hfj11_1g41e is
    port (    
	CHS_GND:   INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\ledg+\:   INOUT  STD_LOGIC;    
	\ledg-\:   INOUT  STD_LOGIC;    
	\ledy+\:   INOUT  STD_LOGIC;    
	\ledy-\:   INOUT  STD_LOGIC;    
	MTG1:      INOUT  STD_LOGIC;    
	MTG2:      INOUT  STD_LOGIC;    
	\td1+\:    INOUT  STD_LOGIC;    
	\td1-\:    INOUT  STD_LOGIC;    
	\td2+\:    INOUT  STD_LOGIC;    
	\td2-\:    INOUT  STD_LOGIC;    
	\td3+\:    INOUT  STD_LOGIC;    
	\td3-\:    INOUT  STD_LOGIC;    
	\tdo+\:    INOUT  STD_LOGIC;    
	\tdo-\:    INOUT  STD_LOGIC);
end rj45_hfj11_1g41e;
