// generated by newgenasym  Fri Oct 17 14:51:20 2003


module ltc1440is8 (gndd, hyst, \in+ , \in- , n3v3, out, p3v3, ref);
    input gndd;
    input hyst;
    input \in+ ;
    input \in- ;
    input n3v3;
    output out;
    input p3v3;
    input ref;


    initial
        begin
        end

endmodule
