// generated by newgenasym  Thu Nov 26 18:01:34 2009


module ten10 (\+vin1 , \+vin2 , \+vout , \-vin1 , \-vin2 , \-vout , \on/off );
    inout \+vin1 ;
    inout \+vin2 ;
    inout \+vout ;
    inout \-vin1 ;
    inout \-vin2 ;
    inout \-vout ;
    inout \on/off ;


    initial
        begin
        end

endmodule
