// generated by newgenasym  Tue Feb 27 12:06:12 2007


module \at65-107  (\c#200.5 , \c#201 , \c#2016 , \c#202 , \c#204 , \c#208 , gnd1, gnd10, gnd11, gnd12,
        gnd13, gnd14, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9,
        rf1, rf2, \vcc+ , \vcc- );
    inout \c#200.5 ;
    inout \c#201 ;
    inout \c#2016 ;
    inout \c#202 ;
    inout \c#204 ;
    inout \c#208 ;
    inout gnd1;
    inout gnd10;
    inout gnd11;
    inout gnd12;
    inout gnd13;
    inout gnd14;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout rf1;
    inout rf2;
    inout \vcc+ ;
    inout \vcc- ;


    initial
        begin
        end

endmodule
