// generated by newgenasym  Tue Jun 29 16:06:03 2004


module sma9376_1113 (in1, in2, in3, in4, in5);
    inout in1;
    input in2;
    input in3;
    input in4;
    input in5;


    initial
        begin
        end

endmodule
