-- generated by newgenasym Tue Jun 29 16:06:03 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sma9376_1113 is
    port (    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	IN3:       IN     STD_LOGIC;    
	IN4:       IN     STD_LOGIC;    
	IN5:       IN     STD_LOGIC);
end sma9376_1113;
