-- generated by newgenasym Fri Aug 17 17:58:33 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mic5363 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end mic5363;
