-- generated by newgenasym Thu Aug 16 10:28:26 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps2592a is
    port (    
	BFET:      INOUT  STD_LOGIC;    
	DVDT:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	ILIM:      INOUT  STD_LOGIC);
end tps2592a;
