// generated by newgenasym  Thu Oct 19 12:20:33 2006


module \si-50211  (chassis, gnd, led1a, led1c, led2a, led2c, rct, \rd+ , \rd- , tct,
        \td+ , \td- );
    inout chassis;
    inout gnd;
    inout led1a;
    inout led1c;
    inout led2a;
    inout led2c;
    inout rct;
    inout \rd+ ;
    inout \rd- ;
    inout tct;
    inout \td+ ;
    inout \td- ;


    initial
        begin
        end

endmodule
