// generated by newgenasym  Mon Jul 26 17:56:37 2004


module sn74cb3t3253 (\ea* , \eb* , ia, ib, s, ya, yb);
    input \ea* ;
    input \eb* ;
    inout [3:0] ia;
    inout [3:0] ib;
    input [1:0] s;
    inout ya;
    inout yb;


    initial
        begin
        end

endmodule
