// generated by newgenasym  Tue Sep 05 13:48:30 2017


module hmc545 (a, b, rf1, rf2, rfc);
    inout a;
    inout b;
    inout rf1;
    inout rf2;
    inout rfc;


    initial
        begin
        end

endmodule
