-- generated by newgenasym Tue Sep 05 13:48:30 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc545 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RFC:       INOUT  STD_LOGIC);
end hmc545;
