-- generated by newgenasym Tue Jul 01 15:08:43 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \hcpl-063l\ is
    port (    
	ANODE_A:   IN     STD_LOGIC;    
	ANODE_B:   IN     STD_LOGIC;    
	CATHODE_A: IN     STD_LOGIC;    
	CATHODE_B: IN     STD_LOGIC;    
	GNDD:      IN     STD_LOGIC;    
	P3V3:      IN     STD_LOGIC;    
	Q_A:       OUT    STD_LOGIC;    
	Q_B:       OUT    STD_LOGIC);
end \hcpl-063l\;
