-- generated by newgenasym Wed Nov 08 10:09:37 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g125 is
    port (    
	A:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc1g125;
