-- generated by newgenasym Mon Aug 16 11:52:07 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max803 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\reset*\:  OUT    STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end max803;
