// generated by newgenasym  Tue Jul 13 16:20:42 2010


module ds90lv031a (din1, din2, din3, din4, \dout1+ , \dout1- , \dout2+ , \dout2- ,
        \dout3+ , \dout3- , \dout4+ , \dout4- , en, en_n, gnd, vcc);
    inout din1;
    inout din2;
    inout din3;
    inout din4;
    inout \dout1+ ;
    inout \dout1- ;
    inout \dout2+ ;
    inout \dout2- ;
    inout \dout3+ ;
    inout \dout3- ;
    inout \dout4+ ;
    inout \dout4- ;
    inout en;
    inout en_n;
    input gnd;
    input vcc;


    initial
        begin
        end

endmodule
