// generated by newgenasym  Thu Dec 01 17:00:58 2016


module si53307 (\clk0* , clk0_p, \clk1* , clk1_p, clk_sel, oe, \q0* , q0_p, \q1* ,
        q1_p, sfout0, sfout1);
    inout \clk0* ;
    inout clk0_p;
    inout \clk1* ;
    inout clk1_p;
    inout clk_sel;
    inout oe;
    inout \q0* ;
    inout q0_p;
    inout \q1* ;
    inout q1_p;
    inout sfout0;
    inout sfout1;


    initial
        begin
        end

endmodule
