-- generated by newgenasym Thu Dec 01 17:00:58 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity si53307 is
    port (    
	\clk0*\:   INOUT  STD_LOGIC;    
	CLK0_P:    INOUT  STD_LOGIC;    
	\clk1*\:   INOUT  STD_LOGIC;    
	CLK1_P:    INOUT  STD_LOGIC;    
	CLK_SEL:   INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	\q0*\:     INOUT  STD_LOGIC;    
	Q0_P:      INOUT  STD_LOGIC;    
	\q1*\:     INOUT  STD_LOGIC;    
	Q1_P:      INOUT  STD_LOGIC;    
	SFOUT0:    INOUT  STD_LOGIC;    
	SFOUT1:    INOUT  STD_LOGIC);
end si53307;
