-- generated by newgenasym Thu Aug 21 18:19:11 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mp25p128 is
    port (    
	C:         INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	\hold*\:   INOUT  STD_LOGIC;    
	Q:         INOUT  STD_LOGIC;    
	\s*\:      INOUT  STD_LOGIC;    
	\w*\:      INOUT  STD_LOGIC);
end mp25p128;
